const {assert,login,report,pdf,form}=require('./helpers789.cjs');
const {PrismaClient}=require('@prisma/client'),db=new PrismaClient(),{randomUUID}=require('node:crypto');
const {AgentCenterService}=require('../apps/api/dist/agent-center.service');
const {extractPlanText,cleanPlanIntent}=require('../apps/api/dist/agent-intent');
const {checkAgentOperation}=require('../apps/api/dist/agent-operation');
const results=[],pass=name=>{results.push({name,result:'PASS'});console.log('PASS',name);};
(async()=>{const sessions=[];try{
 const t=await login('trader'),c=await login('carrier'),other=await login('trader.b'),a=await login('admin');sessions.push(t,c,other,a);
 const create=(client,capability,contextType='page',contextId='')=>client.call('POST','/agents/center/conversations',{capability,contextType,contextId});
 const center=await create(t,'PLAN');
 for(const client of [c,other,a]){await client.call('GET','/agents/center/conversations/'+center.id,null,404);await client.call('POST','/agents/center/conversations/'+center.id+'/cancel',{},404);assert(!(await client.call('GET','/agents/center/conversations')).items.some(x=>x.id===center.id));}
 const personal=new AgentCenterService(db,{}, {permission(){}}, {}, {}, {});
 await assert.rejects(()=>personal.conversation(center.id,{user:{id:'different-user-in-same-company',businessEntityId:center.entityId}}),e=>e.status===404);
 await create(t,'UNAUTHORIZED','page','').then(()=>assert.fail('invalid capability'),e=>assert(e.message.includes('400')));
 const foreign=await db.transportDemand.findFirst({where:{businessEntityId:other.user.businessEntityId,deletedAt:null}});
 if(foreign)await t.call('POST','/agents/center/conversations',{capability:'PLAN',contextType:'transport-demand',contextId:foreign.id},404);
 pass('对话按本人账号隔离；平台、他人和同企业其他账号均不可读取；上下文保持原业务权限');
 const intent=cleanPlanIntent(extractPlanText('从辽宁省盘锦市盘锦站运输到广东省广州市广州国际港站，100吨玉米，散货'));
 assert.equal(intent.originText,'辽宁省盘锦市盘锦站');assert.equal(intent.destinationText,'广东省广州市广州国际港站');assert.equal(intent.quantity,100);
 assert.deepEqual(cleanPlanIntent({quantity:-1,originText:'',price:1,origin:{lng:1},loadingType:'fake',departureAt:'yesterday'}),{});
 const example=await t.call('GET','/plans/examples'),key=randomUUID();
 const draft=await t.call('POST','/agents/center/conversations/'+center.id+'/messages',{requestKey:key,question:'从盘锦站运输到广州国际港站，100吨玉米，散货'});
 assert.equal(draft.response.type,'PLAN_CONFIRM');assert.equal(draft.response.draft.quantity,100);assert.equal(draft.response.draft.grainId,example.grainId);assert(draft.response.draft.origin?.nodeId);assert(draft.response.draft.destination?.nodeId);
 const duplicate=await t.call('POST','/agents/center/conversations/'+center.id+'/messages',{requestKey:key,question:draft.question});assert.equal(duplicate.id,draft.id);
 await t.call('POST','/agents/center/conversations/'+center.id+'/messages',{requestKey:key,question:'不同的问题'},409);
 assert.equal((await t.call('GET','/agents/center/conversations/'+center.id)).turns.length,1);
 pass('自然语言运输条件提取、可核对节点定位、默认时间说明及重复请求幂等');
 const input={...example,allowMultimodal:true,allowTransfer:true,maxTransfers:4,allowContainerization:true,allowModel:true,preference:'BALANCED'};delete input.notes;
 await t.call('POST','/agents/center/conversations/'+center.id+'/solve',{requestKey:randomUUID()},400);
 await t.call('POST','/agents/center/conversations/'+center.id+'/solve',{requestKey:randomUUID(),input:{...input,origin:{...input.origin,matchKind:'APPROXIMATE'}}},400);
 const solveKey=randomUUID(),solved=await t.call('POST','/agents/center/conversations/'+center.id+'/solve',{requestKey:solveKey,input});
 assert.equal(solved.response.type,'PLAN_RESULT');const view=solved.response.plan;assert(view.candidates.length>=2);assert(view.candidates.some(x=>x.modes.length>1));
 const run=await t.call('GET','/plans/runs/'+view.id);assert.equal(run.id,view.id);assert.equal(run.input.allowModel,true);assert(run.input.solverInfo.advisor.status==='SUCCEEDED','真实模型通道建议应成功');
 for(const candidate of view.candidates){assert(run.candidates.some(x=>x.id===candidate.id));assert(candidate.segments.length);assert(candidate.recommendationLabel);}
 const again=await t.call('POST','/agents/center/conversations/'+center.id+'/solve',{requestKey:solveKey,input});assert.equal(again.id,solved.id);
 await t.call('POST','/agents/center/conversations/'+center.id+'/solve',{requestKey:solveKey,input:{...input,quantity:101}},409);
 pass('真实求解器和模型通道建议联动；动态推荐、费用与分段地图结果可回到已有方案页面；求解重试不重复生成');
 const fixture=require('../docs/acceptance/intermodal-workspace-fixture.json'),task=await db.transportTask.findFirst({where:{businessId:fixture.bulkBusinessId,mode:'ROAD'}});
 assert(task);const chat=await create(t,'TRACK','task',task.id);
 const before=await db.executionEvent.count(),answer=await t.call('POST','/agents/center/conversations/'+chat.id+'/messages',{requestKey:randomUUID(),question:'这辆车的运输状态和起运目的地是什么？请根据现有记录回答。'});
 assert.equal(answer.response.structured.task.id,task.id);assert.equal(answer.response.provider,'DEEPSEEK');assert.equal(await db.executionEvent.count(),before);
 await create(other,'TRACK','task',task.id).then(()=>assert.fail('foreign task'),e=>assert(e.message.includes('404')));
 const doc=await t.call('POST','/documents/recognize/'+task.id,form(pdf(['Waybill: AGENT-20261003','Cargo: Corn','Quantity: 5 t']),'agent-center-test.pdf'));
 assert.equal(doc.recognized.fields.waybillNo,'AGENT-20261003');await other.call('GET','/documents/'+doc.id,null,404);
 pass('问踪默认调用已配置模型、引用本人可见运输记录且不代执行业务；单据识别与越权拦截保持有效');
 const cancelChat=await create(t,'PLAN');const mock=new AgentCenterService(db,{}, {permission(){}}, {}, {}, {});
 mock.planDraft=async(_c,_q,_r,signal)=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>resolve({}),20000);signal.addEventListener('abort',()=>{clearTimeout(timer);try{checkAgentOperation(signal);}catch(e){reject(e);}},{once:true});});
 const request={user:{id:t.user.id,businessEntityId:cancelChat.entityId}},pending=mock.send(cancelChat.id,{question:'测试可停止的分析',requestKey:randomUUID()},request).catch(e=>e);
 while(!mock.active.has(t.user.id))await new Promise(r=>setTimeout(r,5));
 assert.equal((await mock.cancel(cancelChat.id,request)).status,'STOPPING');assert.equal((await pending).status,409);assert.equal(await db.agentTurn.count({where:{conversationId:cancelChat.id}}),0);assert(!mock.active.has(t.user.id));
 pass('停止分析会中断模型等待、保留对话输入且释放账号任务锁');
 report('agent-center',results,{conversationId:center.id,planRunId:view.id,candidateCount:run.candidates.length,modeFamilies:[...new Set(run.candidates.map(x=>x.familyLabel))],taskId:task.id,documentId:doc.id});
 }finally{await Promise.all(sessions.map(s=>s.logout()));await db.$disconnect();}})().catch(e=>{console.error(e);process.exit(1);});
