const assert=require('node:assert/strict'),fs=require('node:fs'),{randomUUID}=require('node:crypto');require('dotenv').config();
const {PrismaClient}=require('@prisma/client');const db=new PrismaClient(),url='http://127.0.0.1:3001/api',stamp=Date.now(),results=[],sessions=[];
const day=n=>new Date(Date.now()+n*86400000).toISOString(),pass=name=>{console.log('PASS',name);results.push({name,result:'PASS'});};
async function login(username,driver=false){const prefix=driver?'/driver':'/auth';const r=await fetch(url+prefix+'/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password:process.env.SEED_PASSWORD})});const j=await r.json();assert.equal(r.status,201,JSON.stringify(j));let cookie=r.headers.getSetCookie()[0].split(';')[0];const token=j.data.accessToken;const raw=async(method,path,body)=>{const r=await fetch(url+path,{method,headers:{Authorization:'Bearer '+token,Cookie:cookie,...(body instanceof FormData?{}:{'Content-Type':'application/json'})},...(body?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};};const call=async(method,path,body,status=method==='GET'?200:201)=>{const r=await raw(method,path,body);assert.equal(r.status,status,`${path}: ${JSON.stringify(r.data)}`);return r.data.data;};const session={call,raw,prefix,token,user:j.data.user};sessions.push(session);return session;}
(async()=>{assert.notEqual(process.env.NODE_ENV,'production');let driverOther;
try{
 const t=await login('trader'),c=await login('carrier'),a=await login('admin'),b=await login('trader.b'),driver=await login('driver',true);
 const original=await db.user.findUniqueOrThrow({where:{username:'driver'}});driverOther=await db.user.create({data:{username:'phase5-driver-'+stamp,displayName:'Phase5 隔离验证司机',passwordHash:original.passwordHash,businessEntityId:'carrier-b',isTestData:true,roles:{create:{role:{connect:{code:'driver'}}}}}});const other=await login(driverOther.username,true);
 await driver.call('GET','/contracts',null,401);await c.call('GET','/driver/tasks',null,401);await b.call('POST','/contracts/templates',{type:'MAIN',name:'越权模板',body:'越权模板正文，仅作权限验证',mode:'A',effectiveFrom:day(-1)},403);pass('PC 与司机令牌隔离，模板维护限制平台');
 const opts=await t.call('GET','/transport-options'),grain=opts.grains[0],mode=opts.modes[0];
 await a.call('POST','/trade-orders/import',{businessNo:'JY-P5-'+stamp,businessEntityId:'trader-a',recipient:'Phase5 验收收货方',shipperContact:'验收发货人',shipperPhone:'13800000001',recipientContact:'验收收货人',recipientPhone:'13800000002',sourceSystem:'phase5-acceptance',sourceRecordId:String(stamp),items:[{lineNo:'1',grainId:grain.id,cargoName:'Phase5 验收粮食',specification:'开发样例',quantity:100}]});
 const item=(await t.call('GET','/trade-orders?q=JY-P5-'+stamp)).items[0];
 async function confirmation(name){const d=await t.call('POST','/transport-demands',{orderItemId:item.id,name:'Phase5 '+name+' '+stamp,quantity:10,originCodes:['210000','211100','211102'],originAddress:'盘锦验收粮库',destinationCodes:['440000','440100','440112'],destinationAddress:'广州验收仓库',departureAt:day(10),arrivalAt:day(18),modeIds:[mode.id],allowMultimodal:true,allowTransfer:true,maxTransfers:2,loadingType:'BULK',preference:'BALANCED',budget:8000,contact:'验收联系人',phone:'13800000001',notes:'Phase5 模拟验收，非实际运输委托'});const p=await t.call('POST','/matches/publications',{demandId:d.id,version:d.version,mode:'PUBLIC',deadline:day(5),quoteType:'PER_TON',budgetPublic:false,contactPublic:false,allowPartial:false,notes:'Phase5 模拟验收'});let view=await c.call('GET',`/matches/publications/${p.id}`);const response=await c.call('POST',`/matches/publications/${p.id}/quote`,{publicationVersion:view.version,terms:{quantity:10,price:350,unit:'PER_TON',taxIncluded:true,departureAt:day(10),arrivalAt:day(15),validUntil:day(4),capability:'验收运输资源',followOriginalPlan:true,note:'模拟报价'}});view=await t.call('GET',`/matches/publications/${p.id}`);await t.call('POST',`/matches/responses/${response.id}/negotiate`,{publicationVersion:view.version,version:view.responses[0].version,action:'ACCEPT',note:'验收接受'});view=await t.call('GET',`/matches/publications/${p.id}`);return t.call('POST',`/matches/responses/${response.id}/confirm`,{publicationVersion:view.version,version:view.responses[0].version});}
 const terms={settlement:'回单核对后 30 日内结算',requirements:'留存装卸及签收凭证',platformFeeCents:10000,expiresAt:day(60)};
 const conf=await confirmation('A 模式');const p=await t.call('POST','/contracts',{confirmationId:conf.id,...terms});
 const detail=()=>t.call('GET','/contracts/'+p.id);let cp=await detail();assert.equal(cp.revisions.length,1);assert.equal(cp.revisions[0].documents.length,2);const digest=cp.revisions[0].digest;
 await b.call('GET','/contracts/'+p.id,null,404);await t.call('POST',`/matches/confirmations/${conf.id}/cancel`,{version:conf.version,reason:'验证合同锁定'},409);
 const business={packageId:p.id,mode:'SINGLE',needsContainerization:true,segments:[{mode:'ROAD',origin:'盘锦验收粮库',destination:'营口验收港'},{mode:'WATER',origin:'营口验收港',destination:'广州验收仓库'}]};await c.call('POST','/fulfillment',business,409);
 const act=async(who,id,action,extra={},status=201)=>{const current=await who.call('GET','/contracts/'+id);return who.call('POST',`/contracts/${id}/${action}`,{version:current.version,...extra},status);};
 await act(t,p.id,'submit');await act(c,p.id,'return',{reason:'补充作业说明'});await act(t,p.id,'submit');await act(c,p.id,'approve');
 await act(a,p.id,'sign',{documentType:'MAIN',acknowledged:true},403);await act(t,p.id,'sign',{documentType:'MAIN',acknowledged:false},400);
 for(const who of [t,c])for(const documentType of ['MAIN','ADDENDUM'])await act(who,p.id,'sign',{documentType,acknowledged:true});
 cp=await detail();assert.equal(cp.status,'EFFECTIVE');assert.equal(cp.revisions[0].signatures.length,4);assert.equal(cp.revisions[0].digest,digest);await act(c,p.id,'sign',{documentType:'MAIN',acknowledged:true},400);pass('合同双文件快照、退回、A 模式四项签署、禁止代签、生效门禁');
 const biz=await c.call('POST','/fulfillment',business);await t.call('POST','/fulfillment',business,403);await b.call('GET','/fulfillment/'+biz.id,null,404);const vehicle=await c.call('POST','/fulfillment/vehicles',{plate:'辽验'+String(stamp).slice(-6),capacityKg:30000});const task=await c.call('POST',`/fulfillment/${biz.id}/tasks`,{segment:1,quantityKg:10000,driverId:driver.user.id,vehicleId:vehicle.id,resource:'Phase5 模拟运输任务'});await c.call('POST',`/fulfillment/${biz.id}/tasks`,{segment:1,quantityKg:1,driverId:driver.user.id,vehicleId:vehicle.id,resource:''},409);assert.equal((await other.call('GET','/driver/tasks')).length,0);await other.call('POST',`/driver/tasks/${task.id}/events`,{type:'ACCEPT',requestKey:randomUUID()},404);pass('生效合同下发任务、区段数量上限、其他企业和司机隔离');
 const event=async(who,taskId,type,extra={},status=201)=>who.call('POST',`${who===driver?'/driver':'/fulfillment'}/tasks/${taskId}/events`,{type,requestKey:randomUUID(),...extra},status);
 await event(driver,task.id,'DEPART',{},409);const requestKey=randomUUID();const one=await driver.call('POST',`/driver/tasks/${task.id}/events`,{type:'ACCEPT',requestKey});const two=await driver.call('POST',`/driver/tasks/${task.id}/events`,{type:'ACCEPT',requestKey});assert.equal(one.id,two.id);await driver.call('POST',`/driver/tasks/${task.id}/events`,{type:'DEPART',requestKey},409);await event(driver,task.id,'AT_LOADING');await event(driver,task.id,'LOAD',{quantityKg:10000},400);
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');async function upload(who,taskId){const f=new FormData();f.append('file',new Blob([png],{type:'image/png'}),'phase5-evidence.png');return who.call('POST',`${who===driver?'/driver':'/fulfillment'}/tasks/${taskId}/evidence`,f);}
 const evidence=await upload(driver,task.id);await event(driver,task.id,'LOAD',{quantityKg:10000,evidenceId:evidence.id});await event(driver,task.id,'DEPART');const issue=await driver.call('POST',`/driver/tasks/${task.id}/issues`,{type:'WAITING',description:'开发验收：等待卸货泊位'});await event(driver,task.id,'ARRIVE');await event(driver,task.id,'UNLOAD',{quantityKg:9000},400);await event(driver,task.id,'UNLOAD',{quantityKg:10000});await event(driver,task.id,'RECEIPT',{evidenceId:evidence.id,receiver:'验收收货人'});await event(driver,task.id,'COMPLETE',{},409);await c.call('POST',`/fulfillment/issues/${issue.id}/resolve`,{resolution:'验收：泊位已安排，等待解除'});await event(driver,task.id,'COMPLETE');const evCount=await db.executionEvent.count({where:{taskId:task.id}});assert.equal(evCount,8);pass('司机完整节点、顺序和幂等校验、单据必填、数量偏差、异常闭环');
 const batch=await c.call('POST',`/fulfillment/${biz.id}/batches`,{name:'验收散改集批次',quantityKg:10000});await c.call('POST',`/fulfillment/${biz.id}/batches`,{name:'超量验证',quantityKg:1},400);
 await c.call('POST',`/fulfillment/batches/${batch.id}/arrivals`,{version:1,plate:'辽A12345',grossKg:15000,tareKg:10000,ticketNo:'TEST-1'});await c.call('POST',`/fulfillment/batches/${batch.id}/arrivals`,{version:2,plate:'辽A67890',grossKg:16000,tareKg:11000,ticketNo:'TEST-2'});let batches=(await c.call('GET','/fulfillment/'+biz.id)).batches,bch=batches[0];
 const box={version:3,boxNo:'TEST'+stamp,boxType:'20GP',seal:'SEAL01',vessel:'模拟粮运轮',voyage:'QA-001',sources:bch.arrivals.map(v=>({arrivalId:v.id,quantityKg:5000}))};await c.call('POST',`/fulfillment/batches/${batch.id}/boxes`,{...box,sources:[{arrivalId:bch.arrivals[0].id,quantityKg:6000}]},400);await c.call('POST',`/fulfillment/batches/${batch.id}/boxes`,box);await c.call('POST',`/fulfillment/batches/${batch.id}/boxes`,{...box,version:4,boxNo:'EXTRA'+stamp},400);pass('多车辆入箱来源、批次和入箱数量守恒、航次关联');
 const water=await c.call('POST',`/fulfillment/${biz.id}/tasks`,{segment:2,quantityKg:10000,resource:'模拟粮运轮 / QA-001 / 运单 QA-001',batchId:batch.id,boxNo:box.boxNo});await event(c,water.id,'AT_LOADING');const wf=await upload(c,water.id);for(const [type,extra] of [['LOAD',{quantityKg:10000,evidenceId:wf.id}],['DEPART',{}],['ARRIVE',{}],['UNLOAD',{quantityKg:10000}],['RECEIPT',{receiver:'广州验收仓库',evidenceId:wf.id}],['COMPLETE',{}]])await event(c,water.id,type,extra);const completed=await c.call('GET','/fulfillment/'+biz.id);assert.equal(completed.completedKg,10000);assert.equal(completed.tasks.reduce((n,t)=>n+(t.unloadedKg||0),0),20000);pass('水运 PC 执行与箱号关联，末段履约汇总避免重复计量');
 const archive=await c.call('GET',`/contracts/${p.id}/archive`);assert.ok(archive.notice.includes('模拟'));assert.equal(archive.confirmation.response.carrierId,'carrier-a');assert.ok(archive.performance.tasks.some(t=>t.evidence.length));await b.call('GET',`/contracts/${p.id}/archive`,null,404);pass('合同档案包含签署、成交和执行证据索引，并实施归属校验');
 await t.call('POST',`/contracts/${p.id}/change`,{...terms,settlement:'回单核对后 45 日内结算',version:(await detail()).version,kind:'CHANGE',reason:'模拟变更结算周期'});await act(t,p.id,'submit');await act(c,p.id,'approve');for(const who of [t,c])for(const documentType of ['MAIN','ADDENDUM'])await act(who,p.id,'sign',{documentType,acknowledged:true});cp=await detail();assert.equal(cp.revisions[0].digest,digest);assert.equal(cp.revisions.length,2);assert.equal(cp.revisions[1].terms.settlement,'回单核对后 45 日内结算');pass('变更重新完整签署，原始正文与签署记录保留');
 const originals=await a.call('GET','/contracts/templates'),base=originals.find(v=>v.type==='ADDENDUM'&&v.status==='PUBLISHED');const tb=await a.call('POST','/contracts/templates',{type:'ADDENDUM',name:'Phase5 B 模式验收模板',body:base.body,mode:'B',effectiveFrom:new Date().toISOString()});await a.call('POST',`/contracts/templates/${tb.id}/publish`);
 const cfB=await confirmation('B 模式'),pb=await t.call('POST','/contracts',{confirmationId:cfB.id,...terms});
 const restore=await a.call('POST','/contracts/templates',{type:'ADDENDUM',name:base.name,body:base.body,mode:base.mode,effectiveFrom:new Date().toISOString()});await a.call('POST',`/contracts/templates/${restore.id}/publish`);
 await act(t,pb.id,'submit');await act(c,pb.id,'approve');for(const who of [t,c])for(const documentType of ['MAIN','ADDENDUM'])await act(who,pb.id,'sign',{documentType,acknowledged:true});assert.equal((await t.call('GET','/contracts/'+pb.id)).status,'SIGNING');await c.call('POST','/fulfillment',{...business,packageId:pb.id,mode:'TRADITIONAL'},409);await act(a,pb.id,'sign',{documentType:'ADDENDUM',acknowledged:true});const traditional=await c.call('POST','/fulfillment',{...business,packageId:pb.id,mode:'TRADITIONAL',needsContainerization:false,segments:[{mode:'ROAD',origin:'盘锦验收粮库',destination:'广州验收仓库'}]});assert.equal((await c.call('GET','/fulfillment/'+traditional.id)).waybillNo,null);pass('B 模式平台签署门禁，传统模式不生成联运运单');
 const uiConf=await confirmation('浏览器签署');fs.writeFileSync('docs/acceptance/phase5-fixture.json',JSON.stringify({confirmationId:uiConf.id,packageId:p.id,businessId:biz.id,traditionalBusinessId:traditional.id,vehicleId:vehicle.id,driverId:driver.user.id,createdAt:new Date().toISOString()},null,2));
 pass('保留独立浏览器验收承运确认与司机资源');
}finally{for(const s of sessions)await s.call('POST',s.prefix+'/logout');if(driverOther)await db.user.update({where:{id:driverOther.id},data:{status:'DISABLED',deletedAt:new Date()}});await db.$disconnect();fs.writeFileSync('docs/acceptance/phase5-api.json',JSON.stringify({at:new Date().toISOString(),results},null,2));}})().catch(e=>{console.error(e);process.exitCode=1;});
