const assert=require('node:assert/strict'),fs=require('node:fs');require('dotenv').config();
const {PrismaClient}=require('@prisma/client');const db=new PrismaClient();
const URL=process.env.API_URL||'http://127.0.0.1:3001/api',stamp=Date.now(),day=n=>new Date(Date.now()+n*86400000).toISOString(),results=[],sessions=[],created=[];
const pass=name=>{results.push({name,result:'PASS'});console.log('PASS',name);};
async function login(username){const res=await fetch(URL+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password:process.env.SEED_PASSWORD})});assert.equal(res.status,201);const {accessToken:token}= (await res.json()).data,cookie=res.headers.getSetCookie().find(c=>c.startsWith('grain_refresh=')).split(';')[0];const raw=async(method,path,data)=>{const r=await fetch(URL+path,{method,headers:{Authorization:'Bearer '+token,Cookie:cookie,'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});return {status:r.status,body:await r.json()};};const call=async(method,path,data,status=method==='POST'?201:200)=>{const r=await raw(method,path,data);assert.equal(r.status,status,`${method} ${path}: ${JSON.stringify(r.body)}`);return r.body.data;};sessions.push({call});return {call,raw};}
(async()=>{assert.notEqual(process.env.NODE_ENV,'production');let t,c,a,b,cb,supply;
try{
 t=await login('trader');c=await login('carrier');a=await login('admin');b=await login('trader.b');cb=await login('carrier.b');
 const opts=await t.call('GET','/transport-options'),grain=opts.grains.find(g=>g.code==='1'),mode=opts.modes.find(m=>m.code==='1');
 await a.call('POST','/trade-orders/import',{businessNo:'JY-P4-'+stamp,businessEntityId:'trader-a',recipient:'Phase4验收收货方',shipperContact:'验收发货人',shipperPhone:'13800000001',recipientContact:'验收收货人',recipientPhone:'13800000002',sourceSystem:'phase4-acceptance',sourceRecordId:String(stamp),items:[{lineNo:'1',grainId:grain.id,cargoName:'验收玉米',specification:'国标二等',quantity:500}]});
 const item=(await t.call('GET','/trade-orders?q=JY-P4-'+stamp)).items[0];
 const base={orderItemId:item.id,name:'Phase4验收需求 '+stamp,quantity:10,originCodes:['210000','211100','211102'],originAddress:'盘锦验收粮库',destinationCodes:['440000','440100','440112'],destinationAddress:'广州验收仓库',departureAt:day(10),arrivalAt:day(18),modeIds:[mode.id],allowMultimodal:true,allowTransfer:true,maxTransfers:2,loadingType:'BULK',preference:'BALANCED',budget:8000,contact:'私有测试联系人',phone:'13800000001',notes:'Phase4 开发验收，非真实货运委托'};
 const create=async(name,qty=10)=>{const d=await t.call('POST','/transport-demands',{...base,name:name+' '+stamp,quantity:qty});created.push(d.id);return d;};
 const pubdto=d=>({demandId:d.id,version:d.version,mode:'PUBLIC',deadline:day(5),quoteType:'PER_TON',budgetPublic:false,contactPublic:false,allowPartial:true,notes:'Phase4 开发验收'});
 const publish=async(d,extra={})=>(await t.call('POST','/matches/publications',{...pubdto(d),...extra})).id;
 const detail=(id,who=t)=>who.call('GET','/matches/publications/'+id);
 const terms=(quantity=6,price=350)=>({quantity,price,unit:'PER_TON',taxIncluded:true,departureAt:day(10),arrivalAt:day(15),validUntil:day(4),capability:'验收运力：防潮车辆和转运组织',followOriginalPlan:true,note:'测试价格，不作为实际报价'});
 const offer=async(id,who=c,term=terms())=>{const p=await detail(id,who);return who.call('POST',`/matches/publications/${id}/quote`,{publicationVersion:p.version,terms:term});};
 const act=async(id,rid,who,action,term)=>{const p=await detail(id,who),r=p.responses.find(r=>r.id===rid);return who.call('POST',`/matches/responses/${rid}/negotiate`,{version:r.version,publicationVersion:p.version,action,note:'验收操作',...(term?{terms:term}:{})});};
 let d=await create('公开分量承接'),pid=await publish(d);
 await t.call('POST','/matches/publications',pubdto(d),409);await c.call('POST','/matches/publications',pubdto(d),403);await a.call('POST','/matches/publications',pubdto(d),403);
 assert.ok((await t.call('GET','/matches/publications?minQuantity=9&maxQuantity=11&publicationMode=PUBLIC')).items.some(x=>x.id===pid));assert.ok(!(await t.call('GET','/matches/publications?minQuantity=11')).items.some(x=>x.id===pid));await t.call('GET','/matches/publications?minQuantity=12&maxQuantity=1',null,400);await t.call('GET','/matches/publications?departureFrom=2030-01-02T00:00:00Z&departureTo=2030-01-01T00:00:00Z',null,400);pass('数量范围与发布方式组合筛选，反向数量/日期范围拦截');
 const publicView=await detail(pid,b);assert.equal(publicView.contact,null);assert.equal(publicView.budget,null);assert.ok(!JSON.stringify(publicView).includes('私有测试联系人'));assert.equal(publicView.responses.length,0);
 const r=await offer(pid);await offer(pid,cb,terms(6,360));assert.equal((await detail(pid,c)).responses.length,1);assert.equal((await detail(pid,cb)).responses.length,1);assert.equal((await detail(pid)).responses.length,2);assert.equal((await detail(pid,a)).responses.length,2);assert.equal((await detail(pid,b)).responses.length,0);pass('公开发布、贸易只读隐私、物流报价互相隔离、平台只读');
 let p=await detail(pid,c);await c.call('POST',`/matches/responses/${r.id}/negotiate`,{version:1,publicationVersion:p.version,action:'ACCEPT',note:''},400);
 await act(pid,r.id,t,'COUNTER',terms(6,330));await act(pid,r.id,c,'COUNTER',terms(6,340));await act(pid,r.id,t,'ACCEPT');
 p=await detail(pid);let rr=p.responses.find(x=>x.id===r.id);assert.equal(rr.rounds.length,4);assert.deepEqual(rr.rounds.map(x=>x.terms.price),[350,330,340,340]);assert.equal(rr.terms.totalCents,204000);assert.equal(p.stage,'PENDING_CONFIRM');
 const confirm={version:rr.version,publicationVersion:p.version};let conf=await t.call('POST',`/matches/responses/${rr.id}/confirm`,confirm);await t.call('POST',`/matches/responses/${rr.id}/confirm`,confirm,409);assert.equal(conf.quantityKg,6000);d=await t.call('GET','/transport-demands/'+d.id);assert.equal(d.matchedKg,6000);assert.equal(d.matchStage,'PARTIAL');await t.call('POST',`/transport-demands/${d.id}/withdraw`,{version:d.version},409);await t.call('POST',`/transport-demands/${d.id}/cancel`,{version:d.version},409);pass('多轮条款不可变、自我接受拦截、分量承运与重复确认保护');
 p=await detail(pid);const br=p.responses.find(x=>x.carrierId==='carrier-b');await t.call('POST',`/matches/responses/${br.id}/negotiate`,{version:br.version,publicationVersion:p.version,action:'ACCEPT',note:''},400);
 await act(pid,br.id,cb,'COUNTER',terms(4,350));await act(pid,br.id,t,'ACCEPT');p=await detail(pid);const br2=p.responses.find(x=>x.id===br.id);await t.call('POST',`/matches/responses/${br.id}/confirm`,{version:br2.version,publicationVersion:p.version});p=await detail(pid);assert.equal(p.status,'MATCHED');assert.equal(p.matchedKg,10000);assert.equal((await t.call('GET','/transport-demands/'+d.id)).matchStage,'MATCHED');
 await t.call('POST',`/matches/confirmations/${conf.id}/cancel`,{version:conf.version,reason:'开发验收取消承运'});await t.call('POST',`/matches/confirmations/${conf.id}/cancel`,{version:conf.version,reason:'再次取消'},409);p=await detail(pid);assert.equal(p.status,'CLOSED');assert.equal(p.matchedKg,4000);assert.equal(p.responses.find(x=>x.id===r.id).confirmations[0].status,'CANCELLED');
 const rematch=await publish(await t.call('GET','/transport-demands/'+d.id));assert.equal((await detail(rematch)).quantityKg,6000);pass('剩余量校验、全量完成、取消释放与剩余需求重新发布');
 d=await create('定向权限');const direct=await publish(d,{mode:'DIRECTED',targetCarrierId:'carrier-a',allowPartial:false});await detail(direct,c);await cb.call('GET','/matches/publications/'+direct,null,404);await b.call('GET','/matches/publications/'+direct,null,404);assert.ok(!(await cb.call('GET','/matches/publications?q='+stamp)).items.some(x=>x.id===direct));await offer(direct,c,terms(10));pass('定向发布在列表、详情和报价入口均实施主体隔离');
 p=await detail(direct);const dr=p.responses[0];await act(direct,dr.id,t,'REJECT');await act(direct,dr.id,c,'COUNTER',terms(10));await act(direct,dr.id,c,'WITHDRAW');await act(direct,dr.id,c,'COUNTER',terms(10));
 // Change only our test fixture's validity to exercise time-sensitive guards without waiting days.
 const expiredTerms={...terms(10),validUntil:day(-1)};await db.matchResponse.update({where:{id:dr.id},data:{terms:JSON.stringify(expiredTerms)}});p=await detail(direct);await t.call('POST',`/matches/responses/${dr.id}/negotiate`,{version:p.responses[0].version,publicationVersion:p.version,action:'ACCEPT',note:''},400);
 await db.matchPublication.update({where:{id:direct},data:{deadline:new Date(day(-1))}});p=await detail(direct);assert.equal(p.status,'EXPIRED');assert.equal((await t.call('GET','/transport-demands/'+d.id)).matchStage,'REMATCH');pass('拒绝/撤回后重新报价、过期报价拒绝接受、发布到期同步');
 d=await create('并发确认');const raceId=await publish(d);await offer(raceId,c,terms(6));await offer(raceId,cb,terms(6));p=await detail(raceId);for(const r of p.responses)await act(raceId,r.id,t,'ACCEPT');p=await detail(raceId);const race=await Promise.all(p.responses.map(r=>t.raw('POST',`/matches/responses/${r.id}/confirm`,{version:r.version,publicationVersion:p.version})));assert.equal(race.filter(r=>r.status===201).length,1);assert.ok(race.every(r=>[201,409].includes(r.status)));assert.equal((await t.call('GET','/transport-demands/'+d.id)).matchedKg,6000);pass('并发确认仅成功一次，数量不超配');
 supply=await c.call('POST','/transport-supplies',{name:'Phase4反向匹配 '+stamp,modeId:mode.id,originCodes:base.originCodes,originAddress:base.originAddress,destinationCodes:base.destinationCodes,destinationAddress:base.destinationAddress,viaNodes:'',capacity:100,minQuantity:1,maxQuantity:100,resourceType:'VEHICLE',resourceDescription:'开发验收车辆',grainIds:[grain.id],serviceStart:day(1),serviceEnd:day(25),durationHours:96,referencePrice:350,priceUnit:'PER_TON',capabilities:'防潮',validFrom:day(-1),validUntil:day(6),contact:'验收物流',phone:'13800000002',notes:'仅开发验收'});await c.call('POST',`/transport-supplies/${supply.id}/publish`,{version:supply.version});d=await create('供给反向匹配',110);await t.call('POST','/matches/publications',{...pubdto(d),supplyId:supply.id,mode:'DIRECTED',targetCarrierId:'carrier-a'},400);const supplyMatch=await publish(d,{supplyId:supply.id,mode:'DIRECTED',targetCarrierId:'carrier-a',riskAcknowledged:true});assert.equal((await detail(supplyMatch)).riskNotes.length,1);assert.ok((await cb.call('GET','/matches/supplies?q='+(await c.call('GET','/transport-supplies/'+supply.id)).businessNo)).items.some(x=>x.id===supply.id));pass('有效供给大厅、反向定向匹配、数量不适配显式确认');
 d=await create('完整方案匹配');const plan=await db.planRun.create({data:{businessNo:'FA-P4-QA-'+stamp,groupId:'P4-QA-'+stamp,version:1,businessEntityId:'trader-a',demandId:d.id,demandVersion:d.version,input:'{}',warnings:'[]',status:'SELECTED',createdBy:t.id||'TEST',isTestData:true,candidates:{create:{name:'开发验收完整方案',rank:1,distanceMeters:100000,durationSeconds:3600,costCents:0,transferCount:0,arrivalAt:new Date(day(15)),modes:'["RAIL"]',warnings:'["开发验收夹具，非实际班列"]',recommendation:'',geometryComplete:false,segments:{create:{sequence:1,mode:'RAIL',origin:'{"name":"验收起点"}',destination:'{"name":"验收终点"}',distanceMeters:100000,durationSeconds:3600,costCents:0,priceSnapshot:'{"pricePending":true}',source:'开发验收',routeProfile:'MISSING'}}}}},include:{candidates:true}});await db.planRun.update({where:{id:plan.id},data:{selectedPlanId:plan.candidates[0].id}});
 await t.call('POST','/matches/publications',{...pubdto(d),planRunId:plan.id},400);const planPub=await publish(d,{planRunId:plan.id,allowPartial:false});p=await detail(planPub,c);assert.equal(p.objectType,'PLAN');assert.equal(p.snapshot.plan.segments.length,1);assert.ok(!('costCents' in p.snapshot.plan));await c.call('POST',`/matches/publications/${planPub}/quote`,{publicationVersion:p.version,terms:terms(5)},400);const pr=await offer(planPub,c,terms(10,375));await act(planPub,pr.id,t,'ACCEPT');p=await detail(planPub);const pc=await t.call('POST',`/matches/responses/${pr.id}/confirm`,{version:p.responses[0].version,publicationVersion:p.version});assert.equal(pc.totalCents,375000);pass('完整方案快照、禁止按区段/部分数量报价、成交价来自接受条款');
 const ui=await create('浏览器验收整单需求',8);fs.writeFileSync('docs/acceptance/phase4-fixture.json',JSON.stringify({demandId:ui.id,name:ui.name,supplyId:supply.id,createdAt:new Date().toISOString()},null,2));created.splice(created.indexOf(ui.id),1);
 pass('生成独立浏览器验收需求，保留现有业务记录');
}finally{
 if(t)for(const id of created){try{const pubs=await db.matchPublication.findMany({where:{demandId:id},include:{confirmations:true}});for(const p of pubs){for(const cf of p.confirmations.filter(c=>c.status==='CONFIRMED'))await t.call('POST',`/matches/confirmations/${cf.id}/cancel`,{version:cf.version,reason:'验收完成清理数量占用'});const current=await t.call('GET','/matches/publications/'+p.id);if(current.status==='ACTIVE')await t.call('POST',`/matches/publications/${p.id}/close`,{version:current.version,reason:'验收完成关闭发布'});}const d=await t.call('GET','/transport-demands/'+id);await t.call('POST',`/transport-demands/${id}/cancel`,{version:d.version});}catch(e){console.error('Fixture cleanup failed',e.message);}}
 if(c&&supply){try{const s=await c.call('GET','/transport-supplies/'+supply.id);if(s.status==='PUBLISHED')await c.call('POST',`/transport-supplies/${s.id}/pause`,{version:s.version});}catch{}}
 for(const s of sessions)await s.call('POST','/auth/logout');await db.$disconnect();fs.writeFileSync('docs/acceptance/phase4-api.json',JSON.stringify({at:new Date().toISOString(),results},null,2));
}})().catch(e=>{console.error(e);process.exitCode=1;});
