const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
require('dotenv').config();
const TARGET=process.env.TARGET_URL||'http://127.0.0.1:5173';
const results=[],errors=[];const check=name=>{results.push({name,result:'PASS'});console.log('PASS',name);};
const stamp=Date.now(),date=days=>new Date(Date.now()+days*86400000).toISOString(),uiDate=days=>{const d=new Date(Date.now()+days*86400000);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')+' 12:00:00';};
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:process.env.PW_HEADLESS==='true'});
 const contexts=[];
 async function login(username,ui=false){const context=await browser.newContext({viewport:{width:1440,height:1000}});contexts.push(context);let data;let page;
  if(ui){page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(TARGET+'/login');await page.getByRole('textbox',{name:'账号',exact:true}).fill(username);await page.getByRole('textbox',{name:'密码',exact:true}).fill(process.env.SEED_PASSWORD);const pending=page.waitForResponse(r=>r.url().endsWith('/auth/login'));await page.getByRole('button',{name:'登录',exact:true}).click();const response=await pending;assert.equal(response.status(),201);data=(await response.json()).data;await page.waitForURL(TARGET+'/');}
  else{const r=await context.request.post(TARGET+'/api/auth/login',{data:{username,password:process.env.SEED_PASSWORD}});assert.equal(r.status(),201);data=(await r.json()).data;}
  const call=async(method,path,body,status=method==='post'?201:200)=>{const r=await context.request[method](TARGET+'/api'+path,{headers:{Authorization:'Bearer '+data.accessToken},...(body?{data:body}:{})});const json=await r.json();assert.equal(r.status(),status,`${method} ${path}: ${JSON.stringify(json)}`);return json.data;};
  return {context,page,data,call};
 }
 let t,c,a,b,cb;
 try{
 t=await login('trader',true);c=await login('carrier',true);a=await login('admin');b=await login('trader.b');cb=await login('carrier.b');
 const opts=await t.call('get','/transport-options');const corn=opts.grains.find(g=>g.code==='1');const mode=opts.modes.find(m=>m.code==='1');
 const orders=await t.call('get','/trade-orders?pageSize=100');assert.ok(orders.items.every(i=>i.tradeOrder.businessEntityId==='trader-a'));const item=orders.items.find(i=>i.grain.code==='1');const baseline=item.reservedQuantity;
 const base={orderItemId:item.id,name:'验收订单需求 '+stamp,quantity:10,originCodes:['210000','211100','211102'],originAddress:'盘锦粮库一号仓',destinationCodes:['440000','440100','440112'],destinationAddress:'黄埔粮食仓库',departureAt:date(10),arrivalAt:date(15),modeIds:[mode.id],allowMultimodal:true,allowTransfer:true,maxTransfers:2,loadingType:'BULK',preference:'BALANCED',budget:8000,contact:'验收联系人',phone:'13800000001',notes:'Phase 2 业务验收'};
 await a.call('post','/transport-demands',base,403);await c.call('post','/transport-demands',base,403);await b.call('post','/transport-demands',base,404);await t.call('post','/transport-demands',{...base,businessEntityId:'trader-b'},400);check('创建需求强制贸易权限、订单归属与服务端主体范围');
 let d=await t.call('post','/transport-demands',base);assert.equal(d.quantity,10);assert.equal((await t.call('get','/trade-orders?pageSize=100')).items.find(i=>i.id===item.id).reservedQuantity,baseline+10);
 await b.call('get','/transport-demands/'+d.id,null,404);await b.call('put','/transport-demands/'+d.id,{...base,version:d.version},404);
 d=await t.call('put','/transport-demands/'+d.id,{...base,quantity:12.345,version:d.version});assert.equal(d.quantityKg,12345);await t.call('put','/transport-demands/'+d.id,{...base,version:1},409);await t.call('post','/transport-demands',{...base,quantity:item.remainingQuantity},400);check('草稿占用、差额编辑、三位精度、超量和过期版本拦截');
 const pub={version:d.version,mode:'DIRECTED',targetCarrierId:'carrier-a',deadline:date(5),quoteType:'PER_TON',budgetPublic:false,contactPublic:false,notes:'指定物流商响应'};
 await t.call('post','/transport-demands/'+d.id+'/publish',pub);await t.call('post','/transport-demands/'+d.id+'/publish',pub,409);d=await t.call('get','/transport-demands/'+d.id);assert.equal(d.publications.filter(p=>p.status==='ACTIVE').length,1);assert.equal(d.publications[0].targetCarrierId,'carrier-a');await t.call('put','/transport-demands/'+d.id,{...base,version:d.version},409);
 await t.call('post','/transport-demands/'+d.id+'/withdraw',{version:d.version});d=await t.call('get','/transport-demands/'+d.id);assert.equal(d.publications[0].status,'CLOSED');assert.equal((await t.call('get','/trade-orders?pageSize=100')).items.find(i=>i.id===item.id).reservedQuantity,baseline+12.345);
 await t.call('post','/transport-demands/'+d.id+'/cancel',{version:d.version});await t.call('post','/transport-demands/'+d.id+'/cancel',{version:d.version},409);assert.equal((await t.call('get','/trade-orders?pageSize=100')).items.find(i=>i.id===item.id).reservedQuantity,baseline);check('定向发布记录、重复发布、撤回保留占用、取消只释放一次');
 // A separate 1-ton imported order makes the competing-reservation assertion deterministic.
 const orderDto={businessNo:'JY-QA-'+stamp,businessEntityId:'trader-a',recipient:'验收收货方',shipperContact:'验收发货人',shipperPhone:'13800000001',recipientContact:'验收收货人',recipientPhone:'13800000002',sourceSystem:'phase2-acceptance',sourceRecordId:String(stamp),items:[{lineNo:'1',grainId:corn.id,cargoName:'验收玉米',specification:'国标二等',quantity:1}]};
 const imported=await a.call('post','/trade-orders/import',orderDto);assert.equal((await a.call('post','/trade-orders/import',orderDto)).id,imported.id);await a.call('post','/trade-orders/import',{...orderDto,recipient:'内容改变'},409);await t.call('post','/trade-orders/import',orderDto,403);
 const line=(await t.call('get','/trade-orders?q=JY-QA-'+stamp)).items[0];
 const race=await Promise.all([1,2].map(n=>t.context.request.post(TARGET+'/api/transport-demands',{headers:{Authorization:'Bearer '+t.data.accessToken},data:{...base,orderItemId:line.id,name:'验收并发 '+n,quantity:.75}})));
 assert.equal(race.filter(r=>r.status()===201).length,1);assert.ok(race.every(r=>[201,400,409].includes(r.status())));const winner=(await race.find(r=>r.status()===201).json()).data;assert.equal((await t.call('get','/trade-orders?q=JY-QA-'+stamp)).items[0].reservedQuantity,.75);await t.call('post','/transport-demands/'+winner.id+'/delete',{version:winner.version});assert.equal((await t.call('get','/trade-orders?q=JY-QA-'+stamp)).items[0].reservedQuantity,0);check('来源导入幂等、冲突保护、并发超量只成功一笔与删除释放');
 const supplyBase={name:'验收公路供给 '+stamp,modeId:mode.id,originCodes:base.originCodes,originAddress:base.originAddress,destinationCodes:base.destinationCodes,destinationAddress:base.destinationAddress,viaNodes:'沈阳集运站',capacity:100,minQuantity:10,maxQuantity:100,resourceType:'VEHICLE',resourceDescription:'高栏车3辆，防雨篷布',grainIds:[corn.id],serviceStart:date(1),serviceEnd:date(20),durationHours:72,referencePrice:350,priceUnit:'PER_TON',capabilities:'装卸、防潮',validFrom:date(-1),validUntil:date(10),contact:'物流验收联系人',phone:'13800000003',notes:'真实接口开发验收'};
 await t.call('post','/transport-supplies',supplyBase,403);let s=await c.call('post','/transport-supplies',supplyBase);await cb.call('get','/transport-supplies/'+s.id,null,404);await t.call('get','/transport-supplies/'+s.id,null,404);
 const upload=async(name,mime,buffer,kind='DOCUMENT',status=201)=>{const r=await c.context.request.post(TARGET+'/api/transport-files/supply/'+s.id,{headers:{Authorization:'Bearer '+c.data.accessToken},multipart:{kind,file:{name,mimeType:mime,buffer}}});assert.equal(r.status(),status,await r.text());return (await r.json()).data;};
 await upload('bad.html','image/png',Buffer.from('<html>bad</html>'),'PHOTO',400);const file=await upload('sample.pdf','application/pdf',Buffer.from('%PDF-1.4\n% acceptance attachment\n%%EOF'));
 const image=await upload('corn.png','image/png',fs.readFileSync('apps/web/public/assets/grain/corn.png'),'PHOTO');s=await c.call('get','/transport-supplies/'+s.id);assert.ok(!JSON.stringify(s.files).includes('storageName'));
 await c.call('post','/transport-supplies/'+s.id+'/publish',{version:s.version});s=await c.call('get','/transport-supplies/'+s.id);const publicSupply=await t.call('get','/transport-supplies/'+s.id);assert.equal(publicSupply.phone,'138****0003');assert.equal(publicSupply.files.length,1);
 assert.equal((await t.context.request.get(TARGET+'/api/transport-files/'+file.id,{headers:{Authorization:'Bearer '+t.data.accessToken}})).status(),403);assert.equal((await t.context.request.get(TARGET+'/api/transport-files/'+image.id,{headers:{Authorization:'Bearer '+t.data.accessToken}})).status(),200);
 assert.equal((await t.call('get','/transport-supplies?q=nonexistent&grainId='+corn.id)).total,0);check('供给企业隔离、有效发布可见、组合筛选、附件鉴权与类型检查');
 await c.call('post','/transport-supplies/'+s.id+'/pause',{version:s.version});await t.call('get','/transport-supplies/'+s.id,null,404);s=await c.call('get','/transport-supplies/'+s.id);await c.call('delete','/transport-files/'+file.id);s=await c.call('get','/transport-supplies/'+s.id);s=await c.call('put','/transport-supplies/'+s.id,{...supplyBase,version:s.version,validUntil:new Date(Date.now()+2500).toISOString()});await c.call('post','/transport-supplies/'+s.id+'/publish',{version:s.version});await new Promise(r=>setTimeout(r,2800));s=await c.call('get','/transport-supplies/'+s.id);assert.equal(s.status,'EXPIRED');assert.ok((await c.call('get','/transport-supplies/'+s.id+'/history')).some(h=>h.action==='供给到期失效'));check('暂停撤出公开列表、移除附件、后端到期失效与审计');
 // UI: use actual Element Plus inputs and server-backed order selection.
 const p=t.page;await p.goto(TARGET+'/supply-demand/demands');
 await p.getByRole('button',{name:'新建运输需求',exact:true}).click();const editor=p.getByRole('dialog',{name:'新建运输需求',exact:true});await editor.getByRole('button',{name:'保存草稿',exact:true}).click();await editor.getByText('请填写交易订单明细',{exact:true}).waitFor();await editor.getByRole('button',{name:'选择交易订单明细'}).click();
 const picker=p.getByRole('dialog',{name:'选择交易订单明细',exact:true});await picker.getByRole('textbox',{name:'订单搜索'}).fill('JY-DEV-A-001');await picker.getByRole('button',{name:'查询订单'}).click();await picker.getByRole('row').filter({hasText:'JY-DEV-A-001'}).getByRole('button',{name:'选择',exact:true}).click();
 const field=(root,label)=>root.locator('.el-form-item').filter({has:p.locator('.el-form-item__label').filter({hasText:new RegExp('^'+label+'$')})});
 const fill=async(root,label,value)=>{const input=field(root,label).locator('input').first();await input.fill(value);await input.press('Tab');};
 const region=async(root,label,names)=>{await field(root,label).locator('input').click();for(const n of names)await p.getByRole('menuitem',{name:n,exact:true}).last().click();};
 await fill(editor,'运输需求名称','盘锦玉米南运 · 浏览器验收 '+stamp);await fill(editor,'运输数量（吨）','35.125');await region(editor,'起运地区',['辽宁省','盘锦市','双台子区']);await region(editor,'目的地区',['广东省','广州市','黄埔区']);await fill(editor,'起运详细地址',base.originAddress);await fill(editor,'目的详细地址',base.destinationAddress);await fill(editor,'计划发运时间',uiDate(10));
 await p.screenshot({path:'docs/acceptance/phase2-demand-form.png',fullPage:false,animations:'disabled'});const created=p.waitForResponse(r=>r.url().endsWith('/transport-demands')&&r.request().method()==='POST');await editor.getByRole('button',{name:'保存草稿'}).click();const createdResponse=await created;assert.equal(createdResponse.status(),201,await createdResponse.text());const uiDemand=(await createdResponse.json()).data;await p.getByRole('heading',{name:uiDemand.name,exact:true}).waitFor();await p.reload();await p.getByRole('heading',{name:uiDemand.name,exact:true}).waitFor();
 await p.screenshot({path:'docs/acceptance/phase2-demand-detail.png',fullPage:false,animations:'disabled'});const detailDrawer=p.getByRole('dialog',{name:'运输需求详情',exact:true});await detailDrawer.getByRole('button',{name:'发布',exact:true}).click();const pubDialog=p.getByRole('dialog',{name:'发布运输需求',exact:true});await fill(pubDialog,'响应截止时间',uiDate(5));await pubDialog.getByRole('button',{name:'确认发布'}).click();await p.getByText('需求已发布',{exact:true}).waitFor();check('浏览器订单选择、字段校验、需求创建、详情深链刷新与发布');
 await detailDrawer.locator('.el-drawer__close-btn').click();await p.getByRole('textbox',{name:'搜索关键词'}).fill('浏览器验收 '+stamp);await p.getByRole('button',{name:'搜索',exact:true}).click();await p.getByRole('button',{name:uiDemand.name,exact:true}).waitFor();for(const width of [1440,1280]){await p.setViewportSize({width,height:960});await p.screenshot({path:`docs/acceptance/phase2-demand-${width}.png`,fullPage:true,animations:'disabled'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
 await p.route('**/api/transport-demands?**',r=>r.abort());await p.getByRole('button',{name:'刷新列表'}).click();await p.getByText('网络连接失败，请检查服务后重试',{exact:true}).waitFor();await p.unroute('**/api/transport-demands?**');await p.getByRole('button',{name:'重新加载'}).click();await p.getByRole('button',{name:uiDemand.name,exact:true}).waitFor();check('浏览器筛选、1280/1440布局与请求失败重试');
 const cp=c.page;await cp.goto(TARGET+'/supply-demand/supplies');await cp.getByRole('button',{name:'新建运输供给'}).click();const se=cp.getByRole('dialog',{name:'新建运输供给'});
 // Same field helper, scoped to carrier page.
 const sf=label=>se.locator('.el-form-item').filter({has:cp.locator('.el-form-item__label').filter({hasText:new RegExp('^'+label+'$')})});
 const sfill=async(label,value)=>{const input=sf(label).locator('input').first();await input.fill(value);await input.press('Tab');};
 await sfill('运输供给名称','东北至华南公路运力 · 浏览器验收 '+stamp);await sf('运输方式').locator('.el-select').click();await cp.getByRole('option',{name:'公路',exact:true}).click();await sfill('可承运数量（吨）','200');for(const [l,ns] of [['起运地区',['辽宁省','盘锦市','双台子区']],['目的地区',['广东省','广州市','黄埔区']]]){await sf(l).locator('input').click();for(const n of ns)await cp.getByRole('menuitem',{name:n,exact:true}).last().click();}await sfill('起运详细地址',base.originAddress);await sfill('目的详细地址',base.destinationAddress);await sf('资源说明').locator('textarea').fill('防雨高栏车6辆，支持粮食散装运输');for(const [l,day] of [['服务开始时间',1],['服务结束时间',20],['供给生效时间',-1],['供给失效时间',10]])await sfill(l,uiDate(day));await sfill('联系人','浏览器物流联系人');await sfill('联系电话','13800000003');const sc=cp.waitForResponse(r=>r.url().endsWith('/transport-supplies')&&r.request().method()==='POST');await se.getByRole('button',{name:'保存草稿'}).click();const sr=await sc;assert.equal(sr.status(),201,await sr.text());const uiSupply=(await sr.json()).data;await cp.getByRole('heading',{name:uiSupply.name,exact:true}).waitFor();await cp.getByRole('dialog',{name:'运输供给详情',exact:true}).getByRole('button',{name:'发布',exact:true}).click();await cp.getByRole('button',{name:'确认发布',exact:true}).click();await cp.getByText('操作成功',{exact:true}).waitFor();await cp.reload();await cp.getByRole('heading',{name:uiSupply.name,exact:true}).waitFor();await cp.screenshot({path:'docs/acceptance/phase2-supply-detail.png',fullPage:false,animations:'disabled'});check('浏览器供给表单、创建发布和刷新持久化');
 const allMenus=await a.call('get','/menus');assert.ok(allMenus.find(m=>m.id==='demand').children.every(m=>m.available));assert.ok(allMenus.find(m=>m.id==='contract').children.every(m=>!m.available));await t.call('get','/users',null,403);assert.ok((await a.call('get','/users')).total>0);check('Phase1权限回归，Phase2入口开放，后续阶段入口仍受控');
 const finalDemand=await t.call('get','/transport-demands/'+uiDemand.id),finalSupply=await c.call('get','/transport-supplies/'+uiSupply.id),finalOrder=(await t.call('get','/trade-orders?pageSize=100')).items.find(i=>i.id===uiDemand.orderItemId);fs.writeFileSync('docs/acceptance/phase2-persistence-before.json',JSON.stringify({demand:{id:finalDemand.id,status:finalDemand.status,version:finalDemand.version,publicationIds:finalDemand.publications.map(p=>p.id)},supply:{id:finalSupply.id,status:finalSupply.status,version:finalSupply.version},order:{id:finalOrder.id,reservedKg:finalOrder.reservedKg}},null,2));assert.deepEqual(errors,[]);
 }catch(error){if(t?.page)await t.page.screenshot({path:'docs/acceptance/phase2-failure-trader.png',fullPage:true,animations:'disabled'}).catch(()=>{});if(c?.page)await c.page.screenshot({path:'docs/acceptance/phase2-failure-carrier.png',fullPage:true,animations:'disabled'}).catch(()=>{});throw error;}finally{fs.writeFileSync('docs/acceptance/phase2-results.json',JSON.stringify({at:new Date().toISOString(),results,errors},null,2));await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
