const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');require('dotenv').config();
const TARGET=process.env.TARGET_URL||'http://127.0.0.1:5173',results=[],errors=[],stamp=Date.now();const check=name=>{results.push({name,result:'PASS'});console.log('PASS',name);},days=n=>new Date(Date.now()+n*86400000).toISOString();
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:process.env.PW_HEADLESS==='true'});let t,a,b,c,cleanup=[];
 async function login(name,ui=false){const context=await browser.newContext({viewport:{width:1440,height:1050}});let page,data;if(ui){page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(TARGET+'/login');await page.getByRole('textbox',{name:'账号',exact:true}).fill(name);await page.getByRole('textbox',{name:'密码',exact:true}).fill(process.env.SEED_PASSWORD);const wait=page.waitForResponse(r=>r.url().endsWith('/auth/login'));await page.getByRole('button',{name:'登录',exact:true}).click();const r=await wait;assert.equal(r.status(),201);data=(await r.json()).data;await page.waitForURL(TARGET+'/');}else{const r=await context.request.post(TARGET+'/api/auth/login',{data:{username:name,password:process.env.SEED_PASSWORD}});assert.equal(r.status(),201);data=(await r.json()).data;}
 const call=async(method,path,body,status=method==='post'?201:200)=>{const r=await context.request[method](TARGET+'/api'+path,{headers:{Authorization:'Bearer '+data.accessToken},...(body?{data:body}:{}),timeout:120000});const json=await r.json();assert.equal(r.status(),status,`${method} ${path}: ${JSON.stringify(json).slice(0,600)}`);return json.data;};return {context,page,call};}
 try{
 t=await login('trader',true);a=await login('admin',true);b=await login('trader.b');c=await login('carrier');const opts=await t.call('get','/plans/options'),origin=opts.nodes.find(n=>n.name==='盘锦站'),destination=opts.nodes.find(n=>n.name==='广州北站'),grain=opts.grains.find(g=>g.code==='1');assert.ok(opts.nodes.length>=6);assert.ok(opts.nodes.every(n=>n.source==='AMAP_POI'&&n.coordinateSystem==='GCJ02'&&!n.name.includes('酒店')));
 const point=n=>({name:n.name,nodeId:n.id,lng:n.lng,lat:n.lat});const dto={grainId:grain.id,cargoName:'验收玉米',quantity:50,origin:point(origin),destination:point(destination),departureAt:days(5),modes:['ROAD','RAIL','WATER'],allowMultimodal:true,allowTransfer:true,maxTransfers:2,loadingType:'BULK',preference:'BALANCED'};
 await t.call('post','/plans/solve',{...dto,origin:undefined},400);let first=await t.call('post','/plans/solve',dto);assert.ok(first.candidates.length>=2);for(const candidate of first.candidates){assert.equal(candidate.distanceMeters,candidate.segments.reduce((s,r)=>s+r.distanceMeters,0));assert.equal(candidate.durationSeconds,candidate.segments.reduce((s,r)=>s+r.durationSeconds+r.waitSeconds,0));assert.equal(candidate.costCents,candidate.segments.reduce((s,r)=>s+r.costCents,0));for(const s of candidate.segments){assert.equal(s.geometry.routeProfile,'AMAP_DRIVING_GENERAL');assert.ok(s.geometry.coordinates.length>100);assert.equal(s.costCents,Math.round(dto.quantity*s.distanceMeters/1000*s.priceSnapshot.rate*100));}}check('真实高德节点与多条道路候选，费用/里程/时长逐段一致');
 let second=await t.call('post','/plans/solve',{...dto,previousRunId:first.id});assert.equal(second.version,2);assert.deepEqual(second.candidates.map(x=>x.segments[0].geometryId),first.candidates.map(x=>x.segments[0].geometryId));assert.deepEqual(second.candidates.map(x=>x.segments[0].geometry.queriedAt),first.candidates.map(x=>x.segments[0].geometry.queriedAt));await t.call('post','/plans/runs/'+first.id+'/select',{candidateId:first.candidates[0].id,revision:first.revision},409);await b.call('get','/plans/runs/'+second.id,null,404);await b.call('post','/plans/solve',{...dto,previousRunId:second.id},404);await a.call('post','/plans/solve',{...dto,previousRunId:second.id},403);await c.call('post','/plans/runs/'+second.id+'/select',{candidateId:second.candidates[0].id,revision:second.revision},403);await t.call('post','/plans/runs/'+second.id+'/select',{candidateId:second.candidates[0].id,revision:second.revision});await t.call('post','/plans/runs/'+second.id+'/select',{candidateId:second.candidates[1].id,revision:second.revision},409);check('路径复用数据库缓存，重算生成新版本，完整选择与企业隔离');
 const price=(await a.call('get','/route-prices')).items.find(p=>p.id==='sample-road-rate-v1');const priceDto={unit:price.unit,rate:price.rate,validFrom:price.validFrom,validUntil:price.validUntil,source:price.source,maintainer:price.maintainer,enabled:price.enabled,version:price.version};await t.call('put','/route-prices/'+price.id,priceDto,403);await c.call('post','/route-prices',priceDto,403);await a.call('post','/route-prices',{...priceDto,version:undefined},409);await a.call('put','/route-prices/'+price.id,{...priceDto,version:price.version+100},409);check('公共价格仅平台维护，重叠有效期及过期版本被拒绝');
 const lines=await a.call('get','/transport-lines?pageSize=100');const node2=opts.nodes.find(n=>n.name==='沈阳东站');const lineDto={name:'验收盘锦至沈阳公路 '+stamp,mode:'ROAD',originId:origin.id,destinationId:node2.id,distanceKm:1,durationHours:1,grainIds:[],loadingTypes:['BULK','CONTAINER'],transferMinutes:30,source:'高德官方道路服务',sourceRef:'routing-query',sourceUrl:'https://lbs.amap.com/api/webservice/guide/api/newroute',maintainer:'开发验收平台',quality:'VERIFIED',enabled:true};const line=await a.call('post','/transport-lines',lineDto);cleanup.push({id:line.id,dto:lineDto});const actual=await a.call('get','/transport-lines/'+line.id);assert.ok(actual.distanceKm>100);assert.ok(actual.geometry.id);await a.call('post','/route-prices',{lineId:line.id,unit:'PER_TON',rate:88.5,validFrom:days(-1),validUntil:days(30),source:'开发验收价格，非市场报价',maintainer:'开发验收平台',enabled:true});check('平台线路创建回填真实道路距离与几何，独立线路价格入库');
 const railDto={...lineDto,name:'验收隔离铁路规则 '+stamp,mode:'RAIL',distanceKm:200,durationHours:10,source:'自动化规则验收参数（非业务实测）',sourceRef:'phase3-test-only',quality:'VERIFIED'};const rail=await a.call('post','/transport-lines',railDto);cleanup.push({id:rail.id,dto:railDto});await a.call('post','/route-prices',{lineId:rail.id,unit:'PER_TON',rate:50,validFrom:days(-1),validUntil:days(30),source:'自动化验收样例，非报价',maintainer:'开发验收平台',enabled:true});const missing=await t.call('post','/plans/solve',{...dto,destination:point(node2),modes:['RAIL'],requiredLineId:rail.id,allowTransfer:false,maxTransfers:0});assert.equal(missing.candidates.length,1);assert.equal(missing.candidates[0].geometryComplete,false);assert.equal(missing.candidates[0].segments[0].geometry,null);assert.ok(missing.candidates[0].warnings.some(w=>w.includes('缺少已核验路径')));await a.call('post','/transport-lines/'+rail.id+'/geometry',{version:rail.version,routeProfile:'PLANNED_WATER',source:'测试',sourceRef:'https://example.com/test',coordinates:[[origin.lng,origin.lat],[node2.lng,node2.lat],[destination.lng,destination.lat]]},400);check('缺失铁路几何仅保留节点和来源数据，拒绝错用水运路径');
 const noResult=await t.call('post','/plans/solve',{...dto,arrivalAt:new Date(new Date(dto.departureAt).getTime()+60000).toISOString()});assert.equal(noResult.status,'NO_RESULT');assert.equal(noResult.candidates.length,0);check('时效约束不可满足时保留无结果记录和原因');
 // Browser: menu is an empty form; select real POIs from the point picker.
 const p=t.page;await p.goto(TARGET+'/plans/solve');await p.getByRole('button',{name:'开始求解',exact:true}).waitFor();assert.equal(await p.getByRole('spinbutton',{name:'运输数量',exact:true}).inputValue(),'');await p.getByRole('button',{name:'开始求解',exact:true}).click();await p.getByText('请填写：粮食品种、运输数量、起运位置、目的位置、计划发运时间',{exact:true}).waitFor();
 const form=p.locator('.plan-form');await form.getByRole('combobox',{name:'粮食品种',exact:true}).focus();await form.getByRole('combobox',{name:'粮食品种',exact:true}).press('ArrowDown');await p.getByRole('option',{name:'玉米',exact:true}).click();await form.getByRole('spinbutton',{name:'运输数量',exact:true}).fill('50');await form.getByRole('spinbutton',{name:'运输数量',exact:true}).press('Tab');
 for(const [label,node] of [['起运位置',origin],['目的位置',destination]]){await p.getByRole('button',{name:'选择'+label,exact:true}).click();const picker=p.getByRole('dialog',{name:'选择'+label,exact:true});await picker.locator('.point-results button').filter({hasText:node.name}).click();await picker.getByRole('button',{name:'确认位置',exact:true}).click();}
 const d=new Date(Date.now()+5*86400000);const value=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')+' 12:00:00';await form.getByRole('combobox',{name:'计划发运时间',exact:true}).fill(value);await p.locator('.el-picker-panel:visible').getByRole('button',{name:'确定',exact:true}).click();await p.locator('.el-picker-panel:visible').waitFor({state:'hidden'});assert.deepEqual(await form.locator('input').evaluateAll(inputs=>inputs.filter(x=>!x.validity.valid).map(x=>({label:x.getAttribute('aria-label'),value:x.value,step:x.step,min:x.min,reason:x.validationMessage}))),[]);console.log('CHECK 表单输入通过原生校验');const solved=p.waitForResponse(r=>r.url().endsWith('/plans/solve')&&r.request().method()==='POST',{timeout:30000});await p.getByRole('button',{name:'开始求解',exact:true}).click();const response=await solved;assert.equal(response.status(),201,await response.text());const uiRun=(await response.json()).data;await p.locator('.candidate-card').first().waitFor();await p.waitForFunction(()=>!!document.querySelector('.map-canvas canvas'),null,{timeout:30000});await p.locator('.map-state').waitFor({state:'hidden',timeout:30000});await p.evaluate(()=>window.scrollTo(0,0));await p.screenshot({path:'docs/acceptance/phase3-solve-1440.png',fullPage:true,animations:'disabled'});await p.locator('.candidate-card').nth(1).click();await p.getByRole('button',{name:'选择完整方案',exact:true}).click();await p.getByRole('button',{name:'确认选择',exact:true}).click();await p.getByText('已选定完整方案',{exact:true}).waitFor();await p.reload();await p.getByRole('button',{name:'已选完整方案',exact:true}).waitFor();check('浏览器空白求解入口、真实节点选择、候选比选、完整选择与刷新持久化');
 await p.setViewportSize({width:1280,height:960});await p.evaluate(()=>window.scrollTo(0,0));await p.screenshot({path:'docs/acceptance/phase3-solve-1280.png',fullPage:true,animations:'disabled'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('.segment-link').first().click();await p.getByRole('button',{name:'适配全程',exact:true}).click();check('1280/1440布局、区段与地图联动和全程视角');
 const demands=await t.call('get','/transport-demands?status=DRAFT&pageSize=100');let demand=demands.items[0];if(!demand){const item=(await t.call('get','/trade-orders?q=JY-DEV-A-001')).items[0];demand=await t.call('post','/transport-demands',{orderItemId:item.id,name:'Phase3需求带入验收 '+stamp,quantity:5,originCodes:['210000','211100','211102'],originAddress:'盘锦站',destinationCodes:['440000','440100','440114'],destinationAddress:'广州北站',departureAt:days(6),modeIds:[],allowMultimodal:true,allowTransfer:true,maxTransfers:2,loadingType:'BULK',preference:'BALANCED',contact:'开发验收',phone:'13800000001'});}
 await p.goto(TARGET+'/supply-demand/demands?id='+demand.id);await p.getByRole('button',{name:'方案求解',exact:true}).click();await p.waitForURL('**/plans/solve?demandId='+demand.id);await p.getByRole('link',{name:demand.businessNo,exact:true}).waitFor();assert.equal(Number(await p.getByRole('spinbutton',{name:'运输数量',exact:true}).inputValue()),demand.quantity);assert.equal(await p.getByRole('spinbutton',{name:'运输数量',exact:true}).isDisabled(),true);await b.call('get','/plans/demand/'+demand.id+'/input',null,404);await t.call('post','/plans/solve',{...dto,demandId:demand.id,demandVersion:demand.version,quantity:demand.quantity+1,departureAt:demand.departureAt},400);check('需求入口自动带入并锁定来源字段，后端拒绝篡改和跨企业需求');
 const ap=a.page;await ap.goto(TARGET+'/plans/prices');await ap.getByRole('button',{name:'新增线路',exact:true}).waitFor();await ap.getByRole('textbox',{name:'线路搜索',exact:true}).fill(String(stamp));await ap.getByRole('button',{name:'搜索',exact:true}).click();await ap.getByRole('button',{name:lineDto.name,exact:true}).waitFor();await ap.getByRole('button',{name:lineDto.name,exact:true}).click();await ap.getByText('88.5',{exact:true}).waitFor();const priceDrawer=ap.getByRole('dialog',{name:lineDto.name+' · 线路与价格',exact:true});await priceDrawer.getByRole('button',{name:'编辑',exact:true}).click();const priceEditor=ap.getByRole('dialog',{name:'编辑参考价格',exact:true});await priceEditor.getByRole('spinbutton',{name:'参考单价',exact:true}).fill('89.125');await priceEditor.getByRole('spinbutton',{name:'参考单价',exact:true}).press('Tab');await priceEditor.getByRole('button',{name:'保存',exact:true}).click();await priceDrawer.getByText('89.125',{exact:true}).waitFor();await ap.screenshot({path:'docs/acceptance/phase3-prices.png',fullPage:false,animations:'disabled'});await p.goto(TARGET+'/plans/prices');await p.getByRole('heading',{name:'线路价格',exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'新增线路',exact:true}).count(),0);check('平台线路与价格页面、企业只读视图');
 const stored=await t.call('get','/plans/runs/'+uiRun.id);fs.writeFileSync('docs/acceptance/phase3-persistence-before.json',JSON.stringify({id:stored.id,selectedPlanId:stored.selectedPlanId,revision:stored.revision,version:stored.version,geometryIds:stored.candidates.flatMap(c=>c.segments.map(s=>s.geometryId)),totals:stored.candidates.map(c=>[c.distanceMeters,c.durationSeconds,c.costCents])},null,2));assert.deepEqual(errors,[]);check('无浏览器运行时异常');
 }catch(e){if(a?.page)await a.page.screenshot({path:'docs/acceptance/phase3-prices-failure.png',fullPage:true}).catch(()=>{});if(t?.page)await t.page.screenshot({path:'docs/acceptance/phase3-failure.png',fullPage:true,animations:'disabled'}).catch(()=>{});throw e;}
 finally{for(const row of cleanup)try{const latest=await a.call('get','/transport-lines/'+row.id);await a.call('put','/transport-lines/'+row.id,{...row.dto,version:latest.version,enabled:false,quality:'DRAFT'});}catch{}fs.writeFileSync('docs/acceptance/phase3-results.json',JSON.stringify({at:new Date().toISOString(),results,errors},null,2));await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});









