const assert=require('node:assert/strict');
const {budgetBounds,filterByTotalBudget}=require('../apps/api/dist/planning-budget');
const {PlanningService}=require('../apps/api/dist/planning.service');
const route=(id,costCents,costComplete=true)=>({id,costCents,costComplete});
const rows=[route('low',100001),route('edge',200050),route('high',600000),route('unknown',null,false),route('partial',100,true)];
assert.deepEqual(budgetBounds({minBudget:1000.01,maxBudget:2000.50}),{min:100001,max:200050});
assert.deepEqual(filterByTotalBudget(rows,{minBudget:1000.01,maxBudget:2000.50}).candidates.map(r=>r.id),['low','edge']);
assert.deepEqual(filterByTotalBudget(rows,{maxBudget:2000.50}).candidates.map(r=>r.id),['low','edge','partial']);
assert.deepEqual(filterByTotalBudget(rows,{minBudget:2000.50}).candidates.map(r=>r.id),['edge','high']);
assert.equal(filterByTotalBudget(rows,{}).candidates,rows);
assert.equal(filterByTotalBudget(rows,{minBudget:null,maxBudget:null}).constrained,false);
assert.equal(filterByTotalBudget([route('free',0)],{maxBudget:0}).candidates.length,1);
const result=filterByTotalBudget(rows,{minBudget:1000.01,maxBudget:2000.50});
assert.equal(result.excluded,2);assert.equal(result.unknown,1);
assert.equal(filterByTotalBudget([route('subtotal',10000,false)],{maxBudget:200}).candidates.length,0);
for(const budget of [{minBudget:5,maxBudget:4},{minBudget:-1},{maxBudget:Infinity},{maxBudget:NaN},{maxBudget:20000001},{maxBudget:1.111}])assert.throws(()=>budgetBounds(budget),RangeError);
// Even callers that bypass the HTTP DTO are rejected before network/database work.
(async()=>{
 const service=new PlanningService({}, {}, {}, {});
 await assert.rejects(()=>service.solve({minBudget:500,maxBudget:400},{user:{id:'budget-validation-test'}}),e=>e.getStatus()===400&&e.message.includes('下限'));
 let saved;
 const price={lineId:null,grainId:null,unit:'PER_TON_KM',rateMillis:100};
 const tx={planRun:{findFirst:async()=>null,create:async({data})=>{saved=data;return {id:'isolated-budget-run',version:1}}}};
 const db={dictionary:{count:async()=>1},routePrice:{findMany:async()=>[price]},transportLine:{findMany:async()=>[]},$transaction:async cb=>cb(tx)};
 const amap={routes:async()=>[1000,2000,4000].map((distanceMeters,i)=>({id:'road-'+i,distanceMeters,durationSeconds:3600,source:'AMAP_V5_DRIVING',routeProfile:'DRIVING'}))};
 const solver=new PlanningService(db,{write:async()=>{}},amap,{});
 solver.run=async()=>saved;
 const dto={grainId:'corn',quantity:1000,origin:{name:'起点',lng:120,lat:40},destination:{name:'终点',lng:121,lat:40},departureAt:new Date(Date.now()+86400000).toISOString(),modes:['ROAD'],allowMultimodal:false,allowTransfer:false,maxTransfers:0,loadingType:'BULK',preference:'BALANCED',allowModel:false,minBudget:100,maxBudget:200};
 await solver.solve(dto,{user:{id:'isolated-user',businessEntityId:'isolated-entity'}});
 assert.equal(saved.candidates.create.length,2);
 assert.deepEqual(saved.candidates.create.map(c=>c.costCents),[10000,20000]);
 assert.equal(JSON.parse(saved.input).minBudget,100);assert.equal(JSON.parse(saved.input).maxBudget,200);
 assert.match(JSON.parse(saved.warnings).join(' '),/排除1条/);
 await solver.solve({...dto,minBudget:undefined,maxBudget:50},{user:{id:'isolated-user',businessEntityId:'isolated-entity'}});
 assert.equal(saved.status,'NO_RESULT');assert.equal(saved.candidates.create.length,0);
 assert.match(JSON.parse(saved.warnings).join(' '),/总预算/);
 console.log('PASS 总预算元/分换算、含边界区间、单边限制、不限、零上限、未知费用排除、输入校验及服务提前拒绝');
 console.log('PASS 求解服务在推荐及保存前筛选整单总价、保留预算输入、无结果提示（隔离内存数据）');
})().catch(e=>{console.error(e);process.exitCode=1});
