<script setup lang="ts">
import {numberA11y as vNumberA11y} from '../number-a11y';
import {ref,watch} from 'vue';import {ElMessage} from 'element-plus';import {api,get,message} from '../api';import {date,download} from '../fulfillment';
const props=defineProps<{taskId:string}>();const emit=defineEmits(['busy']);const documents=ref<any[]>([]),review=ref<any>(),fields=ref<any>({}),ack=ref(false),busy=ref(false),error=ref('');watch(busy,v=>emit('busy',v),{flush:'sync'});
async function load(){error.value='';try{documents.value=await get('/documents/task/'+props.taskId);}catch(e){error.value=message(e);}}
function setReview(d:any){review.value=d;fields.value={...d.recognized.fields,...(d.confirmed||{})};ack.value=false;}
async function recognize(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;if(file.size>8*1024*1024){error.value='单据不得超过8MB';input.value='';return;}busy.value=true;error.value='';try{const form=new FormData();form.append('file',file);setReview((await api.post('/documents/recognize/'+props.taskId,form,{timeout:110000})).data.data);await load();ElMessage.success('识别完成，请核对原件和字段');}catch(e){error.value=message(e);}finally{busy.value=false;input.value='';}}
async function inspect(id:string){error.value='';try{setReview(await get('/documents/'+id));}catch(e){error.value=message(e);}}
async function original(){try{const r=await api.get('/documents/'+review.value.id+'/file',{responseType:'blob'});download(r.data,review.value.name,review.value.mime);}catch(e){error.value=message(e);}}
async function confirm(){busy.value=true;error.value='';try{const data={...fields.value};if(data.quantityTons==null||data.quantityTons==='')delete data.quantityTons;await api.post('/documents/'+review.value.id+'/confirm',{version:review.value.version,acknowledged:ack.value,fields:data});setReview(await get('/documents/'+review.value.id));await load();ElMessage.success('人工复核结果已保存');}catch(e){error.value=message(e);}finally{busy.value=false;}}
watch(()=>props.taskId,()=>{review.value=undefined;documents.value=[];load();},{immediate:true});
</script>
<template><section class="document-workspace"><header><h3>任务单据</h3><label class="upload-button">{{busy?'处理中…':'上传并识别单据'}}<input type="file" aria-label="选择待识别单据" accept=".png,.jpg,.jpeg,.pdf,.xlsx" :disabled="busy" @change="recognize"/></label></header><p>PNG / JPEG / PDF / XLSX · 最大8MB</p><el-alert v-if="error" :title="error" type="error" :closable="false"/><div class="document-list"><el-button v-for="d in documents" :key="d.id" link type="primary" :disabled="busy" @click="inspect(d.id)">{{d.name}} · {{d.status==='CONFIRMED'?'已复核':'待复核'}}</el-button></div><div v-if="review"><div class="document-title"><strong>{{review.name}}</strong><el-button link type="primary" @click="original">下载原件</el-button></div><el-alert v-if="review.recognized.warnings.length" :title="review.recognized.warnings.join('；')" type="warning" :closable="false"/><el-form label-position="top" class="review-grid"><el-form-item v-for="[key,label] in [['waybillNo','运单号'],['cargo','货物'],['origin','起运地'],['destination','目的地'],['carrier','承运主体'],['date','单据日期']]" :key="key" :label="label"><el-input v-model="fields[key]" :aria-label="'复核'+label" :disabled="review.status==='CONFIRMED'||busy"/></el-form-item><el-form-item label="数量（吨）"><el-input-number v-number-a11y v-model="fields.quantityTons" aria-label="识别数量（吨）" :min=".1" :max="100000" :precision="1" :step=".1" :disabled="review.status==='CONFIRMED'||busy"/></el-form-item></el-form><template v-if="review.status!=='CONFIRMED'"><el-checkbox v-model="ack" :disabled="busy">我已核对原单据和以上字段</el-checkbox><el-button type="primary" :disabled="!ack" :loading="busy" @click="confirm">保存人工复核结果</el-button></template><el-tag v-else type="success">已复核 · {{date(review.confirmedAt)}}</el-tag><details><summary>查看提取文本</summary><pre>{{review.extractedText||'未提取到有效内容，请核对原件并补录。'}}</pre></details></div></section></template>
<style scoped>.document-workspace{background:#fff;border:1px solid #e3eaf5;padding:22px;border-radius:12px;margin-top:20px}.document-workspace header,.document-title{display:flex;justify-content:space-between;align-items:center;gap:12px}.document-workspace h3{font-size:15px;margin:0}.document-workspace>p{color:#91a0b1;font-size:11px}.upload-button{font-size:12px;border:1px solid #79a8fa;color:#2877ed;position:relative;overflow:hidden;border-radius:6px;padding:9px 12px;cursor:pointer}.upload-button input{position:absolute;inset:0;opacity:0;cursor:pointer;width:100%}.document-list{display:flex;flex-wrap:wrap;gap:10px;margin:20px 0}.document-list .el-button{margin:0;font-size:12px}.document-title{font-size:13px;margin-bottom:16px}.review-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 16px;margin-top:16px}.review-grid :deep(.el-form-item__label){font-size:12px}.review-grid :deep(.el-input-number){width:100%}details{font-size:12px;color:#8694a8;margin-top:20px}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:240px;overflow:auto;font-size:12px}@media(max-width:650px){.review-grid{grid-template-columns:1fr}}</style>
