<script setup lang="ts">
import {reactive,ref,watch} from 'vue';
import {numberA11y as vNumberA11y} from '../number-a11y';
import PointPicker from './PointPicker.vue';
const props=defineProps<{draft:any;options:any;busy:boolean;disabled?:boolean}>();const emit=defineEmits(['confirm']);
const form=reactive<any>({}),error=ref('');watch(()=>props.draft,d=>Object.assign(form,JSON.parse(JSON.stringify(d))),{immediate:true});
function confirm(){error.value='';const missing=[!form.origin&&'起运位置',!form.destination&&'目的位置',!form.grainId&&'粮食品种',!form.quantity&&'运输数量',!form.departureAt&&'计划发运时间',!form.arrivalAt&&'要求到达时间'].filter(Boolean);if(missing.length){error.value='请填写：'+missing.join('、');return;}if(new Date(form.departureAt).getTime()<=Date.now()){error.value='计划发运时间必须晚于当前时间';return;}if(new Date(form.arrivalAt)<=new Date(form.departureAt)){error.value='要求到达时间必须晚于计划发运时间';return;}if([form.origin,form.destination].some(p=>p.matchKind==='APPROXIMATE')){error.value='地址仅定位到区域，请点击地址并在地图上确认装卸位置';return;}
 const keys=['grainId','cargoName','quantity','origin','destination','departureAt','arrivalAt','modes','loadingType','containerType','containerCount','demandId','demandVersion'];const dto=Object.fromEntries(keys.filter(k=>form[k]!=null&&form[k]!=='').map(k=>[k,form[k]]));Object.assign(dto,{allowModel:true,allowMultimodal:form.allowMultimodal??true,allowTransfer:form.allowTransfer??true,maxTransfers:form.maxTransfers??4,allowContainerization:true,preference:'BALANCED'});if(form.loadingType==='BULK'){delete dto.containerType;delete dto.containerCount;}emit('confirm',dto);}
</script>
<template><section class="agent-plan-confirm"><header><strong>运输条件确认</strong><span>{{form.sourceLocked?'已关联运输需求':'核对后生成路线'}}</span></header><p v-if="form.defaults?.length" class="defaults">{{form.defaults.join('；')}}。</p><el-form label-position="top" :disabled="busy||disabled"><div class="confirm-grid"><el-form-item label="起运详细地址" required><PointPicker v-model="form.origin" label="起运位置" :search-text="form.originText||form.originSearch" :nodes="options.nodes||[]" :disabled="busy||disabled"/></el-form-item><el-form-item label="目的详细地址" required><PointPicker v-model="form.destination" label="目的位置" :search-text="form.destinationText||form.destinationSearch" :nodes="options.nodes||[]" :disabled="busy||disabled"/></el-form-item><el-form-item label="粮食品种" required><el-select v-model="form.grainId" aria-label="确认粮食品种" :disabled="busy||disabled||form.sourceLocked"><el-option v-for="g in options.grains||[]" :key="g.id" :value="g.id" :label="g.label"/></el-select></el-form-item><el-form-item label="运输数量（吨）" required><el-input-number v-number-a11y v-model="form.quantity" aria-label="确认运输数量" :min=".1" :max="100000" :precision="1" :step=".1" :disabled="busy||disabled||form.sourceLocked"/></el-form-item><el-form-item label="计划发运时间" required><el-date-picker v-model="form.departureAt" aria-label="确认计划发运时间" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" :disabled-date="(d:Date)=>d.getTime()<new Date().setHours(0,0,0,0)" :disabled="busy||disabled||form.sourceLocked"/></el-form-item><el-form-item label="要求到达时间" required><el-date-picker v-model="form.arrivalAt" aria-label="确认要求到达时间" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ"/></el-form-item><el-form-item label="装载形式"><el-select v-model="form.loadingType" aria-label="确认装载形式" :disabled="busy||disabled||form.sourceLocked"><el-option value="BULK" label="散货"/><el-option value="CONTAINER" label="集装箱"/></el-select></el-form-item><el-form-item label="运输方式偏好"><el-select v-model="form.modes" multiple aria-label="确认运输方式偏好" :disabled="busy||disabled||form.sourceLocked"><el-option value="ROAD" label="公路"/><el-option value="RAIL" label="铁路"/><el-option value="WATER" label="水运"/></el-select></el-form-item><template v-if="form.loadingType==='CONTAINER'"><el-form-item label="箱型"><el-select v-model="form.containerType" aria-label="确认箱型"><el-option label="20GP" value="20GP"/><el-option label="40GP" value="40GP"/></el-select></el-form-item><el-form-item label="箱数"><el-input-number v-number-a11y v-model="form.containerCount" aria-label="确认箱数" :min="1" :max="10000" :precision="0"/></el-form-item></template></div></el-form><el-alert v-if="error" :title="error" type="error" :closable="false"/><div class="confirm-footer"><span>地址可搜索、选择业务节点或在地图确认。</span><el-button type="primary" :loading="busy" :disabled="disabled" @click="confirm">确认并生成联运方案</el-button></div></section></template>
<style scoped>.agent-plan-confirm{margin-top:20px;border-top:1px solid #edf0f5;padding-top:20px}.agent-plan-confirm header{display:flex;justify-content:space-between;font-size:15px;margin-bottom:16px}.agent-plan-confirm header>span,.defaults,.confirm-footer>span{font-size:12px;color:#8795a8}.defaults{line-height:1.7;margin-bottom:16px}.confirm-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 18px}.confirm-grid :deep(.el-form-item__label){font-size:12px;color:#63738a}.confirm-grid :deep(.el-input-number),.confirm-grid :deep(.el-date-editor){width:100%}.confirm-grid :deep(.point-trigger){min-height:60px}.confirm-footer{display:flex;align-items:center;justify-content:space-between;gap:12px;padding-top:10px}@media(max-width:700px){.confirm-grid{grid-template-columns:1fr}.confirm-footer{align-items:flex-start;flex-direction:column}}</style>
