<script setup lang="ts">
import {ref,watch} from 'vue';import {api,get,message} from '../api';import {date} from '../fulfillment';import {openAgent} from '../agent';
const props=defineProps<{taskId:string;includeTest:boolean;asOf?:string;preview?:any}>(),forecast=ref<any>(),busy=ref(false),error=ref('');let sequence=0;
const qualities:Record<string,string>={INITIALIZATION:'参考测算',ACTUAL:'实际执行记录',MEDIUM:'可信度中等',LOW:'可信度较低',SIMULATED:'参考测算',INSUFFICIENT:'数据不足'};
async function load(force=false){const seq=++sequence;busy.value=true;error.value='';try{if(props.preview){forecast.value=props.preview;return;}const path='/eta/tasks/'+props.taskId+(force?'/refresh':'');const response=force?(await api.post(path,null,{params:{includeTest:String(props.includeTest)},timeout:45000})).data.data:await get(path,{includeTest:String(props.includeTest)});if(seq===sequence)forecast.value=response;}catch(e){if(seq===sequence){error.value=message(e);forecast.value=null;}}finally{if(seq===sequence)busy.value=false;}}
watch(()=>[props.taskId,props.includeTest,props.asOf,props.preview],()=>load(),{immediate:true});
</script>
<template><section class="forecast-panel"><header><h3>预计到达与影响因素</h3><el-button link :loading="busy" @click="load(true)">重新预测</el-button></header><el-alert v-if="error" :title="error" type="warning" :closable="false"/><el-skeleton v-if="busy&&!forecast" :rows="2" animated/><template v-if="forecast"><el-tag size="small" :type="forecast.quality==='ACTUAL'?'success':'warning'">{{qualities[forecast.quality]}}</el-tag><strong class="eta-time">{{forecast.eta?date(forecast.eta):'当前无法可靠预测'}}</strong><small>当前区段 · {{date(forecast.predictedAt)}} 预测</small><p v-if="forecast.range">参考范围：{{date(forecast.range.from)}} — {{date(forecast.range.to)}}</p><p v-if="forecast.remainingKm!==null">剩余路径 {{forecast.remainingKm}} km · {{forecast.remainingMinutes===null?'时长待核实':forecast.remainingMinutes+' 分钟'}}</p><p>{{forecast.finalEtaNote}}</p><p v-if="forecast.delayMinutes">相对约定到达：预计晚 {{forecast.delayMinutes}} 分钟</p><ul><li v-for="f in forecast.factors" :key="f">{{f}}</li></ul><small v-if="forecast.needsReview">需人工确认 · 预测不会替代到达、签收或异常处理事实</small><details><summary>数据依据</summary><p v-for="(s,i) in forecast.sources" :key="i">{{s.source}} · {{s.observedAt?date(s.observedAt):'业务历史'}}</p></details></template><el-button class="ask-tracking" @click="openAgent({contextType:'task',contextId:taskId,suggestedAgent:'TRACK'})">智能问踪</el-button><el-button class="ask-tracking" @click="openAgent({contextType:'task',contextId:taskId,suggestedAgent:'DOCUMENT'})">单据识别与复核</el-button></section></template>
<style scoped>.forecast-panel{border-top:1px solid var(--border);border-bottom:1px solid var(--border);padding:16px 0;margin:16px 0;font-size:11px;line-height:1.8}.forecast-panel header{display:flex;align-items:center;justify-content:space-between;gap:8px}.forecast-panel h3{font-size:12px}.forecast-panel small{color:var(--text-secondary);font-size:10px;display:block}.eta-time{display:block;font-size:15px;margin:12px 0 4px}.forecast-panel p{margin:8px 0}.forecast-panel ul{padding-left:16px;color:var(--text-secondary)}details{font-size:10px;margin:12px 0}summary{cursor:pointer}.ask-tracking{width:100%;margin:8px 0 0!important;font-size:11px}</style>
