<script setup lang="ts">
import {requestKey} from '../request-key';
import BusinessStatus from './BusinessStatus.vue';
import {ref,reactive,computed,watch} from 'vue';
import {ElMessage,ElMessageBox,ElDrawer} from 'element-plus';
import {api,get,message} from '../api';
import {label,transportMode,date,ton,money,download} from '../fulfillment';
const props=defineProps<{business:any,stageId:string,canWrite:boolean,embedded?:boolean}>(),emit=defineEmits(['close','changed']);
const b=ref<any>(props.business),s=computed(()=>b.value.stages.find((s:any)=>s.id===props.stageId)),busy=ref(false),error=ref(''),finish=ref(false);
watch(()=>props.business,value=>{b.value=value;});
const editable=computed(()=>props.canWrite&&b.value.status!=='COMPLETED'&&b.value.package.status==='EFFECTIVE');
const completion=reactive<any>({actualEndAt:'',quantity:0,note:''}),fees=computed(()=>b.value.serviceFees.filter((f:any)=>f.stageId===props.stageId));
const fee=reactive<any>({feeCode:'OTHER',amount:0,description:'',evidenceId:'',requestKey:requestKey()});
const sources:Record<string,string>={CONTRACT:'合同费用',DRIVER:'司机回传',OTHER:'其他费用'},status:Record<string,string>={DRAFT:'待提交',SUBMITTED:'执行中',COMPLETED:'已完成'};
async function refresh(){b.value=await get('/intermodal/'+b.value.id);emit('changed');}
async function file(f:any,driver=false){try{const result=await api.get(driver?'/fulfillment/evidence/'+f.id:'/intermodal/attachments/'+f.id,{responseType:'blob'});download(result.data,f.name,f.mime);}catch(e){error.value=message(e);}}
async function upload(e:Event){const input=e.target as HTMLInputElement,f=input.files?.[0];if(!f)return;busy.value=true;try{const data=new FormData();data.append('file',f);await api.post('/intermodal/stages/'+s.value.id+'/attachments',data);await refresh();ElMessage.success('附件已上传');}catch(e){error.value=message(e);}finally{busy.value=false;input.value='';}}
function beginFinish(){Object.assign(completion,{actualEndAt:new Date().toISOString(),quantity:s.value.mode==='ROAD'?s.value.tasks.reduce((n:number,t:any)=>n+(t.unloadedKg||0),0)/1000:s.value.quantityKg/1000,note:''});error.value='';finish.value=true;}
async function confirmStage(){busy.value=true;error.value='';try{await api.post('/intermodal/stages/'+s.value.id+'/complete',{version:s.value.version,actualEndAt:completion.actualEndAt,quantityKg:Math.round(completion.quantity*1000),note:completion.note});finish.value=false;await refresh();ElMessage.success('阶段已完成，可勾选对账费用');}catch(e){error.value=message(e);}finally{busy.value=false;}}
async function addFee(){if(!fee.amount||!fee.description.trim()){error.value='请填写费用金额和具体说明';return;}busy.value=true;error.value='';try{await api.post('/intermodal/stages/'+s.value.id+'/fees',{feeCode:fee.feeCode,amountCents:Math.round(fee.amount*100),description:fee.description,evidenceId:fee.evidenceId||undefined,requestKey:fee.requestKey});Object.assign(fee,{amount:0,description:'',evidenceId:'',requestKey:requestKey()});await refresh();ElMessage.success('费用已登记');}catch(e){error.value=message(e);}finally{busy.value=false;}}
async function toggleFee(f:any,checked:boolean){busy.value=true;try{await api.put('/intermodal/fees/'+f.id,{version:f.version,selected:checked});await refresh();}catch(e){error.value=message(e);}finally{busy.value=false;}}
async function resolve(i:any){try{const {value:resolution}=await ElMessageBox.prompt('填写异常处理结果','处理运输异常',{inputValidator:v=>v?.trim().length>=2||'请填写处理说明'});busy.value=true;await api.post('/fulfillment/issues/'+i.id+'/resolve',{resolution});await refresh();}catch(e){if(e!=='cancel'&&e!=='close')error.value=message(e);}finally{busy.value=false;}}
</script>
<template><component :is="embedded?'section':ElDrawer" v-bind="embedded?{}:{modelValue:true,title:transportMode(s.mode)+' · 第 '+s.sequence+' 阶段',size:'850px'}" @close="emit('close')"><el-alert v-if="error&&!finish" :title="error" type="error" :closable="false" show-icon/><div class="stage-detail-top"><div><strong>{{s.origin}} → {{s.destination}}</strong><p>{{b.waybillNo}} · {{b.cargo}} · {{ton(s.quantityKg)}}</p></div><BusinessStatus :status="s.status" :label="status[s.status]"/></div><el-descriptions :column="2" border><el-descriptions-item label="开始时间">{{date(s.plannedStartAt)}}</el-descriptions-item><el-descriptions-item label="预计结束">{{date(s.plannedEndAt)}}</el-descriptions-item><el-descriptions-item label="实际完成">{{date(s.actualEndAt)}}</el-descriptions-item><el-descriptions-item label="装载形式">{{s.containerized?'集装箱':'散货'}}</el-descriptions-item><template v-if="s.mode==='WATER'"><el-descriptions-item label="船名 / 航次">{{s.vessel}} / {{s.voyage}}</el-descriptions-item><el-descriptions-item label="提单号">{{s.billOfLading}}</el-descriptions-item><el-descriptions-item v-if="s.containerized" label="箱号" :span="2">{{s.boxes.join('、')}}</el-descriptions-item><el-descriptions-item v-else label="过磅信息" :span="2">{{s.weightTicketNo}} · 毛重 {{ton(s.grossKg||0)}} · 皮重 {{ton(s.tareKg||0)}} · 净重 {{ton((s.grossKg||0)-(s.tareKg||0))}}</el-descriptions-item></template><el-descriptions-item v-if="s.mode==='RAIL'" label="铁路运单号" :span="2">{{s.railWaybillNo}}</el-descriptions-item><el-descriptions-item label="补充说明" :span="2">{{s.notes||'—'}}</el-descriptions-item><el-descriptions-item v-if="s.completionNote" label="完成说明" :span="2">{{s.completionNote}}</el-descriptions-item></el-descriptions>
<template v-if="s.mode==='ROAD'"><h3>车辆任务与司机回传</h3><article v-for="t in s.tasks" :key="t.id" class="driver-report"><header><strong>{{t.vehicle?.plate||t.resource}} · {{t.driver?.displayName}}</strong><BusinessStatus :status="t.feedbackSubmittedAt?'SUBMITTED':t.status" :label="t.feedbackSubmittedAt?'已回传业务信息':label(t.status)" compact/></header><p>{{t.businessNo}} · {{t.feedbackSubmittedAt||t.unloadedKg>0?'实际签收 '+ton(t.unloadedKg||t.feedback?.quantityKg||0):'待过磅'}}</p><div v-if="t.feedbackSubmittedAt" class="resource"><span>签收人 <b>{{t.feedback.receiver}}</b></span><span v-if="s.containerized">铅封号 <b>{{t.feedback.sealNo}}</b></span><span>磅单号 <b>{{t.feedback.weightTicketNo||'见磅单附件'}}</b></span><span v-if="s.containerized&&t.feedback.containers?.length">箱号与粮食数量 <b>{{t.feedback.containers.map((c:any)=>c.boxNo+' · '+ton(c.quantityKg)).join('；')}}</b></span><span v-if="t.feedback.grossKg!=null&&t.feedback.tareKg!=null">过磅净重 <b>{{ton(t.feedback.grossKg-t.feedback.tareKg)}}</b></span><span>{{t.feedback.note}}</span></div><div class="file-links"><el-button v-for="f in t.evidence" :key="f.id" link type="primary" @click="file(f,true)">{{f.category==='EIR'?'设备交接单':f.category==='WEIGH'?'磅单':f.category==='RECEIPT'?'签收单':f.category==='FEE'?'费用凭证':'附件'}} · {{f.name}}</el-button></div><div v-for="i in t.issues.filter((i:any)=>i.status==='OPEN')" :key="i.id" class="issue-warning">未处理异常：{{i.description}} <el-button v-if="editable" link type="primary" @click="resolve(i)">处理异常</el-button></div></article></template><div class="detail-heading"><h3>阶段附件</h3><label v-if="editable&&s.status!=='COMPLETED'" class="service-upload"><input type="file" accept=".pdf,.png,.jpg,.jpeg" :disabled="busy" @change="upload"/>上传附件</label></div><div class="file-links"><el-button v-for="f in s.attachments" :key="f.id" link type="primary" @click="file(f)">{{f.name}}</el-button><span v-if="!s.attachments.length" class="muted">暂无附件</span></div><el-button v-if="editable&&s.status==='SUBMITTED'" type="primary" class="stage-complete-button" @click="beginFinish">确认阶段完成</el-button>
<template v-if="s.status==='COMPLETED'"><div class="detail-heading"><h3>对账费用</h3><span class="muted">勾选后计入总运单账单</span></div><el-table :data="fees"><el-table-column label="计入账单" width="90"><template #default="{row:f}"><el-checkbox :model-value="f.selected" :disabled="!editable||busy" :aria-label="'计入费用 '+f.name" @change="(v:any)=>toggleFee(f,!!v)"/></template></el-table-column><el-table-column label="费用 / 来源" min-width="165"><template #default="{row:f}">{{f.name}}<small>{{sources[f.source]}}</small></template></el-table-column><el-table-column label="金额" width="120"><template #default="{row:f}">{{money(f.amountCents)}}</template></el-table-column><el-table-column label="说明" prop="description" min-width="150"/></el-table><p class="muted">合同运输费用 {{money(b.package.totalCents)}} 在业务完成时按总运单勾选。</p><el-form v-if="editable" label-position="top" class="stage-other-fees"><h4>添加其他费用</h4><div class="other-fee-grid"><el-form-item label="费用项目"><el-select v-model="fee.feeCode"><el-option label="船公司放单费" value="SHIP_RELEASE"/><el-option label="港口杂项作业费" value="PORT_MISC"/><el-option label="清箱费" value="CLEAN_BOX"/><el-option label="其他费用" value="OTHER"/></el-select></el-form-item><el-form-item label="金额（元）" required><el-input-number v-model="fee.amount" :min="0" :max="1000000" :precision="2"/></el-form-item></div><el-form-item label="具体说明" required><el-input v-model="fee.description" type="textarea" :rows="2" maxlength="2000" aria-label="其他费用说明"/></el-form-item><el-form-item v-if="s.attachments.length" label="关联阶段凭证"><el-select v-model="fee.evidenceId" clearable><el-option v-for="f in s.attachments" :key="f.id" :value="f.id" :label="f.name"/></el-select></el-form-item><el-button :loading="busy" @click="addFee">登记费用</el-button></el-form></template>
<el-dialog v-model="finish" title="确认阶段完成" width="570px" append-to-body :close-on-click-modal="false"><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-form label-position="top"><el-form-item label="实际完成时间" required><el-date-picker v-model="completion.actualEndAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss.SSSZ"/></el-form-item><el-form-item label="实际交付数量（吨）" required><el-input-number v-model="completion.quantity" :disabled="s.mode==='ROAD'" :min="0.1" :precision="1" :step=".1"/></el-form-item><el-form-item label="完成说明（数量有偏差时必填）"><el-input v-model="completion.note" type="textarea" :rows="3" maxlength="2000"/></el-form-item></el-form><template #footer><el-button @click="finish=false">取消</el-button><el-button type="primary" :loading="busy" @click="confirmStage">确认完成</el-button></template></el-dialog></component></template>
<style scoped>.stage-detail-top{display:flex;align-items:center;justify-content:space-between;margin-bottom:20px;gap:14px}.stage-detail-top strong{font-size:16px}.stage-detail-top p{font-size:12px;color:#8a94a2}h3{font-size:14px;margin:24px 0 14px}.detail-heading{display:flex;align-items:center;justify-content:space-between;gap:15px}.detail-heading h3{margin:20px 0 14px}.muted{font-size:12px;color:#8a94a2}.driver-report{border:1px solid #e5eaf0;background:#fafbfc;padding:16px;border-radius:7px;margin:12px 0}.driver-report header{display:flex;justify-content:space-between;align-items:center;font-size:13px}.driver-report p{font-size:12px;color:#8a94a2}.resource{display:flex;flex-wrap:wrap;gap:12px 28px;font-size:12px;color:#8a94a2}.resource b{color:#384454;margin-left:8px;font-weight:500}.file-links{display:flex;align-items:center;flex-wrap:wrap;gap:6px 14px}.file-links .el-button{margin:0}.service-upload{color:#e72b32;border:1px solid #f0b4b9;border-radius:5px;padding:6px 12px;cursor:pointer;font-size:12px}.service-upload input{position:absolute;opacity:0;width:1px;height:1px}.service-upload:focus-within{outline:2px solid #e72b32;outline-offset:2px}.stage-complete-button{margin:22px 0 8px}.issue-warning{color:#d87919;font-size:12px;margin-top:10px}.other-fee-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.stage-other-fees{margin-top:22px;border:1px solid #e5eaf0;padding:18px;border-radius:7px}.stage-other-fees h4{margin:0 0 18px;font-size:13px}.stage-other-fees :deep(.el-select),.stage-other-fees :deep(.el-input-number){width:100%}:deep(.cell small){display:block;color:#8a94a2;font-size:11px;margin-top:4px}</style>
