<script setup lang="ts">
import {ref,reactive,computed,onMounted} from 'vue';
import {ElMessage} from 'element-plus';
import {api,get,message} from '../api';
import {ton} from '../fulfillment';
const props=defineProps<{business:any,stage?:any,resources:any}>(),emit=defineEmits(['close','changed']);
const busy=ref(false),error=ref(''),savedId=ref(props.stage?.id||''),files=ref<any[]>(props.stage?.attachments||[]),uploading=ref(false);
const defaultStart=new Date().toISOString(),defaultEnd=new Date(Date.now()+86400000).toISOString();
const f=reactive<any>({...{mode:'ROAD',origin:props.business.origin,destination:props.business.destination,quantityKg:props.business.package.quantityKg,plannedStartAt:defaultStart,plannedEndAt:defaultEnd,allocations:[],vessel:'',voyage:'',vesselId:'',mmsi:'',billOfLading:'',railWaybillNo:'',containerized:props.business.package.snapshot.loadingType==='CONTAINER',boxes:[],weightTicketNo:'',grossKg:null,tareKg:null,notes:''},...props.stage,allocations:(props.stage?.allocations||[]).map((a:any)=>({...a})),boxes:[...(props.stage?.boxes||[])]});
const quantity=ref(f.quantityKg/1000),gross=ref(f.grossKg==null?undefined:f.grossKg/1000),tare=ref(f.tareKg==null?undefined:f.tareKg/1000),boxesText=ref(f.boxes.join('\n'));
const fixedContainer=computed(()=>props.business.package.snapshot.loadingType==='CONTAINER');

function addVehicle(){f.allocations.push({vehicleId:'',plate:'',capacityKg:undefined,driverId:'',startAt:f.plannedStartAt,endAt:f.plannedEndAt});}
function payload(){return {version:f.version,mode:f.mode,origin:f.origin,destination:f.destination,quantityKg:Math.round(quantity.value*1000),plannedStartAt:f.plannedStartAt,plannedEndAt:f.plannedEndAt,allocations:f.mode==='ROAD'?f.allocations.map((a:any)=>({vehicleId:a.vehicleId||undefined,plate:a.vehicleId?undefined:a.plate,capacityKg:a.vehicleId||a.capacityKg==null?undefined:Math.round(a.capacityKg),driverId:a.driverId,startAt:a.startAt||undefined,endAt:a.endAt||undefined})):[],vessel:f.vessel,voyage:f.voyage,vesselId:f.vesselId||undefined,mmsi:f.mmsi||'',billOfLading:f.billOfLading,railWaybillNo:f.railWaybillNo,containerized:f.containerized,boxes:boxesText.value.split(/[\n,，;；\s]+/).filter(Boolean),weightTicketNo:f.weightTicketNo,grossKg:gross.value==null?undefined:Math.round(gross.value*1000),tareKg:tare.value==null?undefined:Math.round(tare.value*1000),notes:f.notes};}
const vessels=ref<any[]>([]);onMounted(async()=>{try{vessels.value=(await get('/vessels',{pageSize:100})).items.filter((v:any)=>v.enabled);}catch{}});function chooseVessel(id:string){const v=vessels.value.find(v=>v.id===id);if(v)Object.assign(f,{vesselId:v.id,vessel:v.name,voyage:v.voyage,mmsi:v.mmsi});}
const baseline=ref(JSON.stringify(payload())),hasUnsavedChanges=computed(()=>JSON.stringify(payload())!==baseline.value);
defineExpose({hasUnsavedChanges});
async function save(close=false){error.value='';if(!f.origin?.trim()||!f.destination?.trim()||!f.plannedStartAt||!f.plannedEndAt||!quantity.value){error.value='请填写路线、运输数量、开始时间和预计结束时间';return false;}busy.value=true;try{const result=(await (savedId.value?api.put('/intermodal/stages/'+savedId.value,payload()):api.post('/intermodal/'+props.business.id+'/stages',payload()))).data.data;savedId.value=result.id;f.version=result.version;baseline.value=JSON.stringify(payload());emit('changed',result.id);if(close){ElMessage.success('运输阶段已保存');emit('close');}return true;}catch(e){error.value=message(e);return false;}finally{busy.value=false;}}
async function submit(){if(!await save())return;busy.value=true;try{await api.post('/intermodal/stages/'+savedId.value+'/submit',{version:f.version});ElMessage.success(f.mode==='ROAD'?'阶段已提交，车辆任务已下发至司机端':'运输阶段已提交');emit('changed');emit('close');}catch(e){error.value=message(e);}finally{busy.value=false;}}
async function upload(e:Event){const input=e.target as HTMLInputElement,file=input.files?.[0];if(!file)return;uploading.value=true;try{if(!await save())return;const data=new FormData();data.append('file',file);await api.post('/intermodal/stages/'+savedId.value+'/attachments',data);const b=await get('/intermodal/'+props.business.id),s=b.stages.find((s:any)=>s.id===savedId.value);f.version=s.version;baseline.value=JSON.stringify(payload());files.value=s.attachments;emit('changed');ElMessage.success('附件已上传');}catch(e){error.value=message(e);}finally{uploading.value=false;input.value='';}}
</script>
<template><section class="stage-editor"><h2>{{stage?'填写运输阶段':'添加运输阶段'}}</h2><el-alert v-if="error" :title="error" type="error" :closable="false" show-icon/><p class="editor-reference">{{business.waybillNo}} · {{business.cargo}} · 合同数量 {{ton(business.package.quantityKg)}}</p><el-form label-position="top"><div class="stage-grid"><el-form-item label="运输阶段" required><el-select v-model="f.mode" aria-label="运输阶段"><el-option label="公路运输" value="ROAD"/><el-option label="水运信息" value="WATER"/><el-option label="铁路信息" value="RAIL"/></el-select></el-form-item><el-form-item label="本阶段运输数量（吨）" required><el-input-number v-model="quantity" :min="0.1" :max="business.package.quantityKg/1000" :precision="1" :step=".1" aria-label="阶段运输数量"/></el-form-item><el-form-item :label="f.mode==='WATER'?'起运港':f.mode==='RAIL'?'发站':'起运地址'" required><el-input v-model="f.origin" aria-label="阶段起运地" maxlength="300"/></el-form-item><el-form-item :label="f.mode==='WATER'?'目的港':f.mode==='RAIL'?'到站':'目的地址'" required><el-input v-model="f.destination" aria-label="阶段目的地" maxlength="300"/></el-form-item><el-form-item :label="f.mode==='ROAD'?'开始时间':'预计开始时间'" required><el-date-picker v-model="f.plannedStartAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss.SSSZ" aria-label="阶段开始时间"/></el-form-item><el-form-item label="预计结束时间" required><el-date-picker v-model="f.plannedEndAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss.SSSZ" aria-label="阶段预计结束时间"/></el-form-item></div>
<template v-if="f.mode==='ROAD'"><el-form-item label="装载形式"><el-select v-model="f.containerized" :disabled="fixedContainer" aria-label="公路装载形式"><el-option label="散货" :value="false"/><el-option label="集装箱" :value="true"/></el-select></el-form-item><div class="editor-section"><h3>车辆与司机分配</h3><span>{{f.allocations.length}} 辆车</span><el-button @click="addVehicle">添加车辆</el-button></div><el-alert v-if="!resources.drivers.length" title="本企业暂无可分配的司机账号，请先在用户管理中创建司机账号。" type="warning" :closable="false"/><article v-for="(a,i) in f.allocations" :key="i" class="vehicle-allocation"><header><strong>车辆 {{i+1}}</strong><el-button link type="danger" @click="f.allocations.splice(i,1)">移除</el-button></header><div class="stage-grid three"><el-form-item label="已登记车辆"><el-select v-model="a.vehicleId" clearable :aria-label="'选择车辆 '+(i+1)" placeholder="可选择车辆或填写新车牌"><el-option v-for="v in resources.vehicles" :key="v.id" :value="v.id" :label="v.plate+' · '+ton(v.capacityKg)"/></el-select></el-form-item><el-form-item v-if="!a.vehicleId" label="车牌号" required><el-input v-model="a.plate" :aria-label="'车牌号 '+(i+1)"/></el-form-item><el-form-item v-if="!a.vehicleId" label="核定载重（吨）" required><el-input-number :model-value="a.capacityKg==null?undefined:a.capacityKg/1000" :min="0.1" :max="100" :precision="1" :step=".1" @update:model-value="(v:any)=>a.capacityKg=Math.round(v*1000)"/></el-form-item><el-form-item label="司机账号" required><el-select v-model="a.driverId" :aria-label="'司机账号 '+(i+1)"><el-option v-for="d in resources.drivers" :key="d.id" :value="d.id" :label="d.displayName+(d.phone?' · '+d.phone:'')"/></el-select></el-form-item><el-form-item label="开始时间"><el-date-picker v-model="a.startAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss.SSSZ"/></el-form-item><el-form-item label="预计结束时间"><el-date-picker v-model="a.endAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss.SSSZ"/></el-form-item></div></article></template>
<template v-if="f.mode==='WATER'"><el-form-item label="船舶档案"><el-select v-model="f.vesselId" filterable clearable placeholder="选择本企业船舶与航次" aria-label="选择船舶档案" @change="chooseVessel"><el-option v-for="v in vessels" :key="v.id" :value="v.id" :label="v.name+' / '+v.voyage+' / '+v.mmsi"/></el-select></el-form-item><div class="stage-grid three"><el-form-item label="船名" required><el-input v-model="f.vessel" aria-label="船名"/></el-form-item><el-form-item label="航次" required><el-input v-model="f.voyage" aria-label="航次"/></el-form-item><el-form-item label="MMSI"><el-input v-model="f.mmsi" aria-label="阶段MMSI" maxlength="9" inputmode="numeric" :disabled="!!f.vesselId"/></el-form-item><el-form-item label="提单号" required><el-input v-model="f.billOfLading" aria-label="提单号"/></el-form-item></div><div class="editor-section"><h3>装载信息</h3><el-tag>{{f.containerized?'集装箱':'散货'}}</el-tag><el-button v-if="!fixedContainer&&!f.containerized" type="primary" plain @click="f.containerized=true">散改集</el-button><el-button v-if="!fixedContainer&&f.containerized" link @click="f.containerized=false">恢复散货</el-button></div><el-form-item v-if="f.containerized" label="箱号（支持多个，每行一个）" required><el-input v-model="boxesText" type="textarea" :rows="3" placeholder="输入箱号，每行一个" aria-label="箱号"/></el-form-item><div v-if="!f.containerized" class="stage-grid three"><el-form-item label="过磅单号" required><el-input v-model="f.weightTicketNo" aria-label="过磅单号"/></el-form-item><el-form-item label="毛重（吨）" required><el-input-number v-model="gross" :min="0.1" :precision="1" :step=".1" aria-label="过磅毛重"/></el-form-item><el-form-item label="皮重（吨）" required><el-input-number v-model="tare" :min="0" :precision="1" :step=".1" aria-label="过磅皮重"/></el-form-item></div></template>
<el-form-item v-if="f.mode==='RAIL'" label="铁路运单号" required><el-input v-model="f.railWaybillNo" aria-label="铁路运单号"/></el-form-item><el-form-item label="补充说明"><el-input v-model="f.notes" type="textarea" :rows="2" maxlength="2000"/></el-form-item><div class="editor-section"><h3>阶段附件</h3><label class="service-upload"><input type="file" accept=".pdf,.png,.jpg,.jpeg" :disabled="busy||uploading" aria-label="上传阶段附件" @change="upload"/>{{uploading?'上传中…':'上传附件'}}</label><small>图片或 PDF，单份不超过 8MB</small></div><div v-for="v in files" :key="v.id" class="editor-file">{{v.name}}</div></el-form><div class="editor-actions"><el-button @click="emit('close')">返回阶段详情</el-button><el-button :loading="busy" :disabled="uploading" @click="save(true)">保存草稿</el-button><el-button type="primary" :loading="busy" :disabled="uploading" @click="submit">提交阶段</el-button></div></section></template>
<style scoped>.stage-editor h2{font-size:16px;margin:0 0 12px}.editor-actions{display:flex;justify-content:flex-end;gap:8px;border-top:1px solid #e7ebf0;margin-top:20px;padding-top:20px}.editor-actions .el-button{margin-left:0}.editor-reference{color:#7d8897;font-size:13px;margin:10px 0 20px}.stage-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 20px}.stage-grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.stage-grid :deep(.el-select),.stage-grid :deep(.el-date-editor),.stage-grid :deep(.el-input-number){width:100%}.editor-section{display:flex;align-items:center;gap:14px;margin:8px 0 15px}.editor-section h3{font-size:14px;margin:0 auto 0 0}.editor-section small,.editor-section span{font-size:12px;color:#7d8897}.vehicle-allocation{background:#f7f8fa;border:1px solid #e8ecf1;padding:16px;margin-bottom:12px;border-radius:8px}.vehicle-allocation header{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px;font-size:13px}.service-upload{display:inline-flex;align-items:center;padding:7px 13px;color:#e72b32;border:1px solid #f3b4b7;border-radius:5px;cursor:pointer;font-size:13px}.service-upload input{position:absolute;width:1px;height:1px;opacity:0}.service-upload:focus-within{outline:2px solid #e72b32;outline-offset:2px}.editor-file{background:#f7f8fa;padding:9px 12px;border-radius:5px;margin:6px 0;font-size:12px}</style>
