<script setup lang="ts">
import {ref,watch} from 'vue';import {useMap} from '../use-map';import MapLoadStatus from './MapLoadStatus.vue';
const props=defineProps<{segments?:any[];points?:any[];selected?:number;pick?:boolean}>();const emit=defineEmits(['select','point','node','ready']);
const container=ref<HTMLElement>(),modes=ref(['ROAD','RAIL','WATER']),nodeInfo=ref<any>(null);let map:any,AMap:any,overlays:any[]=[];
const colors:Record<string,string>={ROAD:'#2f80ed',RAIL:'#805ad5',WATER:'#149eac'};
const {loading,ready,error,tilesLoading,slowTiles,interactiveMs,tilesMs,init}=useMap(container,{zoom:5,center:[113.8,34.8],mapStyle:'amap://styles/normal',features:['bg','road'],showLabel:true},{
 created(instance,api){map=instance;AMap=api;map.on('click',(e:any)=>{if(props.pick)emit('point',{name:`地图选点 ${e.lnglat.getLng().toFixed(5)},${e.lnglat.getLat().toFixed(5)}`,lng:Number(e.lnglat.getLng().toFixed(6)),lat:Number(e.lnglat.getLat().toFixed(6))});});render();},
 ready:()=>emit('ready'),disposed(){map=undefined;overlays=[];}
},'RT');
function render(refit=true){if(!map)return;map.remove(overlays);overlays=[];nodeInfo.value=null;const points:any[]=[...(props.points||[])];for(const s of props.segments||[]){if(!modes.value.includes(s.mode))continue;points.push(s.origin,s.destination);const path=s.geometry?.coordinates?.length?s.geometry.coordinates:s.displayPath;if(!path?.length)continue;const active=!props.selected||props.selected===s.sequence;const line=new AMap.Polyline({path,strokeColor:colors[s.mode],strokeWeight:active?6:4,strokeOpacity:active?.94:.35,strokeStyle:s.mode==='ROAD'?'solid':'dashed',strokeDasharray:s.mode==='RAIL'?[10,6]:[3,6],isOutline:true,outlineColor:'#ffffff',borderWeight:1,lineJoin:'round',zIndex:active?80:40});line.on('click',()=>emit('select',s.sequence));overlays.push(line);}
 const unique=new Map(points.filter(p=>p&&Number.isFinite(p.lng)).map(p=>[`${p.lng},${p.lat}`,p]));let i=0;for(const point of unique.values()){const content=document.createElement('button');content.type='button';content.className='planning-marker';++i;content.textContent=props.pick?(unique.size===1?'选':String(i)):i===1?'起':i===unique.size?'终':String(i-1);content.title=point.name;content.setAttribute('aria-label',point.name);const marker=new AMap.Marker({position:[point.lng,point.lat],content,anchor:'center',title:point.name,zIndex:110});marker.on('click',()=>{nodeInfo.value=point;emit('node',point);});overlays.push(marker);}map.add(overlays);if(refit)fit();}
function fit(){if(props.pick&&props.points?.length===1){const p=props.points[0];map?.setZoomAndCenter(15,[p.lng,p.lat]);}else if(overlays.length)map?.setFitView(overlays,true,[65,65,65,65]);}
watch(()=>[props.segments,props.points,modes.value],()=>render(),{deep:true});watch(()=>props.selected,()=>{render(false);});defineExpose({fit});
</script>
<template><div class="planning-map" :data-map-ready="ready" :data-map-interactive-ms="interactiveMs" :data-map-tiles-ms="tilesMs"><div ref="container" class="map-canvas" :aria-label="pick?'装卸位置选择地图':'高德方案路径地图'"/><MapLoadStatus :loading="loading" :ready="ready" :error="error" :tiles-loading="tilesLoading" :slow-tiles="slowTiles" @retry="init"/><template v-if="!error&&!loading"><div class="map-controls"><el-checkbox-group v-if="!pick" v-model="modes"><el-checkbox value="ROAD"><span class="line-key road"></span>公路</el-checkbox><el-checkbox value="RAIL"><span class="line-key rail"></span>铁路</el-checkbox><el-checkbox value="WATER"><span class="line-key water"></span>水运</el-checkbox></el-checkbox-group><el-button size="small" @click="fit">{{pick?'适配视图':'适配全程'}}</el-button></div><div v-if="pick" class="map-pick-note">点击地图选择位置；请核对装卸节点</div><div v-if="nodeInfo" class="map-node-info"><strong>{{nodeInfo.name}}</strong><span>{{nodeInfo.lng}}, {{nodeInfo.lat}} · GCJ-02</span><el-button link @click="nodeInfo=null">关闭</el-button></div><div v-if="!tilesLoading" class="map-source">{{pick?'高德地图 · 点击选择实际装卸位置':'高德底图 · 公路实线 / 铁路长虚线 / 水运短虚线 · 虚线为走廊示意'}}</div></template></div></template>
<style scoped>.planning-map{position:relative;min-height:450px;height:100%;overflow:hidden;background:#f0f3f5;border-radius:8px;border:1px solid #e5e9ee}.map-canvas{position:absolute;inset:0}.map-controls{position:absolute;left:12px;top:12px;right:50px;display:flex;align-items:center;justify-content:space-between;gap:8px;background:#ffffffee;padding:5px 12px;border-radius:6px;box-shadow:0 2px 10px #263a4912}.map-controls :deep(.el-checkbox){margin-right:13px}.map-controls :deep(.el-checkbox__label){font-size:12px;padding-left:5px}.line-key{display:inline-block;width:13px;border-top:2px solid;margin-right:4px;vertical-align:middle}.road{color:#2f80ed}.rail{color:#805ad5;border-top-style:dashed}.water{color:#149eac;border-top-style:dotted}.map-source{position:absolute;bottom:30px;right:8px;background:#ffffffe6;padding:4px 8px;color:#697788;font-size:10px}.map-pick-note{position:absolute;left:15px;top:65px;padding:8px;background:#fff5e4;color:#916721;font-size:12px;border-radius:4px}.map-node-info{position:absolute;left:14px;bottom:45px;background:white;padding:14px;border-radius:6px;box-shadow:0 4px 18px #1f293721;max-width:80%;display:flex;gap:8px;flex-wrap:wrap}.map-node-info span{font-size:11px;color:#6f7a86}</style>
<style>.planning-marker{width:25px;height:25px;border:2px solid white;border-radius:50%;background:#293d53;color:white;font-size:11px;box-shadow:0 2px 6px #293d5344;display:grid;place-items:center}.planning-marker:hover{background:#e52b2f}</style>
