<script setup lang="ts">
import {requestKey} from '../request-key';
import {ref,computed} from 'vue';
import {ElMessage,ElMessageBox} from 'element-plus';
import {api,message} from '../api';
import {label,eventLabel,date,ton,download} from '../fulfillment';
const props=defineProps<{task:any;driver?:boolean;client?:any;editable?:boolean}>(),emit=defineEmits(['changed']);
const error=ref(''),busy=ref(false),dialog=ref(false),issueDialog=ref(false),kind=ref(''),form=ref<any>({}),issue=ref({type:'OTHER',description:''});
const client=computed(()=>props.client||api),prefix=computed(()=>props.driver?'/driver':'/fulfillment');
const next:Record<string,string>={DISPATCHED:'ACCEPT',ACCEPTED:'AT_LOADING',AT_LOADING:'LOAD',LOADED:'DEPART',IN_TRANSIT:'ARRIVE',ARRIVED:'UNLOAD',UNLOADED:'RECEIPT',RECEIVED:'COMPLETE'};
const canExecute=computed(()=>props.driver||props.editable&&props.task.mode!=='ROAD');
function action(type:string){kind.value=type;form.value={requestKey:requestKey(),type,note:'',...(['LOAD','UNLOAD'].includes(type)?{quantityKg:props.task.loadedKg||props.task.quantityKg}:{}),...(type==='RECEIPT'?{receiver:'',evidenceId:''}:type==='LOAD'?{evidenceId:''}:{})};dialog.value=true;error.value='';}
async function submit(){busy.value=true;try{await client.value.post(`${prefix.value}/tasks/${props.task.id}/events`,form.value);dialog.value=false;emit('changed');ElMessage.success('执行记录已同步');}catch(e){error.value=message(e);}finally{busy.value=false;}}
async function upload(e:Event){const input=e.target as HTMLInputElement,file=input.files?.[0];if(!file)return;busy.value=true;try{const f=new FormData();f.append('file',file);const r=await client.value.post(`${prefix.value}/tasks/${props.task.id}/evidence`,f);form.value.evidenceId=r.data.data.id;emit('changed');ElMessage.success('单据已上传');}catch(e){error.value=message(e);}finally{input.value='';busy.value=false;}}
async function downloadFile(f:any){try{const r=await client.value.get(`${prefix.value}/evidence/${f.id}`,{responseType:'blob'});download(r.data,f.name,f.mime);}catch(e){error.value=message(e);}}
async function report(){busy.value=true;try{await client.value.post(`${prefix.value}/tasks/${props.task.id}/issues`,issue.value);issueDialog.value=false;issue.value={type:'OTHER',description:''};emit('changed');ElMessage.success('异常已上报调度');}catch(e){error.value=message(e);}finally{busy.value=false;}}
async function resolve(i:any){try{const r=await ElMessageBox.prompt('请记录原因与处理结果','处理异常',{inputValidator:v=>v?.trim()?.length>=2||'请填写处理结果'});await api.post(`/fulfillment/issues/${i.id}/resolve`,{resolution:r.value});emit('changed');}catch(e:any){if(e!=='cancel'&&e!=='close')error.value=message(e);}}
function position(){busy.value=true;navigator.geolocation.getCurrentPosition(async p=>{form.value={requestKey:requestKey(),type:'POSITION',latitude:p.coords.latitude,longitude:p.coords.longitude,note:'浏览器定位'};await submit();},()=>{busy.value=false;error.value='无法获取位置，请检查浏览器定位权限。其他节点仍可继续反馈。';},{timeout:10000});}
function payload(e:any){return typeof e.payload==='string'?JSON.parse(e.payload):e.payload;}
</script>
<template><div class="execution"><el-alert v-if="error" :title="error" type="error"/><div class="execution-head"><h3>{{task.businessNo}}</h3><el-tag :type="task.status==='COMPLETED'?'success':'info'">{{label(task.status)}}</el-tag></div><p v-if="task.segment?.origin" class="route-line">{{task.segment.origin}} → {{task.segment.destination}}</p><p v-if="task.boxNo">关联集装箱：{{task.boxNo}}</p><div class="execution-stats"><span>任务量 <b>{{ton(task.quantityKg)}}</b></span><span>装货 <b>{{task.loadedKg?ton(task.loadedKg):'待反馈'}}</b></span><span>卸货 <b>{{task.unloadedKg?ton(task.unloadedKg):'待反馈'}}</b></span></div><p v-if="task.resource" class="muted">{{task.resource}}</p>
<div class="execution-actions"><el-button v-if="canExecute&&next[task.status]" type="primary" :loading="busy" @click="action(next[task.status])">{{eventLabel(next[task.status])}}</el-button><el-button v-if="driver&&task.status==='DISPATCHED'" @click="action('RETURN')">信息有误</el-button><el-button v-if="canExecute&&task.status==='IN_TRANSIT'" :loading="busy" @click="position">记录当前位置</el-button><el-button v-if="(driver||editable)&&!['COMPLETED','CANCELLED','RETURNED'].includes(task.status)" @click="issueDialog=true">上报异常</el-button></div>
<div v-for="i in task.issues" :key="i.id" class="issue-row"><div><el-tag :type="i.status==='OPEN'?'warning':'success'">{{label(i.status)}}</el-tag> {{i.description}}<p v-if="i.resolution">处理结果：{{i.resolution}}</p></div><el-button v-if="editable&&!driver&&i.status==='OPEN'" link type="primary" @click="resolve(i)">处理异常</el-button></div>
<h4>执行时间线</h4><el-timeline v-if="task.events?.length"><el-timeline-item v-for="e in task.events" :key="e.id" :timestamp="date(e.createdAt)"><strong>{{eventLabel(e.type)}}</strong><p v-if="payload(e).quantityKg">数量 {{ton(payload(e).quantityKg)}}</p><p v-if="payload(e).receiver">签收人 {{payload(e).receiver}}</p><p v-if="payload(e).note">{{payload(e).note}}</p><small v-if="payload(e).latitude">位置 {{payload(e).latitude.toFixed(5)}}, {{payload(e).longitude.toFixed(5)}}</small></el-timeline-item></el-timeline><p v-else class="muted">等待首个执行反馈</p>
<h4>单据与回单</h4><div v-if="task.evidence?.length" class="evidence-list"><el-button v-for="f in task.evidence" :key="f.id" link type="primary" @click="downloadFile(f)">{{f.name}} · {{date(f.createdAt)}}</el-button></div><p v-else class="muted">暂无上传单据</p>
<el-dialog v-model="dialog" :title="eventLabel(kind)" width="520px" append-to-body><el-alert v-if="error" :title="error" type="error"/><el-form label-position="top"><el-form-item v-if="['LOAD','UNLOAD'].includes(kind)" label="实际重量（kg）" required><el-input-number v-model="form.quantityKg" :min="1" :max="task.quantityKg" :precision="0"/></el-form-item><el-form-item v-if="kind==='RECEIPT'" label="签收人" required><el-input v-model="form.receiver"/></el-form-item><template v-if="['LOAD','RECEIPT'].includes(kind)"><el-form-item :label="kind==='LOAD'?'装货凭证':'签收回单'" required><input type="file" accept=".pdf,.png,.jpg,.jpeg" aria-label="上传任务单据" @change="upload"/><p class="muted">支持 PDF、PNG、JPG，单份不超过 8 MB。</p></el-form-item><el-tag v-if="form.evidenceId" type="success">已选择上传凭证</el-tag></template><el-form-item :label="kind==='RETURN'?'信息有误原因':'备注 / 数量偏差原因'" :required="kind==='RETURN'"><el-input v-model="form.note" type="textarea" :rows="3" maxlength="2000"/></el-form-item><p v-if="!['RETURN','LOAD','UNLOAD','RECEIPT'].includes(kind)" class="muted">确认完成“{{eventLabel(kind)}}”后，记录将同步给调度和贸易方。</p></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="busy" @click="submit">确认提交</el-button></template></el-dialog>
<el-dialog v-model="issueDialog" title="上报运输异常" width="500px" append-to-body><el-alert v-if="error" :title="error" type="error"/><el-form label-position="top"><el-form-item label="异常类型"><el-select v-model="issue.type"><el-option v-for="o in [['VEHICLE','车辆故障'],['ROAD','道路受阻'],['WAITING','装卸等待'],['CARGO','货物问题'],['CONTACT','联系异常'],['INFORMATION','信息有误'],['OTHER','其他']]" :key="o[0]" :label="o[1]" :value="o[0]"/></el-select></el-form-item><el-form-item label="情况与影响" required><el-input v-model="issue.description" type="textarea" :rows="4" maxlength="2000"/></el-form-item></el-form><template #footer><el-button @click="issueDialog=false">取消</el-button><el-button type="primary" :loading="busy" @click="report">提交异常</el-button></template></el-dialog></div></template>
<style scoped>.execution-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.execution-head h3{font-size:16px}.route-line{line-height:1.8;margin:14px 0}.execution-stats{display:flex;flex-wrap:wrap;gap:20px;font-size:12px;padding:18px 0}.execution-stats b{display:block;font-size:16px;margin-top:6px}.execution-actions{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}.execution-actions .el-button{margin:0}.execution h4{margin:24px 0 20px;font-size:14px}.execution p{font-size:13px;line-height:1.8}.execution .el-timeline{padding-left:4px}.issue-row{padding:14px;background:#fffbf0;display:flex;justify-content:space-between;gap:12px;font-size:13px;margin:10px 0;border-radius:6px}.evidence-list{display:flex;flex-direction:column;align-items:flex-start;gap:12px}.evidence-list .el-button{margin:0;white-space:normal;height:auto;text-align:left}</style>
