<script setup lang="ts">
import {ref,watch} from 'vue';
import {useMap} from '../use-map';
import {loadMapPlugins} from '../amap';
import MapLoadStatus from './MapLoadStatus.vue';
import {date,label} from '../fulfillment';
const props=defineProps<{tasks:any[];detail?:any;replayPoint?:any}>();const emit=defineEmits(['select','ready']);
const container=ref<HTMLElement>(),node=ref<any>(),planned=ref(true),actual=ref(true),modes=ref(['ROAD','RAIL','WATER']);
let map:any,api:any,overlays:any[]=[],cluster:any,replayMarker:any,clusterLoading=false;
const colors:Record<string,string>={ROAD:'#2f80ed',RAIL:'#805ad5',WATER:'#14a4b4'};
const {loading,ready,error,tilesLoading,slowTiles,interactiveMs,tilesMs,init}=useMap(container,{zoom:5,center:[113.8,34.8],mapStyle:'amap://styles/normal',features:['bg','road'],showLabel:true},{
 created(instance,amap){map=instance;api=amap;render();fit();},ready:()=>emit('ready'),
 disposed(){cluster?.setMap(null);cluster=null;replayMarker=null;overlays=[];map=undefined;clusterLoading=false;}
},'RT');
function marker(point:any,text:string,color:string,click:()=>void,title:string){const button=document.createElement('button');button.type='button';button.className='tracking-marker';button.textContent=text;button.style.background=color;button.setAttribute('aria-label',title);const shift=/^\d+[起终]$/.test(text)||text==='站'?new api.Pixel(0,-32):text==='节点'?new api.Pixel(32,0):new api.Pixel(0,0);const m=new api.Marker({offset:shift,position:[point.lng??point.longitude,point.lat??point.latitude],content:button,anchor:'center',title,zIndex:120});m.on('click',click);overlays.push(m);return m;}
function render(){if(!map||!ready.value)return;map.remove(overlays);overlays=[];cluster?.setMap(null);cluster=null;replayMarker?.setMap(null);replayMarker=null;
 const visible=props.tasks.filter(t=>modes.value.includes(t.mode)&&t.currentPosition&&t.id!==props.detail?.id);if(visible.length>30&&api.MarkerCluster){cluster=new api.MarkerCluster(map,visible.map(t=>({lnglat:[t.currentPosition.longitude,t.currentPosition.latitude],taskId:t.id})),{gridSize:70,maxZoom:12,renderMarker:(context:any)=>{const position=context.marker.getPosition();const t=visible.find(t=>Math.abs(t.currentPosition.longitude-position.getLng())<.00001&&Math.abs(t.currentPosition.latitude-position.getLat())<.00001);if(!t)return;const button=document.createElement('button');button.className='tracking-marker';button.textContent=label(t.mode).slice(0,1);button.style.background=colors[t.mode];button.setAttribute('aria-label',t.businessNo);context.marker.setContent(button);context.marker.on('click',()=>emit('select',t.id));}});}else for(const t of visible){marker(t.currentPosition,label(t.mode).slice(0,1),colors[t.mode],()=>emit('select',t.id),t.businessNo);}
 if(visible.length>30&&!api.MarkerCluster&&!clusterLoading){const current=map;clusterLoading=true;void loadMapPlugins(api,['AMap.MarkerCluster']).then(()=>{if(map===current&&ready.value)render();}).catch(()=>undefined).finally(()=>{clusterLoading=false;});}
 const d=props.detail;const nodeKeys=new Set<string>();if(d){if(planned.value)for(const s of d.segments||[]){if(!modes.value.includes(s.mode))continue;if(s.geometry?.coordinates?.length>=3){const line=new api.Polyline({path:s.geometry.coordinates,strokeColor:colors[s.mode],strokeWeight:s.sequence===d.segment?5:3,strokeOpacity:.65,strokeStyle:s.mode==='ROAD'?'solid':'dashed',strokeDasharray:s.mode==='RAIL'?[10,6]:[3,6],zIndex:40});line.on('click',()=>node.value={name:`第 ${s.sequence} 程 · ${label(s.mode)}`,source:s.routeProfile==='AMAP_DRIVING_GENERAL'?'通用道路参考路线':s.geometry.source,updatedAt:s.geometry.queriedAt});overlays.push(line);}for(const [i,p] of [s.origin,s.destination].entries())if(Number.isFinite(p?.lng)&&Number.isFinite(p?.lat)&&!nodeKeys.has(`${p.lng},${p.lat}`)){nodeKeys.add(`${p.lng},${p.lat}`);marker(p,`${s.sequence}${i?'终':'起'}`,colors[s.mode],()=>node.value=p,p.name);}}
 if(actual.value&&modes.value.includes(d.mode)){let batch:any[]=[];const flush=()=>{if(batch.length>1)overlays.push(new api.Polyline({path:batch.map(p=>[p.longitude,p.latitude]),strokeColor:'#e52b2f',strokeWeight:5,strokeOpacity:.95,showDir:true,zIndex:80}));batch=[];};for(const p of d.trajectory||[]){if(p.gapBefore)flush();batch.push(p);}flush();for(const o of d.timeline||[])if(o.node&&Number.isFinite(o.node.lng))marker(o.node,'站',colors.RAIL,()=>node.value={...o.node,source:o.sourceSystem,updatedAt:o.at},o.nodeName);}
 if(d.currentPosition&&modes.value.includes(d.mode)){const p=d.currentPosition;marker(p,d.positionStatus==='SIMULATED'?'参考':'位置','#e52b2f',()=>node.value={name:d.asset||d.businessNo,source:p.sourceSystem,updatedAt:p.observedAt,lng:p.longitude,lat:p.latitude,dataQuality:p.dataQuality},d.businessNo);}
 if(d.currentNode?.node&&modes.value.includes(d.mode)){const o=d.currentNode;marker(o.node,'节点','#e52b2f',()=>node.value={...o.node,source:o.sourceSystem,updatedAt:o.observedAt},o.nodeName);}
 }
 map.add(overlays);updateReplay();}
function updateReplay(){if(!map||!ready.value)return;if(!props.replayPoint){replayMarker?.setMap(null);replayMarker=null;return;}const p=props.replayPoint;if(!replayMarker){const button=document.createElement('span');button.className='replay-marker';button.textContent='▶';replayMarker=new api.Marker({position:[p.longitude,p.latitude],content:button,anchor:'center',zIndex:150});map.add(replayMarker);}else replayMarker.setPosition([p.longitude,p.latitude]);}
function fit(){if(!map||!ready.value||!container.value?.clientWidth)return;if(overlays.length)map?.setFitView(overlays,true,[110,60,80,60]);else if(props.tasks.some(t=>t.currentPosition))map?.setCenter([props.tasks.find(t=>t.currentPosition).currentPosition.longitude,props.tasks.find(t=>t.currentPosition).currentPosition.latitude]);}
watch(()=>[props.tasks,props.detail,planned.value,actual.value,modes.value],render,{deep:true});watch(()=>props.detail?.id,()=>{node.value=null;render();fit();});watch(()=>props.replayPoint,updateReplay);defineExpose({fit});
</script>
<template><div class="tracking-map" :data-map-ready="ready" :data-map-interactive-ms="interactiveMs" :data-map-tiles-ms="tilesMs"><div ref="container" class="tracking-map-canvas" aria-label="高德全程跟踪地图"/><MapLoadStatus :loading="loading" :ready="ready" :error="error" :tiles-loading="tilesLoading" :slow-tiles="slowTiles" @retry="init"/><template v-if="ready&&!error"><div class="tracking-map-controls"><el-checkbox v-model="planned">计划路线</el-checkbox><el-checkbox v-model="actual">采集轨迹</el-checkbox><el-button size="small" @click="fit">适配全程</el-button></div><div class="tracking-map-legend"><el-checkbox-group v-model="modes"><el-checkbox v-for="m in ['ROAD','RAIL','WATER']" :key="m" :value="m"><i :class="m" :style="{borderColor:colors[m]}"/>{{label(m)}}</el-checkbox></el-checkbox-group><span>红线：采集点连线 · 数据断点不连接</span></div><div v-if="node" class="tracking-node" role="status"><strong>{{node.name}}</strong><span v-if="node.lng">{{node.lng}}, {{node.lat}} · GCJ-02</span><span>{{node.source||'内部节点'}} · {{date(node.updatedAt||node.verifiedAt)}}</span><el-button link @click="node=null">关闭</el-button></div><div v-if="!tilesLoading" class="tracking-map-source">高德在线底图 · 业务数据 · 无几何区段仅显示节点</div></template></div></template>
<style scoped>.tracking-map{position:relative;height:100%;min-height:470px;background:var(--page-bg);overflow:hidden}.tracking-map-canvas{position:absolute;inset:0}.tracking-map-controls{position:absolute;top:12px;left:12px;right:50px;display:flex;gap:12px;align-items:center;background:#fffffff2;border:1px solid var(--border);padding:4px 12px;border-radius:6px}.tracking-map-controls :deep(.el-checkbox){margin:0}.tracking-map-legend{position:absolute;left:12px;bottom:42px;background:#fffffff2;padding:8px 12px;border-radius:6px;font-size:11px;color:var(--text-secondary)}.tracking-map-legend :deep(.el-checkbox){margin-right:12px;height:26px}.tracking-map-legend :deep(.el-checkbox__label){font-size:11px;padding-left:4px}.tracking-map-legend i{display:inline-block;width:14px;border-top:2px solid;margin-right:5px}.tracking-map-legend .RAIL{border-top-style:dashed}.tracking-map-legend .WATER{border-top-style:dotted}.tracking-map-legend>span{display:block;font-size:10px}.tracking-map-source{position:absolute;bottom:10px;right:10px;background:#ffffffe6;padding:4px 8px;color:var(--text-secondary);font-size:10px}.tracking-node{position:absolute;top:68px;left:12px;padding:14px;background:var(--surface);border:1px solid var(--border);border-radius:6px;display:flex;flex-direction:column;gap:7px;max-width:80%;font-size:11px}.tracking-node strong{font-size:13px}</style>
<style>.tracking-marker{min-width:28px;height:28px;padding:0 6px;border:2px solid white;color:white;border-radius:14px;font-size:10px;box-shadow:0 1px 5px #263c5440}.tracking-marker:hover{filter:brightness(.85)}.replay-marker{display:grid;place-items:center;width:30px;height:30px;border:3px solid white;background:#e52b2f;color:white;border-radius:50%;box-shadow:0 0 0 4px #e52b2f22}</style>
