<script setup lang="ts">
import {ref,computed,watch,onBeforeUnmount} from 'vue';
import {Play,Pause,RotateCcw,X,Truck,Ship,TrainFront} from 'lucide-vue-next';
import {date} from '../fulfillment';
import {replayBounds,validTrack} from '../tracking-motion';
const props=defineProps<{assets:any[]}>(),emit=defineEmits(['time','close']);
const chosen=ref<string[]>(props.assets.filter(a=>validTrack(a).length>1).map(a=>a.id)),playing=ref(false),speed=ref(1),time=ref(0),expanded=ref(false);
const available=computed(()=>props.assets.filter(a=>validTrack(a).length>1)),selected=computed(()=>available.value.filter(a=>chosen.value.includes(a.id))),bounds=computed(()=>replayBounds(selected.value));
const ratio=computed({get:()=>bounds.value?Math.round((time.value-bounds.value.start)/Math.max(1,bounds.value.end-bounds.value.start)*1000):0,set:(v:number)=>{playing.value=false;time.value=bounds.value?bounds.value.start+(bounds.value.end-bounds.value.start)*v/1000:0;}});
let frame=0,last=0;
watch(bounds,b=>{playing.value=false;time.value=b?.start||0;},{immediate:true});
watch([time,chosen],()=>emit('time',{at:time.value,ids:chosen.value}),{immediate:true,deep:true});
function tick(now:number){if(playing.value&&bounds.value){if(last){time.value=Math.min(bounds.value.end,time.value+(now-last)*(bounds.value.end-bounds.value.start)/90000*speed.value);if(time.value>=bounds.value.end)playing.value=false;}last=now;}else last=0;frame=requestAnimationFrame(tick);}
frame=requestAnimationFrame(tick);onBeforeUnmount(()=>cancelAnimationFrame(frame));
function play(){if(!bounds.value)return;if(time.value>=bounds.value.end)time.value=bounds.value.start;playing.value=!playing.value;}
</script>
<template><section class="tracking-replay" aria-label="运单轨迹回放"><header><div><b>轨迹回放</b><small>{{new Set(available.filter(a=>a.mode==='ROAD').map(a=>a.title)).size}} 辆车 · {{available.filter(a=>a.mode==='ROAD').length}} 车次 · {{available.filter(a=>a.mode==='WATER').length}} 船次 · {{available.filter(a=>a.mode==='RAIL').length}} 铁路任务</small></div><el-button size="small" @click="expanded=!expanded">回放要素 {{chosen.length}} / {{available.length}}</el-button><button aria-label="关闭轨迹回放" @click="emit('close')"><X :size="16"/></button></header><div v-if="expanded" class="replay-pick"><el-checkbox-group v-model="chosen"><el-checkbox v-for="a in available" :key="a.id" :value="a.id"><component :is="a.mode==='ROAD'?Truck:a.mode==='WATER'?Ship:TrainFront" :size="13"/>{{a.title}}<small v-if="a.mode==='ROAD'"> · {{a.businessNo}}</small></el-checkbox></el-checkbox-group><el-button link @click="chosen=available.map(a=>a.id)">全部选择</el-button></div><div v-if="bounds" class="replay-main"><el-button type="primary" circle :aria-label="playing?'暂停轨迹回放':'播放轨迹回放'" @click="play"><Pause v-if="playing" :size="16"/><Play v-else :size="16"/></el-button><button aria-label="重新回放" @click="playing=false;time=bounds.start"><RotateCcw :size="16"/></button><div class="replay-timeline"><b>{{date(new Date(time).toISOString())}}</b><el-slider v-model="ratio" :max="1000" :show-tooltip="false" aria-label="轨迹回放进度"/><div><small>{{date(new Date(bounds.start).toISOString())}}</small><small>{{date(new Date(bounds.end).toISOString())}}</small></div></div><select v-model="speed" aria-label="回放速度"><option :value="1">1×</option><option :value="2">2×</option><option :value="4">4×</option><option :value="8">8×</option></select></div><p v-else>请选择至少一个有轨迹的运输要素。</p><footer>按同一时间轴同步回放 · 任务发车前不显示模型 · 数据断点保留</footer></section></template>
<style scoped>.tracking-replay{position:absolute;z-index:16;bottom:16px;left:390px;right:76px;max-width:820px;border:1px solid #dce5ed;background:#fffffff7;border-radius:10px;box-shadow:0 5px 24px #263f5522;padding:12px 16px;color:#344b64}.tracking-replay header{display:flex;align-items:center;gap:10px;font-size:13px}.tracking-replay header>div{margin-right:auto}.tracking-replay header small{font-size:10px;color:#8a97a6;margin-left:12px}.tracking-replay button:not(.el-button){background:none;border:0;cursor:pointer;color:#728398;padding:4px;display:flex;align-items:center}.replay-main{display:flex;gap:12px;align-items:center;margin-top:10px}.replay-timeline{flex:1;min-width:0}.replay-timeline>b{font-size:12px}.replay-timeline :deep(.el-slider){height:26px}.replay-timeline>div:last-child{display:flex;justify-content:space-between;font-size:10px;color:#929fac}.replay-main select{border:1px solid #dfe6ee;border-radius:5px;padding:5px;color:#48607a;background:#fff}.tracking-replay footer{font-size:10px;color:#94a0ae;margin-top:10px}.replay-pick{max-height:145px;overflow:auto;border-bottom:1px solid #e9edf3;padding:8px 0}.replay-pick :deep(.el-checkbox-group){display:grid;grid-template-columns:1fr 1fr}.replay-pick :deep(.el-checkbox__label){display:flex;align-items:center;gap:6px;font-size:11px}.tracking-replay>p{font-size:12px}@media(max-width:1000px){.tracking-replay{left:350px;right:50px}.tracking-replay header small{display:block;margin:4px 0 0}}@media(max-width:760px){.tracking-replay{left:14px;right:14px;bottom:12px}.replay-pick :deep(.el-checkbox-group){grid-template-columns:1fr}.tracking-replay footer{font-size:9px}}</style>
