<script setup lang="ts">
import {ref,watch,nextTick} from 'vue';
import {referencePosition,referenceHeading,referenceChunks} from '../tracking-reference-motion';
import {useMap} from '../use-map';
import MapLoadStatus from './MapLoadStatus.vue';
import {label,ton} from '../fulfillment';
import {isFinished,trackAt,trackChunks,trackHeading,validTrack,prepareTrack} from '../tracking-motion';
const props=defineProps<{assets:any[];segments:any[];nodes:any[];selected?:any;panelOpen:boolean;replayAt?:number;replayIds?:string[];referenceAt?:number}>(),emit=defineEmits(['select','node','ready']);
const canvas=ref<HTMLElement>(),planned=ref(true),actual=ref(true),popupHost=ref<HTMLElement>(),overlayRenders=ref(0);
let map:any,amap:any,info:any,overlays:any[]=[],fitOverlays:any[]=[],labels:any[]=[],labelMarkers:any[]=[],models:any[]=[],replayLines:any[]=[],lastReplayDraw=0,lastReferenceDraw=0,preparedAssets=new Map<string,any>(),renderFrame=0,viewportFrame=0,lastFitKey="";
const colors:Record<string,string>={ROAD:'#2879dc',WATER:'#0b9eac',RAIL:'#7d58bd'};
const modelPaths:Record<string,string>={ROAD:'<rect x="9" y="4" width="14" height="24" rx="3" fill="currentColor"/><path d="M11 9h10v5H11z" fill="#bde4fb"/><path d="M11 17h10v8H11z" fill="#fff" fill-opacity=".85"/><path d="M7 9v5m18-5v5M7 21v4m18-4v4" stroke="#243e58" stroke-width="3"/>',WATER:'<path d="M16 2 26 13 23 27H9L6 13Z" fill="currentColor"/><path d="M16 5v21" stroke="#fff" stroke-width="1.5"/><rect x="11" y="12" width="10" height="9" rx="1.5" fill="#d7f5f8"/><path d="M4 24q3 3 6 0m12 0q3 3 6 0" stroke="currentColor" fill="none" stroke-width="1.5"/>',RAIL:'<rect x="9" y="2" width="14" height="12" rx="4" fill="currentColor"/><rect x="9" y="16" width="14" height="6" rx="1" fill="currentColor"/><rect x="9" y="24" width="14" height="6" rx="1" fill="currentColor"/><path d="M11 7h10v4H11z" fill="#eadffc"/><path d="M7 1v30m18-30v30" stroke="#a79bb4" stroke-width="1"/>'};
const point=(p:any)=>p&&Number.isFinite(p.longitude??p.lng)&&Number.isFinite(p.latitude??p.lat)?[p.longitude??p.lng,p.latitude??p.lat]:null;
const {loading,ready,error,tilesLoading,slowTiles,interactiveMs,tilesMs,init}=useMap(canvas,{zoom:5,center:[119,32],features:['bg','road'],showLabel:true,mapStyle:'amap://styles/normal'},{
 created(instance,api){map=instance;amap=api;popupHost.value=document.createElement('div');info=new amap.InfoWindow({isCustom:true,content:popupHost.value,offset:new amap.Pixel(0,-26),autoMove:true,closeWhenClickMap:false,avoid:[20,20,90,props.panelOpen?400:20]});render();fit();lastFitKey=viewKey();map.on('zoomend',queueViewport);map.on('moveend',queueViewport);if(props.selected)void syncPopup();},
 ready:()=>emit('ready'),disposed(){cancelAnimationFrame(renderFrame);cancelAnimationFrame(viewportFrame);renderFrame=0;viewportFrame=0;info?.close();info=undefined;popupHost.value=undefined;map=undefined;overlays=[];fitOverlays=[];models=[];labelMarkers=[];replayLines=[];lastFitKey='';}
});
function viewKey(){return props.assets.map(a=>a.id).join('|')+';'+props.segments.map(s=>s.id||s.sequence+':'+s.origin?.name+':'+s.destination?.name).join('|')+';'+props.nodes.map(n=>n.id).join('|')+';'+(props.replayAt!=null);}
function queueRender(){if(!ready.value||renderFrame)return;renderFrame=requestAnimationFrame(()=>{renderFrame=0;if(!ready.value)return;render();const key=viewKey();if(key!==lastFitKey){lastFitKey=key;fit();}});}
function queueViewport(){if(!ready.value||viewportFrame)return;viewportFrame=requestAnimationFrame(()=>{viewportFrame=0;if(!ready.value)return;moveModels();layoutLabels();});}
function addMarker(p:any,title:string,text:string,color:string,select:()=>void,progress=false,warning=false){const pos=point(p);if(!pos)return;const el=document.createElement('button');el.type='button';el.className=progress?'gather-marker':'waybill-map-marker'+(warning?' warning':'');el.textContent=text;el.style.setProperty('--marker-color',color);el.setAttribute('aria-label',title);el.addEventListener('click',select);const anchor=new amap.CircleMarker({center:pos,radius:4,fillColor:color,fillOpacity:1,strokeColor:'#fff',strokeWeight:1,zIndex:150});const marker=new amap.Marker({position:pos,content:el,anchor:'bottom-center',zIndex:warning?190:progress?180:160,title});overlays.push(anchor,marker);fitOverlays.push(anchor,marker);labelMarkers.push({pos,marker,width:Math.max(36,text.length*9+24),height:32});}
function layoutLabels(){if(!map||!ready.value)return;labels=[];for(const m of models){if(m.visible){const px=map.lngLatToContainer(m.marker.getPosition()),size=24;labels.push({x:px.x-size/2,y:px.y-size/2,width:size,height:size});}}
 const offsets=[0,-1,1,-2,2,-3,3,-4,4];for(const entry of labelMarkers){const {pos,marker,width,height}=entry,px=map.lngLatToContainer(pos);let dx=0,dy=0,placed=false;for(const row of offsets){for(const column of offsets){const cx=column*(width+18),cy=row*38,x=px.x-width/2+cx,y=px.y-height+cy;if(x<(props.panelOpen?390:15)||x+width>(canvas.value?.clientWidth||1280)-20||y<60||y+height>(canvas.value?.clientHeight||600)-85||labels.some(r=>x<r.x+r.width+5&&x+width+5>r.x&&y<r.y+r.height+5&&y+height+5>r.y))continue;dx=cx;dy=cy;labels.push({x,y,width,height});placed=true;break;}if(placed)break;}marker.setOffset(new amap.Pixel(dx,dy));if(dx||dy){const path=[pos,map.containerToLngLat([px.x+dx,px.y+dy-height/2])];if(!entry.leader){entry.leader=new amap.Polyline({path,strokeColor:'#258357',strokeOpacity:.6,strokeWeight:1,zIndex:90});overlays.push(entry.leader);map.add(entry.leader);}else{entry.leader.setPath(path);entry.leader.show();}}else entry.leader?.hide();}
}
function dot(p:any,title:string,color:string,select:()=>void,radius=5){const pos=point(p);if(!pos)return;const d=new amap.CircleMarker({center:pos,radius,fillColor:color,fillOpacity:.8,strokeColor:'#fff',strokeWeight:2,zIndex:130});d.on('click',select);d.on('mouseover',()=>map.setCursor('pointer'));d.on('mouseout',()=>map.setCursor(''));overlays.push(d);fitOverlays.push(d);}
function model(a:any){const el=document.createElement('button');el.type='button';el.className='transport-model '+a.mode+(a.alerts?.length&&!isFinished(a)?' has-alert':'');el.style.setProperty('--model-color',colors[a.mode]);el.dataset.assetId=a.id;el.dataset.mode=a.mode;el.setAttribute('aria-label',(a.mode==='ROAD'?'车辆 ':a.mode==='WATER'?'船舶 ':'铁路 ')+a.title);el.title=a.title+' · '+(props.replayAt!=null?'轨迹回放':label(a.status))+(a.position?.dataQuality==='INITIALIZATION'?' · 参考位置':'');
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 32 32');svg.setAttribute('aria-hidden','true');svg.innerHTML=modelPaths[a.mode];el.appendChild(svg);
 const name=document.createElement('span');name.className='model-name';name.textContent=a.title;el.appendChild(name);el.addEventListener('click',()=>{const p=props.replayAt==null?referencePosition(a,props.referenceAt??Date.now()):trackAt(preparedAssets.get(a.id)||a,props.replayAt);emit('select',{...a,position:p,replayAt:props.replayAt});});
 const marker=new amap.Marker({position:point(a.position)||point(validTrack(a)[0])||[119,32],content:el,anchor:'center',zIndex:220,title:el.title});overlays.push(marker);fitOverlays.push(marker);models.push({a,marker,el,svg});}

function drawTracks(time?:number){map.remove(replayLines);replayLines=[];if(!actual.value)return;for(const a of props.assets){if(time!=null&&!props.replayIds?.includes(a.id))continue;for(const batch of time!=null?trackChunks(preparedAssets.get(a.id)||a,time):referenceChunks(preparedAssets.get(a.id)||a,props.referenceAt??Date.now())){const line=new amap.Polyline({path:batch.map(point),strokeColor:colors[a.mode],strokeOpacity:isFinished(a)&&time==null?.45:.85,strokeWeight:props.selected?.id===a.id?5:isFinished(a)&&time==null?2:3,strokeStyle:a.mode==='RAIL'?'dashed':'solid',strokeDasharray:[10,6],showDir:a.mode!=='RAIL'&&!(isFinished(a)&&time==null),zIndex:80});line.on('click',()=>emit('select',a));replayLines.push(line);}}map.add(replayLines);}
function moveModels(){const playback=props.replayAt!=null,time=props.referenceAt??Date.now();for(const m of models){const a=preparedAssets.get(m.a.id)||m.a,p=playback?trackAt(a,props.replayAt!):referencePosition(a,time),visible=p&&(!playback||props.replayIds?.includes(a.id));m.visible=!!visible;if(visible){m.marker.show();m.marker.setPosition(point(p));m.svg.style.transform='rotate('+(playback?trackHeading(a,props.replayAt):referenceHeading(a,time))+'deg)';m.el.classList.toggle('selected',props.selected?.id===a.id);m.el.classList.toggle('historical',playback&&!!p.replayFinished);m.el.classList.toggle('gap',!!p.trackGap);m.el.classList.toggle('show-name',map.getZoom()>=7);m.el.dataset.coordinate=point(p)?.join(',');m.el.dataset.displayOffset='0,0';}else m.marker.hide();}syncPopup(false);}
function render(){if(!ready.value||!map)return;overlayRenders.value++;map.remove(overlays);overlays=[];fitOverlays=[];labels=[];models=[];labelMarkers=[];preparedAssets=new Map(props.assets.map(a=>[a.id,prepareTrack(a)]));
 if(planned.value)for(const s of props.segments){const coords=s.geometry?.coordinates;if(Array.isArray(coords)&&coords.length>=3){const line=new amap.Polyline({path:coords,strokeColor:colors[s.mode],strokeWeight:2,strokeOpacity:.22,strokeStyle:'dashed',strokeDasharray:s.mode==='RAIL'?[12,6]:[3,8],zIndex:35});overlays.push(line);fitOverlays.push(line);}}
 const finished=new Map<string,any[]>();
 for(const a of props.assets){if(props.replayAt!=null||!isFinished(a)){if(point(a.position)||validTrack(a).length)model(a);}else {const key=a.mode+'|'+a.stage?.destination;if(!finished.has(key))finished.set(key,[]);finished.get(key)!.push(a);}}
 for(const group of finished.values()){const a=group[0],pos=a.position||validTrack(a).at(-1);dot(pos,label(a.mode)+'已完成 · '+group.length+' 个任务',colors[a.mode],()=>emit('select',a),4);}
 const seen=new Set<string>();for(const s of props.segments)for(const p of [s.origin,s.destination])if(point(p)&&!seen.has(p.name)&&!props.nodes.some(n=>n.isPort&&n.destination===p.name)){seen.add(p.name);dot(p,p.name,colors[s.mode],()=>emit('node',{id:'endpoint:'+s.sequence+':'+p.name,mode:s.mode,destination:p.name,position:p,origin:s.origin.name}),4);}
 for(const n of props.nodes)if(point(n.position)){if(n.isPort&&props.replayAt==null){const text='集港 '+ton(n.collectedKg)+(n.awaitingEvidenceKg?' · 回传 '+ton(n.awaitingEvidenceKg)+' 待核对':'')+' · 发船 '+ton(n.shippedKg);addMarker(n.position,'港口进度 '+n.destination,text,'#258357',()=>emit('node',n),true,n.warnings?.length>0);}else dot(n.position,n.destination,colors[n.mode]||'#258357',()=>emit('node',n),4);}
 map.add(overlays);drawTracks(props.replayAt);moveModels();layoutLabels();
}
async function syncPopup(move=true){if(!ready.value||!info)return;const current=info,instance=map,asset=props.assets.find(a=>a.id===props.selected?.id),pos=point(props.replayAt!=null&&asset?trackAt(preparedAssets.get(asset.id)||asset,props.replayAt):asset?referencePosition(asset,props.referenceAt??Date.now()):props.selected?.position);if(!props.selected||!pos){current.close();return;}await nextTick();if(!ready.value||info!==current||map!==instance)return;if(move)current.open(instance,pos);else if(current.getIsOpen())current.setPosition(pos);}
function fit(all=false){if(!ready.value||!map)return;const active=models.filter(m=>m.visible&&!isFinished(m.a)).map(m=>m.marker),targets=!all&&props.replayAt==null&&active.length?active:[...fitOverlays,...replayLines];if(targets.length)map.setFitView(targets,true,[100,props.replayAt!=null?220:90,props.panelOpen?420:50,80],12);else map.setZoomAndCenter(5,[119,32]);}
watch(()=>props.referenceAt,()=>{if(!ready.value||props.replayAt!=null)return;moveModels();if(props.assets.some(a=>a.movement)&&performance.now()-lastReferenceDraw>2000){drawTracks();lastReferenceDraw=performance.now();}});
watch(()=>[props.assets,props.segments,props.nodes,planned.value,actual.value],queueRender,{deep:true});watch(()=>props.replayAt!=null,queueRender);watch(()=>props.replayIds,()=>{if(ready.value){moveModels();drawTracks(props.replayAt);}},{deep:true});watch(()=>props.replayAt,()=>{if(!ready.value)return;moveModels();if(performance.now()-lastReplayDraw>160){drawTracks(props.replayAt);lastReplayDraw=performance.now();}});watch(()=>props.selected?.id,()=>{if(!ready.value)return;moveModels();drawTracks(props.replayAt);void syncPopup();});watch(()=>props.panelOpen,queueViewport);defineExpose({fit});
</script>
<style>.transport-model{position:relative;width:24px;height:24px;border:1px solid #ffffffdd;border-radius:50%;background:#fff;color:var(--model-color);padding:2px;box-shadow:0 2px 8px #16314f35;cursor:pointer;display:grid;place-items:center}.transport-model svg{width:22px;height:22px;transform-origin:50% 50%}.transport-model .model-name{display:none;position:absolute;top:28px;left:50%;transform:translateX(-50%);background:#fff;border:1px solid #d9e3ec;box-shadow:0 2px 6px #21354e15;padding:3px 6px;border-radius:4px;white-space:nowrap;font-size:10px;color:#38516a}.transport-model.show-name .model-name,.transport-model:hover .model-name,.transport-model:focus-visible .model-name,.transport-model.selected .model-name{display:block}.transport-model .model-count{position:absolute;left:-4px;bottom:-3px;min-width:15px;height:15px;padding:0 3px;display:grid;place-items:center;border:1px solid #fff;border-radius:8px;background:#405d7d;color:#fff;font-size:9px;font-weight:700}.transport-model .model-count[hidden]{display:none}.transport-model.selected{outline:3px solid #ea31394d}.transport-model.has-alert:after{content:'!';position:absolute;right:-3px;top:-3px;width:13px;height:13px;display:grid;place-items:center;border:1px solid #fff;border-radius:50%;background:#e98036;color:#fff;font-size:9px;font-weight:700}.transport-model.historical{width:12px;height:12px;background:var(--model-color);opacity:.65}.transport-model.historical svg{display:none}.transport-model.gap{outline:2px dashed #e6a359}</style>
<template><div class="waybill-map" :data-map-ready="ready" :data-map-interactive-ms="interactiveMs" :data-map-tiles-ms="tilesMs" :data-map-overlay-renders="overlayRenders"><div ref="canvas" class="waybill-map-canvas" aria-label="全程运单可视化地图"/><MapLoadStatus :loading="loading" :ready="ready" :error="error" :tiles-loading="tilesLoading" :slow-tiles="slowTiles" @retry="init"/><div v-if="ready" class="map-tools"><el-checkbox v-model="planned">计划路线</el-checkbox><el-checkbox v-model="actual">运输轨迹</el-checkbox><el-button size="small" @click="fit(false)">聚焦在途</el-button><el-button size="small" @click="fit(true)">全程路线</el-button></div><div v-if="ready&&!selected&&replayAt==null" class="map-key"><span v-for="m in ['ROAD','WATER','RAIL']" :key="m"><i :style="{borderColor:colors[m]}" :class="m"/>{{label(m)}}</span><small>模型：在途 · 小点：已完成</small></div><a v-if="ready&&segments.some(s=>s.geometry?.source==='OPENSTREETMAP_RAIL_INFRASTRUCTURE')" class="geometry-attribution" href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">铁路路网 © OpenStreetMap contributors</a><Teleport v-if="popupHost&&selected" :to="popupHost"><slot name="popup"/></Teleport></div></template>
<style scoped>.waybill-map{isolation:isolate}.waybill-map,.waybill-map-canvas{position:absolute;inset:0}.map-tools{position:absolute;top:16px;right:18px;display:flex;align-items:center;gap:12px;background:#fffffff5;border:1px solid #e4e8ed;box-shadow:0 4px 16px #2435480c;padding:4px 12px;border-radius:8px}.map-tools .el-checkbox{margin:0;font-size:12px}.map-key{position:absolute;bottom:76px;right:18px;padding:10px 14px;border-radius:8px;background:#fffffff2;border:1px solid #e4e8ed;font-size:11px}.map-key span{margin-right:14px}.map-key i{display:inline-block;width:18px;border-top:3px solid;margin-right:5px;vertical-align:middle}.map-key .WATER{border-top-style:dotted}.map-key .RAIL{border-top-style:dashed}.geometry-attribution{position:absolute;bottom:8px;right:68px;font-size:10px;color:#526879;background:#ffffffd9;padding:2px 5px}.map-key small{display:block;color:#7d8895;margin-top:6px}@media(max-width:760px){.map-tools{left:14px;right:14px;top:12px;justify-content:flex-end}.map-key{right:50px;bottom:12px}}</style>
<style>.waybill-map-marker{background:var(--marker-color);border:2px solid #fff;border-radius:6px;color:#fff;padding:6px 9px;font-size:11px;box-shadow:0 3px 10px #16314f33;cursor:pointer;white-space:nowrap}.waybill-map-marker.warning{outline:3px solid #f37f5340}.waybill-map-marker.warning:before{content:'!';font-weight:bold;background:#e34929;border-radius:50%;display:inline-block;margin-right:6px;width:14px}.waybill-map-marker:hover,.waybill-map-marker:focus-visible{outline:3px solid #e42b3440}.gather-marker{background:#fff;border:1px solid var(--marker-color);border-radius:20px;color:var(--marker-color);padding:7px 12px;font-weight:600;font-size:11px;cursor:pointer;box-shadow:0 3px 12px #243d5422;white-space:nowrap}.map-workspace-main{padding:0!important;max-width:none!important;min-height:0!important;height:calc(100dvh - 112px);overflow:hidden}</style>



