const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {PrismaClient}=require('@prisma/client');
const {readAppearance,saveAppearance,savePreset,deletePreset}=require('../server/appearance.cjs');
const initial=require('../server/default-styles.json');

test('shared appearance persists, rejects stale writes and manages shared presets',async t=>{
 const dir=path.resolve(__dirname,'../../.local/tests');fs.mkdirSync(dir,{recursive:true});
 const filename=path.join(dir,`cockpit-appearance-${process.pid}.db`),url='file:'+filename.replace(/\\/g,'/');
 let db=new PrismaClient({datasourceUrl:url});
 t.after(async()=>{await db.$disconnect();for(const suffix of ['','-journal','-wal','-shm'])if(fs.existsSync(filename+suffix))fs.unlinkSync(filename+suffix);});
 let state=await readAppearance(db);
 assert.deepEqual(state.styles,{platform:initial.platform,chain:initial.chain});
 assert.equal(state.presets[0].name,'one');
 assert.equal(state.revision,0);
 const legacy=JSON.parse(JSON.stringify({styles:state.styles,presets:state.presets}));
 for(const view of ['platform','chain'])for(const key of ['routeLimit','labelLimit','autoCruise'])delete legacy.styles[view][key];
 await db.$executeRawUnsafe('UPDATE "CockpitAppearance" SET "payload"=? WHERE "id"=?',JSON.stringify(legacy),'global');
 const upgraded=await readAppearance(db);assert.deepEqual(upgraded.styles,state.styles);assert.equal(upgraded.revision,0,'New map controls must not reset saved shared styles');
 const platform={...state.styles.platform,text:'#fff000',gap:16};
 state=await saveAppearance(db,{view:'platform',style:platform,both:false,expectedRevision:state.revision});
 assert.deepEqual(state.styles.platform,platform);assert.deepEqual(state.styles.chain,initial.chain);
 await assert.rejects(saveAppearance(db,{view:'chain',style:initial.chain,both:false,expectedRevision:0}),e=>e.appearanceCode==='CONFLICT');
 await assert.rejects(saveAppearance(db,{view:'platform',style:{...platform,mapHeight:9},both:false,expectedRevision:state.revision}),e=>e.appearanceCode==='INVALID');
 await assert.rejects(saveAppearance(db,{view:'platform',style:{...platform,text:'url(javascript:1)'},both:false,expectedRevision:state.revision}),e=>e.appearanceCode==='INVALID');
 state=await savePreset(db,{name:'检查预设',view:'platform',style:platform,expectedRevision:state.revision});
 const id=state.presets.find(p=>p.name==='检查预设').id;
 state=await savePreset(db,{name:'检查预设',view:'chain',style:initial.chain,expectedRevision:state.revision});
 assert.equal(state.presets.find(p=>p.name==='检查预设').id,id);assert.equal(state.presets.length,2);
 assert.deepEqual(state.styles.platform,platform,'Saving a preset must not publish its draft');
 state=await deletePreset(db,id,{expectedRevision:state.revision});
 assert.equal(state.presets.length,1);assert.deepEqual(state.styles.platform,platform);
 const revision=state.revision;
 const race=await Promise.allSettled(['platform','chain'].map(view=>saveAppearance(db,{view,style:{...state.styles[view],gap:18},both:false,expectedRevision:revision})));
 assert.equal(race.filter(r=>r.status==='fulfilled').length,1);assert.equal(race.filter(r=>r.status==='rejected'&&r.reason.appearanceCode==='CONFLICT').length,1);
 state=await readAppearance(db);assert.equal(state.revision,revision+1);
 state=await saveAppearance(db,{view:'chain',style:initial.chain,both:true,expectedRevision:state.revision});
 assert.deepEqual(state.styles.platform,state.styles.chain);
 for(let i=1;i<12;i++)state=await savePreset(db,{name:`预设${i}`,view:'chain',style:initial.chain,expectedRevision:state.revision});
 await assert.rejects(savePreset(db,{name:'超出容量',view:'chain',style:initial.chain,expectedRevision:state.revision}),e=>e.appearanceCode==='INVALID');
 await db.$disconnect();db=new PrismaClient({datasourceUrl:url});
 assert.deepEqual(await readAppearance(db),state,'Settings must survive service restarts');
});
