const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const base=process.env.COCKPIT_URL||'http://127.0.0.1:3002';
const out=path.resolve('jiashicang/acceptance');
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
(async()=>{
 fs.mkdirSync(out,{recursive:true});
 const browser=await chromium.launch({channel:'msedge',headless:process.env.PW_HEADLESS==='true'});
 const results=[],errors=[];
 try{
  const context=await browser.newContext({viewport:{width:1920,height:1080}});
  await context.addInitScript(()=>{
   window.__geometryUploads=0;
   for(const kind of ['WebGLRenderingContext','WebGL2RenderingContext']){
    const p=window[kind]?.prototype;if(!p)continue;
    const original=p.bufferData;p.bufferData=function(...args){window.__geometryUploads++;return original.apply(this,args);};
   }
  });
  const page=await context.newPage(),requests={reference:0,overview:0};
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{if(/transport-network.*\.json/.test(r.url()))requests.reference++;if(r.url().includes('/api/cockpit/overview'))requests.overview++;});
  page.setDefaultTimeout(15000);
  await page.goto(base+'/cockpit?view=platform');
  await page.locator('.cc-panel').nth(5).waitFor();
  await page.waitForFunction(()=>document.querySelector('.cc-map-tools>button>span')?.textContent==='4');
  const canvas=await page.locator('.cc-map-canvas canvas').elementHandle();
  assert.ok(canvas,'WebGL must be available for the main desktop checks');
  await page.screenshot({path:path.join(out,'network-platform-1920.png')});
  async function selectFirst(){await page.getByRole('button',{name:/^运输通道/}).click();await page.locator('.cc-corridor-option').first().click();await page.locator('.cc-route-detail').waitFor();}
  await selectFirst();
  assert.match(await page.locator('.cc-route-detail').innerText(),/公主岭站.*南沙港/);
  await page.getByRole('button',{name:'路线来源',exact:true}).click();
  assert.match(await page.locator('.cc-route-sources').innerText(),/港区衔接段未包含/);
  await page.getByRole('button',{name:'路线来源',exact:true}).click();
  await page.getByRole('button',{name:'路线回放',exact:true}).click();
  await page.waitForFunction(()=>Number(document.querySelector('.cc-explorer').dataset.progress)>1.5);
  const uploads=await page.evaluate(()=>window.__geometryUploads),overviewRequests=requests.overview;
  await wait(1100);
  assert.equal(await page.evaluate(()=>window.__geometryUploads),uploads,'Position ticks must reuse geometry');
  assert.equal(requests.overview,overviewRequests,'Playback must not poll business APIs per frame');
  await page.getByRole('button',{name:'暂停回放',exact:true}).click();
  const stopped=await page.locator('.cc-explorer').getAttribute('data-progress');await wait(450);
  assert.equal(await page.locator('.cc-explorer').getAttribute('data-progress'),stopped);
  const progress=page.getByRole('slider',{name:'路线回放进度'});
  await progress.evaluate(el=>{el.value=Number(el.max)*.6;el.dispatchEvent(new Event('input',{bubbles:true}));});
  await page.waitForFunction(()=>document.querySelector('.cc-route-player strong')?.textContent.includes('水运'));
  await page.getByRole('combobox',{name:'路线回放速度'}).selectOption('4');
  await page.getByRole('button',{name:'继续回放',exact:true}).click();
  await page.screenshot({path:path.join(out,'network-playback-1920.png')});
  await progress.evaluate(el=>{el.value=el.max;el.dispatchEvent(new Event('input',{bubbles:true}));});
  await page.waitForFunction(()=>document.querySelector('.cc-route-player strong')?.textContent==='路线回放完成');
  await page.getByRole('button',{name:'重新播放路线'}).click();
  await page.waitForFunction(()=>Number(document.querySelector('.cc-explorer').dataset.progress)<3);
  await page.getByRole('button',{name:'图层',exact:true}).click();
  await page.locator('.cc-map-mode-choices button').filter({hasText:'公路'}).click();
  assert.equal(await page.locator('.cc-route-player').count(),0,'Changing route visibility exits playback');
  assert.equal(await page.locator('.cc-map-mode-choices button').filter({hasText:'公路'}).getAttribute('aria-pressed'),'false');
  await page.locator('.cc-map-mode-choices button').filter({hasText:'公路'}).click();
  for(const name of ['发运分布','到达分布','风险节点','联运网络']){await page.getByRole('button',{name,exact:true}).click();assert.match(await page.getByRole('button',{name,exact:true}).getAttribute('class'),/active/);}
  await page.getByRole('button',{name:'关闭图层设置'}).click();
  const narrowed=page.waitForResponse(r=>r.url().includes('/api/cockpit/overview?')&&r.url().includes('origin=')&&r.status()===200);
  await page.getByRole('button',{name:'筛选此通道'}).click();
  const scoped=(await (await narrowed).json()).data;
  assert.equal(scoped.businesses.length,4);assert.equal(scoped.metrics.transportedKg,5261500);
  await page.waitForFunction(()=>document.querySelector('.cc-explorer').dataset.scoped==='true');
  const restored=page.waitForResponse(r=>r.url().includes('/api/cockpit/overview?')&&!r.url().includes('origin=')&&r.status()===200);
  await page.getByRole('button',{name:'取消地图统计筛选'}).click();await restored;
  await page.getByRole('button',{name:'高亮 公水',exact:true}).click();await page.locator('.cc-map-highlight').waitFor();
  assert.match(await page.locator('.cc-map-highlight').innerText(),/公水/);
  await page.getByRole('button',{name:'取消图表高亮'}).click();
  await page.getByRole('button',{name:'巡航',exact:true}).click();await wait(700);
  assert.equal(await page.getByRole('button',{name:'巡航',exact:true}).getAttribute('aria-pressed'),'true');
  await page.mouse.move(960,430);await page.mouse.wheel(0,60);
  assert.equal(await page.getByRole('button',{name:'巡航',exact:true}).getAttribute('aria-pressed'),'false');
  await page.getByRole('button',{name:'重置地图视角'}).click();await wait(1000);
  await page.locator('.cc-map-label').first().click();
  assert.match(await page.locator('.cc-route-detail').innerText(),/联运节点/);
  assert.equal(await page.getByRole('button',{name:'筛选此节点'}).count(),1);
  await page.getByRole('button',{name:'关闭地图详情'}).click();
  results.push('desktop WebGL, true polyline playback, pause/seek/speed/restart, geometry reuse, layers, scoped statistics, node selection and cruise');

  await page.getByRole('tab',{name:'一粮一链',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.cc-root').dataset.view==='chain');
  assert.equal(await canvas.evaluate(el=>el===document.querySelector('.cc-map-canvas canvas')),true,'Tabs reuse the same map');
  await page.locator('[data-chart=treemap] [role=button]').first().click();
  assert.match(await page.locator('.cc-map-highlight').innerText(),/站/);
  await page.getByRole('button',{name:'取消图表高亮'}).click();
  await page.locator('[data-chart=bubbles] [role=button]').first().press('Enter');await page.locator('.cc-map-highlight').waitFor();
  await page.getByRole('button',{name:'取消图表高亮'}).click();
  await page.locator('[data-chart=heatmap] [role=button]').first().click();await page.locator('.cc-map-highlight').waitFor();
  await page.getByRole('button',{name:'取消图表高亮'}).click();
  await page.locator('[data-chart=sankey] [aria-label="高亮 公水"]').click();await page.locator('.cc-map-highlight').waitFor();
  await page.getByRole('button',{name:'取消图表高亮'}).click();
  const grainResponse=page.waitForResponse(r=>r.url().includes('/api/cockpit/overview?')&&r.url().includes('grain=')&&r.status()===200);
  await page.locator('.cc-grain-structure-panel .cc-stat-legend [role=button]').first().click();
  const grainData=(await (await grainResponse).json()).data;assert.equal(new Set(grainData.businesses.map(b=>b.grain)).size,1);
  const allGrains=page.waitForResponse(r=>r.url().includes('/api/cockpit/overview?')&&!r.url().includes('grain=')&&r.status()===200);
  await page.getByRole('button',{name:'全部粮种',exact:true}).click();await allGrains;
  await page.screenshot({path:path.join(out,'network-chain-1920.png')});
  for(const view of ['platform','chain']){
   await page.getByRole('tab',{name:view==='platform'?'平台运营':'一粮一链',exact:true}).click();
   await page.setViewportSize({width:1366,height:768});await wait(900);
   assert.equal(await page.locator('.cc-panel').count(),6);
   assert.ok(!(await page.locator('body').innerText()).match(/演示|模拟|实时定位/));
   const boxes=await page.locator('.cc-side .cc-panel').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom};}));
   assert.ok(boxes.every(r=>r.x>=0&&r.y>=0&&r.right<=1367&&r.bottom<=769));
   await selectFirst();await page.getByRole('button',{name:'路线回放',exact:true}).click();
   const detail=await page.locator('.cc-route-detail').boundingBox(),player=await page.locator('.cc-route-player').boundingBox(),map=await page.locator('.cc-map-section').boundingBox();
   assert.ok(detail.x>=map.x&&detail.x+detail.width<=map.x+map.width+1);
   assert.ok(player.x>=map.x&&player.x+player.width<=map.x+map.width+1);
   await page.screenshot({path:path.join(out,`network-${view}-1366.png`)});
   await page.keyboard.press('Escape');
  }
  assert.equal(requests.reference,1,'Reference geometry is loaded once across tabs and filters');
  await page.getByRole('button',{name:'大屏风格设置'}).click();
  await page.getByRole('textbox',{name:'搜索风格参数'}).fill('线路数量');
  assert.match(await page.locator('.cc-settings').innerText(),/总览线路数量/);
  await page.getByRole('button',{name:'取消',exact:true}).click();
  results.push('chain chart linking, keyboard selection, grain filtering, both 1366×768 layouts and shared style controls');
  await page.getByRole('link',{name:'首页',exact:true}).click();
  assert.equal(await page.locator('.cc-map-canvas canvas').count(),0);
  await page.goto(base+'/cockpit?view=chain');await page.locator('.cc-panel').nth(5).waitFor();
  assert.equal(await page.locator('.cc-map-canvas canvas').count(),1);
  await context.close();

  const fallback=await browser.newContext({viewport:{width:1366,height:768}});
  await fallback.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...rest){return String(type).includes('webgl')?null:get.call(this,type,...rest);};});
  const flat=await fallback.newPage();flat.on('pageerror',e=>errors.push(e.message));
  let fail=true;
  await flat.route('**/transport-network*.json',route=>fail?route.fulfill({status:503,body:'unavailable'}):route.continue());
  await flat.goto(base+'/cockpit?view=chain');await flat.locator('.cc-flat-notice').waitFor();await flat.locator('.cc-network-error').waitFor();
  fail=false;await flat.getByRole('button',{name:'重新加载',exact:true}).click();
  await flat.waitForFunction(()=>document.querySelector('.cc-map-tools>button>span')?.textContent==='4');
  await flat.locator('.cc-map-fallback [aria-label="查看地区 广东省"]').first().press('Enter');
  assert.match(await flat.locator('.cc-route-detail').innerText(),/地区分布/);
  await flat.getByRole('button',{name:'关闭地图详情'}).click();
  await flat.getByRole('button',{name:/^运输通道/}).click();await flat.locator('.cc-corridor-option').first().click();
  await flat.getByRole('button',{name:'路线回放',exact:true}).click();
  await flat.waitForFunction(()=>Number(document.querySelector('.cc-explorer').dataset.progress)>.5);
  await flat.screenshot({path:path.join(out,'network-fallback-1366.png')});
  await fallback.close();results.push('leave/return cleanup, failed reference retry, keyboard province selection and 2D playback');
  assert.deepEqual(errors,[]);
  const report={status:'PASS',desktopOnly:true,results,errors};fs.writeFileSync(path.join(out,'map-browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
