// Published products expose structured, minimized data. Samples are illustrative only.
export const dataFields:Record<string,string[]>={
 TASKS:['businessNo','mode','status','quantityKg','loadedKg','unloadedKg','origin','destination','createdAt'],
 METRICS:['mode','taskCount','completedCount','quantityKg','asOf'],
 LINES:['name','mode','origin','destination','distanceKm','durationMinutes','source','sourceUrl','asOf'],
 CAPACITY:['providerCode','providerName','origin','destination','modes','grains','capacityMinTons','capacityMaxTons','loadingType','priceBands','capacityState','servicePeriod','fulfillment','asOf'],
 CORRIDOR:['period','origin','destination','modes','departedTons','inTransitTons','arrivedTons','waybillCount','averageTransitHours','averageWaitHours','congestion','disturbances','asOf'],
 TRACE:['waybillNo','eventType','occurredAt','node','mode','consistency','evidenceType','dataQuality'],
 CREDIT:['providerCode','providerName','registeredRegion','modes','periodMonths','completedOrders','punctualityPercent','exceptionPercent','settlementPercent','riskGrade','disclaimer','asOf'],
 RISK:['riskId','riskType','level','title','affectedNode','waybillNo','estimatedDelayHours','validUntil','advice','source','asOf']
};
const common={owner:'平台运营方',format:'JSON',frequency:'按需',serviceMode:'BOTH'};
export const dataCatalog=[
 {...common,code:'GDS-CAPACITY',dataset:'CAPACITY',name:'北粮南运多式联运运力资源要素产品',shortName:'多式联运运力资源',theme:'运力资源',description:'按授权线路查询公路、铁路、水运及组合运力，结合运价区间与承运履约统计，支持粮食运输计划和询价。',source:'平台已发布运输供给、承运履约台账、线路资料',coverage:'北粮南运线路与集疏运节点',conditions:'仅按审核通过的起讫线路提供数据；企业脱敏，不含联系方式、合同底价及完整单据。',
  icon:'truck',accent:'blue',audience:['粮食贸易企业','加工与饲料企业','物流运营商'],deliveries:['查询 API','批量数据文件','运力分析报告'],contents:['分方式运力目录、起讫节点、适运粮种与承运范围','散货、20GP、40GP参考报价区间；服务周期与运力状态','脱敏承运主体与履约汇总'],sources:['已发布运力供给','线路参考资料','历史运输任务'],external:['铁路余位、港口舱位及航次余舱需另行接入'],scopeText:'限定线路 · 企业脱敏',scopes:['PUBLIC'],sample:{providerCode:'CY-示例',providerName:'东北粮运***',origin:'辽宁省 / 营口市',destination:'广东省 / 广州市',modes:['公路','水运'],capacityMinTons:500,capacityMaxTons:5000,priceBands:[{type:'BULK',min:250,max:300,unit:'元/吨'}],capacityState:'可用'}},
 {...common,code:'GDS-CORRIDOR',dataset:'CORRIDOR',name:'北粮南运粮食物流通道运行态势要素产品',shortName:'粮食通道运行态势',theme:'通道态势',description:'按日、周、月观察起讫通道的发运、在途和到达粮食量，结合节点等待及公共扰动提示，支持通道选择和调度。',source:'平台联运服务、阶段执行与节点观测、有效公共态势登记',coverage:'北粮南运主要通道与枢纽',conditions:'仅提供通道、时段与方式的汇总，不含企业名称、单票标识或业务明细；低样本量隐藏吨数及效率指标。',
  icon:'route',accent:'teal',audience:['粮食贸易企业','物流运营商','行业管理部门'],deliveries:['汇总查询 API','通道数据文件','运行监测报告'],contents:['发运、在途、到达统计，按日 / 周 / 月查询','通道实际运输时长、节点等待与拥堵等级','道路、港口、航线及铁路扰动标签'],sources:['联运运单与运输阶段','节点事件与等候观测','有效公共态势登记'],external:['港口吞吐、锚地等待、AIS及铁路班列外部动态需另行接入'],scopeText:'通道汇总 · 小样本保护',scopes:['AGGREGATE','OWN'],sample:{period:'示例周',origin:'东北产区',destination:'珠三角',modes:['RAIL','WATER'],departedTons:6800,inTransitTons:4200,arrivedTons:2600,waybillCount:16,congestion:'需关注'}},
 {...common,serviceMode:'API',code:'GDS-TRACE',dataset:'TRACE',name:'粮食多式联运链路核验追溯要素产品',shortName:'联运链路核验追溯',theme:'链路追溯',description:'传入本企业获授权的运单号，核验出库、发运、中转、港口作业与签收事件，返回标准化过程及链路一致性标识。',source:'平台运输阶段、执行事件、节点观测与签收记录',coverage:'本企业指定运单的联运链路',conditions:'须明确指定并授权运单；禁止批量枚举，接口留痕。仅返回结构化事件，不提供原始单据图片、货权和金额信息。',
  icon:'shield',accent:'violet',audience:['粮食采购与加工企业','物流运营商','获业务授权的合作方'],deliveries:['单运单核验 API','授权核验报告'],contents:['出库、发运、到达、中转与签收标准事件','时间顺序和运输方式的一致性核验','结构化证据类型及来源质量'],sources:['运输阶段与执行事件','节点观测','司机业务回传记录'],external:['外部 EPCIS、铁路及港口事件需获权后另行接入'],scopeText:'指定运单 · 禁止批量枚举',scopes:['OWN'],sample:{waybillNo:'YD-示例',eventType:'港口到达',occurredAt:'示例时间',node:'营口港',mode:'ROAD',consistency:'与声明一致',evidenceType:'过磅单',dataQuality:'示例'}},
 {...common,code:'GDS-CREDIT',dataset:'CREDIT',name:'北粮南运物流承运主体信用画像要素产品',shortName:'承运主体信用画像',theme:'承运信用',description:'按近3个月或12个月提供承运主体履约稳定性、准时率、异常率及结算表现，辅助供应商选择与合作评估。',source:'平台承运业务、运输阶段、异常记录与结算履约汇总',coverage:'入驻物流运营商',conditions:'企业名称脱敏，只提供汇总指标和风险标签；不含私密联系人、财务流水或原始纠纷。本产品仅供业务合作参考，不构成法定信用评级。',
  icon:'building',accent:'amber',audience:['粮食贸易企业','物流代理','平台运营方'],deliveries:['画像查询 API','企业信用汇总文件','合作评估报告'],contents:['运输方式、经营区域及履约样本量','近3 / 12个月准时率、异常率和结算完成率','基于样本的风险标签；样本不足时不评级'],sources:['运输阶段与完成记录','执行异常','账单与结算状态'],external:['行业公开不良信用及港口反馈需另行接入'],scopeText:'汇总画像 · 合作参考',scopes:['PUBLIC'],sample:{providerCode:'CY-示例',providerName:'辽港粮运***',periodMonths:3,completedOrders:32,punctualityPercent:96.9,exceptionPercent:3.1,riskGrade:'低风险参考',disclaimer:'仅供合作参考，不构成法定信用评级'}},
 {...common,code:'GDS-RISK',dataset:'RISK',name:'粮食物流运输风险预警专题要素产品',shortName:'运输风险预警专题',theme:'运输风险',description:'订阅公共通道风险，或查看本企业在途运单的预测预警，获取风险级别、预计影响和调度建议。',source:'有效港口与环境态势、平台在途任务风险记录',coverage:'公共通道 / 本企业在途运单',conditions:'公共态势可申请公共版；运单预警限本企业关联业务，其他客户运单不可访问。预测结果保留来源和有效期。',
  icon:'map',accent:'rose',audience:['粮食贸易企业','加工与饲料企业','物流运营商'],deliveries:['风险查询 API','实时事件订阅 API','风险简报'],contents:['公共风险事件、影响节点与有效期','本企业在途运单的异常、预计延迟与处置建议','API事件流订阅，持续记录调用情况'],sources:['有效公共态势','任务预测预警','运输阶段与执行状态'],external:['AIS、海况、道路和航道管制专业数据需另行接入'],scopeText:'公共态势 / 本企业运单',scopes:['PUBLIC','OWN'],sample:{riskType:'PORT_CONGESTION',level:'MEDIUM',title:'港口作业等待示例',affectedNode:'营口港',estimatedDelayHours:4,advice:'核对预约窗口，协调集港计划',source:'示例数据'}}
].map(p=>({...p,fields:dataFields[p.dataset]}));
export const dataScenarios=[
 {id:'planning',name:'北粮南运运输计划',category:'运输规划',icon:'route',description:'从通道态势选择通道，参考授权线路运力与价格区间，再进入联运求解和供需匹配。',datasets:['CAPACITY','CORRIDOR','CREDIT'],steps:['比较运输通道','核对可用运力','评估承运合作','求解并发布方案'],path:'/plans/solve',action:'进入方案求解'},
 {id:'tracking',name:'北粮南运全程跟踪',category:'运输执行',icon:'map',description:'以本企业运单核验运输链路，结合在途风险提示，查看公路、铁路与水运全过程。',datasets:['TRACE','RISK','CORRIDOR'],steps:['选择本企业运单','核验阶段事件','关注在途风险','查看轨迹与回传'],path:'/tracking/journeys',action:'进入全程跟踪'},
 {id:'carrier',name:'承运合作与履约评估',category:'合作评估',icon:'building',description:'结合承运画像和相关线路的运力区间进行合作评估，再在匹配大厅邀请报价。',datasets:['CREDIT','CAPACITY'],steps:['识别候选承运主体','检查样本与履约指标','比较线路报价区间','邀请企业报价'],path:'/matches',action:'进入供需匹配'},
 {id:'risk',name:'通道运行与风险监测',category:'运输执行',icon:'shield',description:'将通道时段统计和公共风险放在同一观察范围，发现拥堵、延迟及异常。',datasets:['CORRIDOR','RISK'],steps:['选定通道与时段','比较运输效率','订阅公共风险','关注本企业运输'],path:'/tracking/themes',action:'进入专题视图'}
];
