import {Injectable,BadRequestException,NotFoundException,OnModuleInit,OnModuleDestroy} from '@nestjs/common';
import {Database} from './database';import {Audit} from './audit';import {TrackingService} from './tracking.service';import {TrackingQuery} from './tracking.dto';import {SignalInput,WeatherInput} from './intelligence.dto';import {parse,sha} from './contracts.service';import {AmapService,meters} from './amap';
const inactive=['COMPLETED','CANCELLED','RETURNED'];
const stamp=(value:any)=>new Date(value).getTime();
@Injectable()
export class ForecastService implements OnModuleInit,OnModuleDestroy {
 private timer:any;private refreshing=new Map<string,Promise<any>>();
 constructor(private db:Database,private tracking:TrackingService,private audit:Audit,private amap:AmapService){}
 onModuleInit(){this.timer=setInterval(()=>this.sweep().catch(()=>{}),60000);this.timer.unref();}
 onModuleDestroy(){clearInterval(this.timer);}
 private async sweep(){const tasks=await this.db.transportTask.findMany({where:{status:{notIn:inactive},business:{package:{status:'EFFECTIVE',isTestData:false}}},select:{id:true,business:{select:{package:{select:{carrierId:true}}}}},take:200,orderBy:{createdAt:'desc'}});for(const t of tasks){const r={user:{businessEntityId:t.business.package.carrierId,businessEntity:{type:'CARRIER'},permissions:['tracking:read']}};await this.get(t.id,true,r);}}
 state(t:any){return JSON.stringify([t.status,t.events.at(-1)?.id,t.trackPoints.at(-1)?.id,t.observations.at(-1)?.id]);}
 async signals(includeTest=false){return this.db.monitoringSignal.findMany({where:{...(process.env.NODE_ENV==='production'||!includeTest?{isTestData:false}:{})},orderBy:{observedAt:'desc'},take:500});}
 async saveSignal(d:SignalInput,r:any,id?:string){if(id&&!Number.isInteger(d.version))throw new BadRequestException('更新态势须提供当前版本');const from=new Date(d.validFrom),to=new Date(d.validTo);this.tracking.time(d.observedAt);if(!/^(https:\/\/[^\s]+)?$/.test(d.sourceUrl))throw new BadRequestException('来源链接须为 HTTPS 地址');if(from>=to||to.getTime()-from.getTime()>31*86400000)throw new BadRequestException('有效期须为正且不超过31天');if(d.kind==='PORT'&&!d.nodeId)throw new BadRequestException('港口态势须关联港口节点');if(d.nodeId){const n=await this.db.transportNode.findFirst({where:{id:d.nodeId,enabled:true,...(d.kind==='PORT'?{type:'PORT'}:{})}});if(!n)throw new BadRequestException('节点无效');}if(d.kind==='ENVIRONMENT'&&!d.nodeId&&d.bounds.length!==4)throw new BadRequestException('环境风险须指定节点或空间范围');if(d.bounds.length&&!(d.bounds.length===4&&d.bounds[0]>=73&&d.bounds[2]<=136&&d.bounds[1]>=3&&d.bounds[3]<=54&&d.bounds[0]<d.bounds[2]&&d.bounds[1]<d.bounds[3]))throw new BadRequestException('范围须为 GCJ02 [最小经度,最小纬度,最大经度,最大纬度]');if(d.isTestData&&process.env.NODE_ENV==='production')throw new BadRequestException('生产环境不可添加模拟态势');return this.db.$transaction(async tx=>{const data={...d,bounds:JSON.stringify(d.bounds),validFrom:from,validTo:to,observedAt:new Date(d.observedAt)};delete (data as any).version;const row=id?await tx.monitoringSignal.update({where:{id,version:d.version},data:{...data,version:{increment:1}}}):await tx.monitoringSignal.create({data});await this.audit.write(tx,r,'预测预警',row.id,id?'更新外部态势':'登记外部态势',undefined,{name:row.name,source:row.source});return row;});}
 async weather(d:WeatherInput,r:any){if(!/^\d{6}$/.test(d.city))throw new BadRequestException('城市编码须为六位行政编码');const node=await this.db.transportNode.findFirst({where:{id:d.nodeId,enabled:true}});if(!node)throw new NotFoundException('节点不存在');const geo=await this.amap.request('/v3/geocode/regeo',{location:`${node.lng},${node.lat}`,extensions:'base'});const adcode=geo.regeocode?.addressComponent?.adcode;if(adcode!==d.city)throw new BadRequestException('行政编码与节点实际所在区域不一致');const data=await this.amap.request('/v3/weather/weatherInfo',{city:d.city,extensions:'base'});const live=data.lives?.[0];if(!live)throw new BadRequestException('气象源尚无数据');const high=/暴雨|暴雪|台风|大暴雨|特大暴雨/.test(live.weather),medium=/大雨|大雪|雾|沙尘/.test(live.weather)||parseInt(live.windpower,10)>=6;const report=new Date(String(live.reporttime).replace(' ','T')+'+08:00');return this.saveSignal({kind:'ENVIRONMENT',name:`${live.city} · ${live.weather}`,nodeId:node.id,region:live.city,bounds:[],level:high?'HIGH':medium?'MEDIUM':'LOW',delayMinutes:0,details:`高德实时天气：${live.weather}，${live.temperature}℃，${live.winddirection}风 ${live.windpower} 级。环境提示不等同于通行或禁航决定。`,source:'AMAP_WEATHER_LIVE',sourceUrl:'https://lbs.amap.com/api/webservice/guide/api/weatherinfo',observedAt:report.toISOString(),validFrom:report.toISOString(),validTo:new Date(report.getTime()+3*3600000).toISOString(),isTestData:false},r);}
 async get(id:string,includeTest:boolean,r:any,force=false,authorizedTask?:any){const task=authorizedTask||await this.tracking.task(id,r);if(task.business.package.isTestData&&(process.env.NODE_ENV==='production'||!includeTest))throw new NotFoundException('当前范围未包含测试业务');const cached=await this.db.forecast.findFirst({where:{taskId:id},orderBy:{predictedAt:'desc'}});if(!force&&cached&&parse(cached.result).includeTest===includeTest&&parse(cached.result).entityScope===r.user.businessEntityId&&parse(cached.result).inputState===this.state(task)&&Date.now()-cached.predictedAt.getTime()<60000)return {...parse(cached.result),id:cached.id};const key=id+'|'+r.user.businessEntityId+'|'+includeTest;if(this.refreshing.has(key))return this.refreshing.get(key);const work=this.compute(task,includeTest,r).finally(()=>this.refreshing.delete(key));this.refreshing.set(key,work);return work;}
 async compute(t:any,includeTest:boolean,r:any){const now=new Date(),q=Object.assign(new TrackingQuery(),{includeTest:String(includeTest)}),rules=await this.tracking.rules(),planned=await this.tracking.planned(t),seg=planned[t.segment-1],snapshot=parse(t.business.package.snapshot),latest=this.tracking.current(t,q),signals=(await this.signals(includeTest)).filter(s=>s.validFrom<=now&&s.validTo>now);const factors:string[]=[],sources:any[]=[],external:any[]=[];let eta:string|null=null,range:any=null,remainingKm:number|null=null,remainingMinutes:number|null=null,quality='INSUFFICIENT',method='NO_RELIABLE_INPUT';const arrival=t.events.find((e:any)=>e.type==='ARRIVE');
 for(const s of signals){const bounds=parse(s.bounds),inBounds=(p:any)=>bounds.length===4&&Number.isFinite(p.lng)&&p.lng>=bounds[0]&&p.lng<=bounds[2]&&p.lat>=bounds[1]&&p.lat<=bounds[3];const affected=s.nodeId&&[seg?.origin?.id,seg?.destination?.id].includes(s.nodeId)||inBounds(seg?.origin||{})||inBounds(seg?.destination||{})||latest&&inBounds({lng:latest.longitude,lat:latest.latitude})||seg?.geometry?.coordinates?.some((p:number[])=>inBounds({lng:p[0],lat:p[1]}));if(affected){sources.push({source:s.source,observedAt:s.observedAt,url:s.sourceUrl,isTestData:s.isTestData});factors.push(s.details);if(s.level!=='LOW')external.push({type:s.kind==='PORT'?'PORT_CONGESTION':'ENVIRONMENT',level:s.level,message:s.name+'：'+s.details,at:s.observedAt,signalId:s.id});}}
 if(arrival){eta=arrival.createdAt.toISOString();quality='ACTUAL';method='EXECUTION_ARRIVAL';factors.push('实际到达来自人工执行事件');sources.push({source:'EXECUTION',observedAt:arrival.createdAt});}
 else if(!inactive.includes(t.status)&&t.business.package.status!=='TERMINATED'){
 if(latest){sources.push({source:latest.sourceSystem,type:latest.sourceType,observedAt:latest.observedAt,isTestData:latest.isTestData});const fresh=Date.now()-stamp(latest.observedAt)<=rules.staleMinutes*60000,path=seg?.geometry?.coordinates;
 if(fresh&&path?.length>=3&&this.tracking.distanceToPath(latest,path)<=rules.deviationMeters){let nearest=0,best=Infinity;path.forEach((p:number[],i:number)=>{const dist=meters({lng:p[0],lat:p[1]},{lng:latest.longitude,lat:latest.latitude});if(dist<best){best=dist;nearest=i;}});let distance=best;for(let i=nearest+1;i<path.length;i++)distance+=meters({lng:path[i-1][0],lat:path[i-1][1]},{lng:path[i][0],lat:path[i][1]});remainingKm=Math.round(distance/100)/10;const points=this.tracking.positionsFor(t,q).filter((p:any)=>p.sourceType===latest.sourceType&&p.assetId===latest.assetId&&stamp(p.observedAt)>=now.getTime()-3600000&&(includeTest||!p.isTestData));const speeds:number[]=[];for(let i=1;i<points.length;i++){const seconds=(stamp(points[i].observedAt)-stamp(points[i-1].observedAt))/1000;if(seconds>=30&&seconds<1800){const speed=meters({lng:points[i].longitude,lat:points[i].latitude},{lng:points[i-1].longitude,lat:points[i-1].latitude})/seconds*3.6;if(speed>= (t.mode==='ROAD'?5:1)&&speed<=(t.mode==='ROAD'?120:60))speeds.push(speed);}}if(speeds.length>=2){speeds.sort((a,b)=>a-b);const speed=speeds[Math.floor(speeds.length/2)],delay=signals.filter(s=>external.some(e=>e.signalId===s.id)).reduce((sum,s)=>sum+s.delayMinutes,0);remainingMinutes=Math.ceil(distance/1000/speed*60)+delay;const estimate=now.getTime()+remainingMinutes*60000;eta=new Date(estimate).toISOString();range={from:new Date(now.getTime()+remainingMinutes*.75*60000).toISOString(),to:new Date(now.getTime()+remainingMinutes*1.5*60000).toISOString()};quality=latest.isTestData?'SIMULATED':'MEDIUM';method='PATH_AND_OBSERVED_SPEED';factors.push(`按可验证路径剩余 ${remainingKm} 公里及近期中位速度 ${speed.toFixed(1)} km/h 估算；未计入未观测的道路、港口作业变化。`);sources.push({source:seg.geometry.source,observedAt:seg.geometry.queriedAt||null});}else factors.push('有效速度样本不足，无法给出动态 ETA');}
 else factors.push(!fresh?'定位已过期，停止动态 ETA 推断':'缺少可验证路径或当前位置偏离路径，停止动态 ETA 推断');}
 else factors.push(t.mode==='RAIL'?'铁路以到发节点展示进度；缺少可靠运行时效':'缺少本任务近期定位');
 if(!eta&&['IN_TRANSIT','LOADED','ACCEPTED'].includes(t.status)){const hist=await this.db.transportTask.findMany({where:{mode:t.mode,status:'COMPLETED',business:{package:{isTestData:t.business.package.isTestData,...this.tracking.scope(r,q)}}},include:{business:true,events:{where:{type:{in:['DEPART','ARRIVE']}},orderBy:{createdAt:'asc'}}},orderBy:{createdAt:'desc'},take:200});const durations=hist.filter(h=>{const s=parse(h.business.segments)[h.segment-1];return s?.origin===parse(t.business.segments)[t.segment-1]?.origin&&s?.destination===parse(t.business.segments)[t.segment-1]?.destination;}).map(h=>{const start=h.events.find(e=>e.type==='DEPART'),end=h.events.find(e=>e.type==='ARRIVE');return start&&end?(stamp(end.createdAt)-stamp(start.createdAt))/60000:0;}).filter(n=>n>=1);const departed=t.events.find((e:any)=>e.type==='DEPART');if(durations.length>=3&&departed){durations.sort((a,b)=>a-b);const mid=durations[Math.floor(durations.length/2)],end=stamp(departed.createdAt)+mid*60000;if(end>now.getTime()){eta=new Date(end).toISOString();remainingMinutes=Math.ceil((end-now.getTime())/60000);range={from:new Date(stamp(departed.createdAt)+durations[0]*60000).toISOString(),to:new Date(stamp(departed.createdAt)+durations.at(-1)!*60000).toISOString()};quality=t.business.package.isTestData?'SIMULATED':'LOW';method='SAME_ROUTE_EXECUTION_HISTORY';factors.push(`仅使用授权范围内同区段 ${durations.length} 次已完成执行时效；需人工确认。`);sources.push({source:'AUTHORIZED_EXECUTION_HISTORY',samples:durations.length,observedAt:hist[0]?.createdAt});}}}
 }
 if(snapshot.sourceSystem==='BUSINESS_INITIALIZATION'){quality='INITIALIZATION';factors.push('依据初始化运输记录和参考路径估算，待实际定位与运输回单核验');}
 const plannedArrivalAt=snapshot.deal?.arrivalAt||null,delayMinutes=eta&&plannedArrivalAt&&quality!=='ACTUAL'?Math.max(0,Math.round((stamp(eta)-stamp(plannedArrivalAt))/60000)):null;
 const computed=this.tracking.risks({...t,planned},q,rules).concat(external.map(e=>({...e,taskId:t.id,taskNo:t.businessNo,mode:t.mode})));if(delayMinutes&&delayMinutes>30)computed.push({type:'ETA_DELAY',level:delayMinutes>120?'HIGH':'MEDIUM',message:`当前区段 ETA 超过合同最终到达约定 ${delayMinutes} 分钟，需核实后续衔接`,at:now,taskId:t.id,taskNo:t.businessNo,mode:t.mode});
 const active=inactive.includes(t.status)||t.business.package.status==='TERMINATED'?[]:computed;const result={includeTest,entityScope:r.user.businessEntityId,inputState:this.state(t),taskId:t.id,taskNo:t.businessNo,predictedAt:now,plannedArrivalAt,eta,range,remainingKm,remainingMinutes,delayMinutes,quality,method,needsReview:!['ACTUAL','HIGH'].includes(quality),factors,sources,externalSignals:signals.filter(s=>sources.some(p=>p.source===s.source&&stamp(p.observedAt)===stamp(s.observedAt))),scope:'CURRENT_SEGMENT',finalEta:t.segment===planned.length?eta:null,finalEtaNote:t.segment<planned.length?'后续区段尚未执行，最终 ETA 需补充可靠衔接与时效数据':'当前区段为最后一程'};
 return this.db.$transaction(async tx=>{const saved=await tx.forecast.create({data:{taskId:t.id,result:JSON.stringify(result),inputDigest:sha(JSON.stringify({latest:latest?.id,status:t.status,signals:sources,rules}))}});const existing=await tx.riskRecord.findMany({where:{taskId:t.id,status:{in:['NEW','ONGOING']}}});for(const risk of active){const old=existing.find(e=>e.type===risk.type);if(old)await tx.riskRecord.update({where:{id:old.id},data:{status:'ONGOING',level:risk.level,message:risk.message,lastSeenAt:now}});else await tx.riskRecord.create({data:{taskId:t.id,type:risk.type,level:risk.level,message:risk.message,firstSeenAt:new Date(risk.at||now),lastSeenAt:now}});}for(const old of existing)if(!active.some(e=>e.type===old.type))await tx.riskRecord.update({where:{id:old.id},data:{status:'RECOVERED',recoveredAt:now,lastSeenAt:now}});const older=await tx.forecast.findMany({where:{taskId:t.id},orderBy:{predictedAt:'desc'},skip:100,select:{id:true}});if(older.length)await tx.forecast.deleteMany({where:{id:{in:older.map(x=>x.id)}}});return {...result,id:saved.id};});
 }
 async riskHistory(q:TrackingQuery,r:any){const tasks=await this.db.transportTask.findMany({where:{business:{package:this.tracking.scope(r,q)}},select:{id:true,businessNo:true,mode:true}});const where={taskId:{in:tasks.map(t=>t.id)}};const [items,total]=await this.db.$transaction([this.db.riskRecord.findMany({where,orderBy:{lastSeenAt:'desc'},skip:(q.page-1)*q.pageSize,take:q.pageSize}),this.db.riskRecord.count({where})]);return {items:items.map(i=>({...i,taskNo:tasks.find(t=>t.id===i.taskId)?.businessNo,mode:tasks.find(t=>t.id===i.taskId)?.mode})),total};}
}
