import {selectableVehicles} from './business-resource-scope';
import {Injectable,BadRequestException,ForbiddenException,NotFoundException,ConflictException} from '@nestjs/common';
import {randomUUID} from 'node:crypto';
import {Database} from './database';
import {Audit} from './audit';
import {TrackingService} from './tracking.service';
import {ContractsService,parse,number,sha} from './contracts.service';
import {BusinessDto,VehicleDto,TaskDto,EventDto,IssueDto,ResolutionDto,BatchDto,ArrivalDto,BoxDto} from './fulfillment.dto';
const evidenceSelect={id:true,taskId:true,category:true,name:true,mime:true,digest:true,createdAt:true};
const tasksInclude={stage:true,events:{orderBy:{createdAt:'asc' as const}},issues:true,evidence:{select:evidenceSelect}};
@Injectable()
export class FulfillmentService {
 constructor(private db:Database,private audit:Audit,private contracts:ContractsService,private tracking:TrackingService){}
 driver(req:any){return req.user.roles.some((r:any)=>r.code==='driver');}
 owner(p:any,req:any){if(req.user.businessEntity.type!=='CARRIER'||p.carrierId!==req.user.businessEntityId)throw new ForbiddenException('仅本业务承运商可调度');}
 async business(id:string,req:any,db:any=this.db){const b=await db.logisticsBusiness.findFirst({where:{id,package:this.contracts.scope(req)},include:{package:{include:{revisions:{orderBy:{number:'asc'}}}},tasks:{include:tasksInclude},batches:true}});if(!b)throw new NotFoundException('联运业务不存在');return b;}
 view(b:any){const last=parse(b.segments).length;const counted=b.tasks.filter((t:any)=>t.segment===last&&t.status==='COMPLETED');return {...b,segments:parse(b.segments),package:{...b.package,snapshot:parse(b.package.snapshot)},batches:b.batches.map((v:any)=>({...v,arrivals:parse(v.arrivals),boxes:parse(v.boxes)})),completedKg:counted.reduce((s:number,t:any)=>s+(t.unloadedKg||0),0)};}
 async list(req:any){const all=await this.db.logisticsBusiness.findMany({where:{package:this.contracts.scope(req)},include:{package:true,tasks:{include:tasksInclude},batches:true},orderBy:{createdAt:'desc'},take:500});return all.map(b=>this.view(b));}
 async detail(id:string,req:any){return this.view(await this.business(id,req));}
 async create(dto:BusinessDto,req:any){return this.db.$transaction(async tx=>{const p=await this.contracts.row(dto.packageId,req,tx);this.owner(p,req);if(p.status!=='EFFECTIVE')throw new ConflictException('合同包尚未完整生效');if(!dto.segments.length||dto.segments.length>20)throw new BadRequestException('请填写 1 至 20 个运输区段');for(let i=1;i<dto.segments.length;i++)if(dto.segments[i-1].destination.trim()!==dto.segments[i].origin.trim())throw new BadRequestException('相邻运输区段的交接地点须一致');if(dto.needsContainerization&&parse(p.snapshot).loadingType!=='BULK')throw new BadRequestException('只有散粮业务可启用散改集');const existing=await tx.logisticsBusiness.findUnique({where:{packageId:p.id},include:{tasks:true,stages:{include:{attachments:true}}}});if(existing&&(existing.tasks.length||existing.stages.some(v=>v.status!=='DRAFT'||v.attachments.length)))throw new ConflictException('合同对应运单已进入执行，不能重复建立');const r=existing?await tx.logisticsBusiness.update({where:{id:existing.id},data:{mode:'SINGLE',needsContainerization:dto.needsContainerization,segments:JSON.stringify(dto.segments)}}):await tx.logisticsBusiness.create({data:{packageId:p.id,businessNo:number('LY'),mode:'SINGLE',waybillNo:'YD'+p.businessNo.replace(/^HT/,''),needsContainerization:dto.needsContainerization,segments:JSON.stringify(dto.segments)}});if(existing)await tx.transportStage.deleteMany({where:{businessId:r.id}});for(let i=0;i<dto.segments.length;i++)await tx.transportStage.create({data:{businessId:r.id,managed:false,sequence:i+1,...dto.segments[i],quantityKg:p.quantityKg,plannedStartAt:new Date(),plannedEndAt:new Date(Date.now()+86400000),containerized:parse(p.snapshot).loadingType==='CONTAINER'}});await this.audit.write(tx,req,'联运组织',r.id,'建立联运业务',undefined,dto);return {id:r.id};});}
 async resources(req:any){this.contracts.role(req,'CARRIER');return {vehicles:await selectableVehicles(this.db,req.user.businessEntityId),drivers:await this.db.user.findMany({where:{businessEntityId:req.user.businessEntityId,deletedAt:null,status:'ACTIVE',roles:{some:{role:{code:'driver'}}}},select:{id:true,displayName:true,phone:true}})};}
 async vehicle(dto:VehicleDto,req:any){this.contracts.role(req,'CARRIER');return this.db.$transaction(async tx=>{const v=await tx.fleetVehicle.create({data:{...dto,plate:dto.plate.trim().toUpperCase(),carrierId:req.user.businessEntityId}});await this.audit.write(tx,req,'车辆',v.id,'登记车辆');return v;});}
 async dispatch(id:string,dto:TaskDto,req:any){return this.db.$transaction(async tx=>{const b=await this.business(id,req,tx);this.owner(b.package,req);if(b.package.status!=='EFFECTIVE')throw new ConflictException('合同包未生效或已终止');if(await tx.transportStage.count({where:{businessId:id,managed:true}}))throw new ConflictException('请在联运服务中填写并提交运输阶段');const effective=b.package.revisions.filter((r:any)=>r.status==='EFFECTIVE').at(-1);if(!effective||new Date(parse(effective.terms).expiresAt)<=new Date())throw new ConflictException('合同已到期');const segments=parse(b.segments),segment=segments[dto.segment-1];if(!segment)throw new BadRequestException('区段不存在');const allocated=b.tasks.filter((t:any)=>t.segment===dto.segment&&t.status!=='CANCELLED').reduce((sum:number,t:any)=>sum+t.quantityKg,0);if(allocated+dto.quantityKg>b.package.quantityKg)throw new ConflictException('本区段累计分配数量超过合同量');
  if(segment.mode==='ROAD'){const v=await tx.fleetVehicle.findFirst({where:{id:dto.vehicleId||'',carrierId:req.user.businessEntityId}}),driver=await tx.user.findFirst({where:{id:dto.driverId||'',businessEntityId:req.user.businessEntityId,status:'ACTIVE',deletedAt:null,roles:{some:{role:{code:'driver'}}}}});if(!v||!driver)throw new BadRequestException('请选择本企业有效车辆及司机');if(dto.quantityKg>v.capacityKg)throw new BadRequestException('任务数量超过车辆载重');}else if(!dto.resource.trim())throw new BadRequestException('铁路/水运任务须填写车次或船舶航次、运单号');
  if(dto.batchId){const batch=b.batches.find((v:any)=>v.id===dto.batchId);if(!batch)throw new BadRequestException('散改集批次不属于本业务');const box=dto.boxNo?parse(batch.boxes).find((v:any)=>v.boxNo===dto.boxNo):null;if(dto.boxNo&&!box)throw new BadRequestException('集装箱不属于所选批次');const used=b.tasks.filter((v:any)=>v.segment===dto.segment&&v.batchId===dto.batchId&&(!dto.boxNo||v.boxNo===dto.boxNo)&&v.status!=='CANCELLED').reduce((s:number,v:any)=>s+v.quantityKg,0);if(used+dto.quantityKg>(box?.quantityKg||batch.quantityKg))throw new ConflictException('批次或集装箱在本区段已分配量超限');}else if(dto.boxNo)throw new BadRequestException('请先选择集装箱所属批次');
  await tx.logisticsBusiness.update({where:{id,version:b.version},data:{version:{increment:1}}});const stage=await tx.transportStage.findFirst({where:{businessId:id,sequence:dto.segment}});if(stage)await tx.transportStage.update({where:{id:stage.id},data:{status:'SUBMITTED'}});await tx.logisticsBusiness.update({where:{id},data:{status:'IN_PROGRESS'}});const task=await tx.transportTask.create({data:{stageId:stage?.id,businessNo:number('RW'),businessId:id,batchId:dto.batchId||null,boxNo:dto.boxNo||null,segment:dto.segment,mode:segment.mode,quantityKg:dto.quantityKg,vehicleId:segment.mode==='ROAD'?dto.vehicleId:null,driverId:segment.mode==='ROAD'?dto.driverId:null,resource:dto.resource,status:segment.mode==='ROAD'?'DISPATCHED':'ACCEPTED'}});await this.audit.write(tx,req,'运输任务',task.id,'下发任务',undefined,dto);return task;
 });}
 async task(id:string,req:any,db:any=this.db){const t=await db.transportTask.findFirst({where:{id,...(this.driver(req)?{driverId:req.user.id}:{business:{package:this.contracts.scope(req)}})},include:{...tasksInclude,business:{include:{package:true}}}});if(!t)throw new NotFoundException('任务不存在或未分配给您');return t;}
 taskView(t:any){const snapshot=parse(t.business.package.snapshot),segments=parse(t.business.segments);return {id:t.id,businessNo:t.businessNo,version:t.version,stageId:t.serviceManaged?t.stageId:null,waybillNo:t.business.waybillNo,containerized:t.stage?.containerized??snapshot.loadingType==='CONTAINER',feedback:parse(t.feedback),feedbackSubmittedAt:t.feedbackSubmittedAt,quantityKg:t.quantityKg,loadedKg:t.loadedKg,unloadedKg:t.unloadedKg,status:t.status,mode:t.mode,resource:t.resource,boxNo:t.boxNo,segment:t.stage?{mode:t.stage.mode,origin:t.stage.origin,destination:t.stage.destination}:segments[t.segment-1],cargo:snapshot.grain||'粮食',plannedDepartureAt:t.plannedStartAt||snapshot.deal?.departureAt||null,requiredArrivalAt:t.plannedEndAt||snapshot.deal?.arrivalAt||null,contact:snapshot.trader.contact,phone:snapshot.trader.phone,events:t.events.map((e:any)=>({...e,payload:parse(e.payload)})),issues:t.issues,evidence:t.evidence};}
 async driverTasks(req:any){return (await this.db.transportTask.findMany({where:{driverId:req.user.id},include:{...tasksInclude,business:{include:{package:true}}},orderBy:{createdAt:'desc'},take:500})).map(t=>this.taskView(t));}
 async event(id:string,dto:EventDto,req:any){let coordinates:any=null;if(dto.type==='POSITION'){const t=await this.task(id,req);const replay=await this.db.executionEvent.findUnique({where:{taskId_requestKey:{taskId:id,requestKey:dto.requestKey}}});if(replay){if(replay.type!==dto.type||replay.payload!==JSON.stringify(dto))throw new ConflictException('相同请求键不能提交不同事件');return replay;}if(!this.driver(req)||t.status!=='IN_TRANSIT'||dto.longitude===undefined||dto.latitude===undefined)throw new BadRequestException('运输中的关联司机才能记录位置');coordinates=await this.tracking.coordinates(dto.longitude,dto.latitude,'WGS84');}return this.db.$transaction(async tx=>{const t=await this.task(id,req,tx);const isDriver=this.driver(req);if(!isDriver){this.owner(t.business.package,req);if(t.mode==='ROAD')throw new ForbiddenException('公路执行节点由分配的司机反馈');}if(t.business.package.status!=='EFFECTIVE')throw new ConflictException('合同不可执行');
  if(t.serviceManaged&&t.stage?.status==='COMPLETED')throw new ConflictException('阶段已完成');if(t.serviceManaged&&dto.type==='COMPLETE')throw new ForbiddenException('请回传业务信息，由物流运营商确认阶段完成');const replay=await tx.executionEvent.findUnique({where:{taskId_requestKey:{taskId:id,requestKey:dto.requestKey}}});if(replay){if(replay.type!==dto.type||replay.payload!==JSON.stringify(dto))throw new ConflictException('相同请求键不能提交不同事件');return replay;}
  const next:any={ACCEPT:['DISPATCHED','ACCEPTED'],RETURN:['DISPATCHED','RETURNED'],AT_LOADING:['ACCEPTED','AT_LOADING'],LOAD:['AT_LOADING','LOADED'],DEPART:['LOADED','IN_TRANSIT'],ARRIVE:['IN_TRANSIT','ARRIVED'],UNLOAD:['ARRIVED','UNLOADED'],RECEIPT:['UNLOADED','RECEIVED'],COMPLETE:['RECEIVED','COMPLETED']};const rule=next[dto.type];if(dto.type==='POSITION'){if(t.status!=='IN_TRANSIT'||dto.latitude===undefined||dto.longitude===undefined)throw new BadRequestException('运输中才能记录有效位置');}else if(!rule||t.status!==rule[0])throw new ConflictException('请按任务节点顺序操作');
  if(dto.type==='RETURN'&&!dto.note?.trim())throw new BadRequestException('请说明信息有误原因');if(['LOAD','UNLOAD'].includes(dto.type)){if(!dto.quantityKg||dto.quantityKg>t.quantityKg)throw new BadRequestException('实际数量须大于零且不超过派发量');if(dto.type==='UNLOAD'&&dto.quantityKg>t.loadedKg)throw new BadRequestException('卸货量不能超过装货量');if(dto.quantityKg!==(dto.type==='LOAD'?t.quantityKg:t.loadedKg)&&!dto.note?.trim())throw new BadRequestException('数量偏差须填写原因');}
  if(dto.type==='LOAD'&&!t.serviceManaged&&t.segment>1){const upstream=await tx.transportTask.findMany({where:{businessId:t.businessId,segment:t.segment-1,status:'COMPLETED'}});const current=await tx.transportTask.findMany({where:{businessId:t.businessId,segment:t.segment,status:{not:'CANCELLED'}}});if(current.reduce((sum,v)=>sum+(v.loadedKg||0),0)+(dto.quantityKg||0)>upstream.reduce((sum,v)=>sum+(v.unloadedKg||0),0))throw new ConflictException('上一运输区段尚未交付足够数量');}
  if(['LOAD','RECEIPT'].includes(dto.type)){const file=await tx.executionEvidence.findFirst({where:{id:dto.evidenceId||'',taskId:id,userId:req.user.id}});if(!file)throw new BadRequestException('请先上传本任务的装货凭证或签收回单');}if(dto.type==='RECEIPT'&&!dto.receiver?.trim())throw new BadRequestException('请填写签收人');if(dto.type==='COMPLETE'&&t.issues.some((i:any)=>i.status==='OPEN'))throw new ConflictException('请先由调度处理未关闭异常');
  await tx.transportTask.update({where:{id,version:t.version},data:{version:{increment:1},...(rule?{status:rule[1]}:{}),...(dto.type==='LOAD'?{loadedKg:dto.quantityKg}:{}),...(dto.type==='UNLOAD'?{unloadedKg:dto.quantityKg}:{})}});if(dto.type==='COMPLETE'&&t.stageId&&!t.serviceManaged){const active=await tx.transportTask.count({where:{stageId:t.stageId,status:{notIn:['COMPLETED','CANCELLED']}}});if(!active)await tx.transportStage.update({where:{id:t.stageId},data:{status:'COMPLETED',actualEndAt:new Date(),completedAt:new Date()}});}const e=await tx.executionEvent.create({data:{taskId:id,requestKey:dto.requestKey,type:dto.type,source:isDriver?'DRIVER_SIMULATOR':'PC',userId:req.user.id,payload:JSON.stringify(dto)}});if(coordinates)await tx.trackPoint.create({data:{taskId:id,sourceSystem:'DRIVER_SIMULATOR',sourceRecordId:dto.requestKey,sourceType:'SIMULATED',assetId:t.vehicleId||req.user.id,observedAt:e.createdAt,...coordinates,originalLongitude:dto.longitude!,originalLatitude:dto.latitude!,originalCoordinateSystem:'WGS84',isTestData:true,dataQuality:'SIMULATED',fingerprint:sha(JSON.stringify(dto))}});await this.audit.write(tx,req,'运输任务',id,'执行节点 '+dto.type,{status:t.status},{status:rule?.[1]||t.status,eventId:e.id});return e;
 });}
 async cancelTask(id:string,req:any){return this.db.$transaction(async tx=>{const t=await this.task(id,req,tx);this.owner(t.business.package,req);if(t.serviceManaged)throw new ConflictException('已提交阶段的车辆任务不能单独取消');if(!['DISPATCHED','RETURNED','ACCEPTED'].includes(t.status))throw new ConflictException('任务已进入执行，不能取消');await tx.transportTask.update({where:{id,version:t.version},data:{status:'CANCELLED',version:{increment:1}}});await this.audit.write(tx,req,'运输任务',id,'取消待执行任务');return {id};});}
 async issue(id:string,dto:IssueDto,req:any){return this.db.$transaction(async tx=>{const t=await this.task(id,req,tx);if(!this.driver(req))this.owner(t.business.package,req);if(['COMPLETED','CANCELLED'].includes(t.status))throw new ConflictException('任务已结束');const issue=await tx.executionIssue.create({data:{taskId:id,...dto}});await this.audit.write(tx,req,'运输异常',issue.id,'上报异常',undefined,dto);return issue;});}
 async resolve(id:string,dto:ResolutionDto,req:any){return this.db.$transaction(async tx=>{const issue=await tx.executionIssue.findUnique({where:{id}});if(!issue)throw new NotFoundException();const t=await this.task(issue.taskId,req,tx);this.owner(t.business.package,req);if(issue.status!=='OPEN')throw new ConflictException('异常已处理');await tx.executionIssue.update({where:{id},data:{resolution:dto.resolution,status:'RESOLVED',resolvedAt:new Date()}});await this.audit.write(tx,req,'运输异常',id,'关闭异常',undefined,dto);return {id};});}
 async upload(id:string,file:any,req:any,category='GENERAL'){if(!['GENERAL','EIR','WEIGH','RECEIPT','FEE'].includes(category))throw new BadRequestException('单据类型无效');if(!file?.buffer||!file.size)throw new BadRequestException('请上传文件');const bytes:Buffer=file.buffer;const mime=bytes.subarray(0,5).toString()==='%PDF-'?'application/pdf':bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))?'image/png':bytes[0]===255&&bytes[1]===216&&bytes[2]===255?'image/jpeg':null;if(!mime)throw new BadRequestException('仅支持有效 PDF、PNG 或 JPG');return this.db.$transaction(async tx=>{const t=await this.task(id,req,tx);if(!this.driver(req))this.owner(t.business.package,req);if(['COMPLETED','CANCELLED'].includes(t.status))throw new ConflictException('任务已结束');if(t.evidence.length>=20)throw new BadRequestException('每个任务最多 20 份单据');const f=await tx.executionEvidence.create({data:{taskId:id,category,userId:req.user.id,name:Buffer.from(file.originalname,'latin1').toString('utf8').slice(0,200),mime,bytes:new Uint8Array(bytes),digest:sha(bytes)},select:evidenceSelect});await this.audit.write(tx,req,'运输单据',f.id,'上传单据');return f;});}
 async download(id:string,req:any){const f=await this.db.executionEvidence.findUnique({where:{id},select:{id:true,taskId:true}});if(!f)throw new NotFoundException();await this.task(f.taskId,req);await this.audit.write(this.db,req,'运输单据',id,'下载单据');return this.db.executionEvidence.findUniqueOrThrow({where:{id}});}
 async batch(id:string,dto:BatchDto,req:any){return this.db.$transaction(async tx=>{const b=await this.business(id,req,tx);this.owner(b.package,req);if(!b.needsContainerization||b.package.status!=='EFFECTIVE')throw new BadRequestException('仅生效散改集业务可建立批次');if(b.batches.reduce((s:number,x:any)=>s+x.quantityKg,0)+dto.quantityKg>b.package.quantityKg)throw new BadRequestException('批次数量超过合同量');await tx.logisticsBusiness.update({where:{id,version:b.version},data:{version:{increment:1}}});const v=await tx.containerBatch.create({data:{businessId:id,...dto}});await this.audit.write(tx,req,'散改集',v.id,'建立批次');return v;});}
 async packing(id:string,dto:ArrivalDto|BoxDto,kind:string,req:any){return this.db.$transaction(async tx=>{const batch=await tx.containerBatch.findUnique({where:{id}});if(!batch)throw new NotFoundException();const b=await this.business(batch.businessId,req,tx);this.owner(b.package,req);if(b.package.status!=='EFFECTIVE'||batch.version!==dto.version)throw new ConflictException('批次已更新或合同已终止');const arrivals=parse(batch.arrivals),boxes=parse(batch.boxes);
  if(kind==='arrival'){const d=dto as ArrivalDto,netKg=d.grossKg-d.tareKg;if(netKg<=0||arrivals.reduce((s:number,v:any)=>s+v.netKg,0)+netKg>batch.quantityKg)throw new BadRequestException('净重须大于零且累计不能超过批次数量');if(arrivals.some((a:any)=>a.ticketNo===d.ticketNo))throw new ConflictException('磅单号已登记');arrivals.push({...d,id:randomUUID(),netKg,at:new Date().toISOString()});}
  else{const d=dto as BoxDto;if(!d.sources.length||new Set(d.sources.map(v=>v.arrivalId)).size!==d.sources.length)throw new BadRequestException('请分配不重复的到货车辆来源');if(b.batches.some((x:any)=>parse(x.boxes).some((v:any)=>v.boxNo===d.boxNo)))throw new ConflictException('业务内箱号已存在');let total=0;for(const source of d.sources){const a=arrivals.find((a:any)=>a.id===source.arrivalId),used=boxes.flatMap((v:any)=>v.sources).filter((s:any)=>s.arrivalId===source.arrivalId).reduce((n:number,s:any)=>n+s.quantityKg,0);if(!a||used+source.quantityKg>a.netKg)throw new BadRequestException('入箱量超过来源车辆剩余净重');total+=source.quantityKg;}if(total>30000)throw new BadRequestException('单箱货重不能超过 30 吨');boxes.push({...d,id:randomUUID(),quantityKg:total,at:new Date().toISOString()});}
  await tx.containerBatch.update({where:{id,version:dto.version},data:{arrivals:JSON.stringify(arrivals),boxes:JSON.stringify(boxes),version:{increment:1}}});await this.audit.write(tx,req,'散改集',id,kind==='arrival'?'登记车辆到货':'装箱并关联航次',undefined,dto);return {id};});}
}
