import { Injectable,BadRequestException,ForbiddenException,NotFoundException,ConflictException,OnModuleInit,OnModuleDestroy } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { randomUUID } from 'node:crypto';
import { Database } from './database';
import { Audit } from './audit';
import { MatchQuery,MatchPublishDto,QuoteDto,QuoteTermsDto,NegotiateDto,ConfirmDto,CloseMatchDto,MatchInviteDto } from './matching.dto';
import { demandSnapshot } from './match-snapshot';
import { supplyAvailability } from './supply-availability';
import {demandRecommendations,supplyRecommendations,matchDemandInclude,matchSupplyInclude} from './matching-recommendations';
import {businessDataScope} from './business-data-scope';
const entity={id:true,name:true};
const demandInclude={grain:true,orderItem:{include:{grain:true}},modes:{include:{mode:true}},businessEntity:{select:entity}};
const include={demand:{include:demandInclude},targetCarrier:{select:entity},recipients:{include:{carrier:{select:entity}}}};
const sample=businessDataScope;
const no=(p:string)=>`${p}-${Date.now().toString(36).toUpperCase()}-${randomUUID().slice(0,6).toUpperCase()}`;
const parse=(v:string)=>JSON.parse(v);
@Injectable()
export class MatchingService implements OnModuleInit,OnModuleDestroy {
 private timer?:NodeJS.Timeout;
 constructor(private db:Database,private audit:Audit){}
 onModuleInit(){this.timer=setInterval(()=>this.expire().catch(()=>console.warn('匹配到期状态将在下次请求重试')),60000);this.timer.unref();}
 onModuleDestroy(){if(this.timer)clearInterval(this.timer);}
 private tx<T>(fn:(tx:Prisma.TransactionClient)=>Promise<T>){return this.db.$transaction(fn,{timeout:15000,maxWait:10000,isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
 private role(req:any,type:string){if(req.user.businessEntity.type!==type)throw new ForbiddenException(type==='TRADER'?'仅贸易企业可操作':'仅物流运营商可报价');}
 private version(row:any,v:number){if(row.version!==v)throw new ConflictException('记录已更新，请刷新详情后重试');}
 private scope(req:any):any {
  const id=req.user.businessEntityId;if(req.user.businessEntity.type==='PLATFORM')return {};
  return {OR:[{createdBy:req.user.id,demand:{businessEntityId:id}},{mode:'DIRECTED',OR:[{targetCarrierId:id},{recipients:{some:{carrierId:id}}}]},{mode:'PUBLIC',status:'ACTIVE',deadline:{gt:new Date()}},{responses:{some:{carrierId:id,createdBy:req.user.id}}}]};
 }
 private reason(dto:CloseMatchDto){if(dto.reason.trim().length<2)throw new BadRequestException('请填写有效原因');}
 private range(q:MatchQuery){if(q.minQuantity!=null&&q.maxQuantity!=null&&q.minQuantity>q.maxQuantity)throw new BadRequestException('数量下限不能大于上限');if(q.departureFrom&&q.departureTo&&new Date(q.departureFrom)>new Date(q.departureTo))throw new BadRequestException('开始日期不能晚于结束日期');return {...(q.minQuantity!=null?{gte:Math.round(q.minQuantity*1000)}:{}),...(q.maxQuantity!=null?{lte:Math.round(q.maxQuantity*1000)}:{})};}
 private async row(id:string,req:any,tx:any=this.db){const r=await tx.matchPublication.findFirst({where:{id,AND:[this.scope(req)],demand:{deletedAt:null,...(req.user.businessEntity.type==='PLATFORM'?{}:{businessEntity:{status:'ACTIVE',deletedAt:null}}),...sample()}},include});if(!r)throw new NotFoundException('发布不存在或无权访问');return r;}
 private owner(p:any,req:any){this.role(req,'TRADER');if(p.demand.businessEntityId!==req.user.businessEntityId||p.createdBy!==req.user.id)throw new ForbiddenException('仅需求发布账号可操作');}
 private active(p:any){if(p.status!=='ACTIVE'||p.deadline<=new Date())throw new ConflictException('发布已关闭或截止，请重新匹配');}
 private async bump(tx:any,p:any){const c=await tx.matchPublication.updateMany({where:{id:p.id,version:p.version,status:'ACTIVE',deadline:{gt:new Date()}},data:{version:{increment:1}}});if(c.count!==1)throw new ConflictException('发布状态已变化，请刷新');}
 private async stage(tx:any,pid:string){
  const p=await tx.matchPublication.findUniqueOrThrow({where:{id:pid},include:{responses:true,demand:true}});
  const now=new Date();const valid=p.responses.filter((r:any)=>!['WITHDRAWN','REJECTED','CONFIRMED'].includes(r.status)&&new Date(parse(r.terms).validUntil)>now);
  const stage=p.matchedKg>=p.quantityKg?'MATCHED':p.matchedKg>0?'PARTIAL':p.status!=='ACTIVE'?'REMATCH':valid.some((r:any)=>r.status==='ACCEPTED')?'PENDING_CONFIRM':valid.some((r:any)=>r.version>1)?'NEGOTIATING':valid.length?'BIDDING':'WAITING';
  await tx.matchPublication.update({where:{id:pid},data:{stage}});
  const other=await tx.matchPublication.findFirst({where:{demandId:p.demandId,status:'ACTIVE',id:{not:pid},deadline:{gt:now}}});
  const ds=p.demand.matchedKg>=p.demand.quantityKg?'MATCHED':p.demand.matchedKg>0?'PARTIAL':other?.stage||(p.status==='ACTIVE'&&p.deadline>now?stage:'REMATCH');
  await tx.transportDemand.update({where:{id:p.demandId},data:{matchStage:ds}});
 }
 async expire(){return this.tx(async tx=>{const rows=await tx.matchPublication.findMany({where:{status:'ACTIVE',deadline:{lte:new Date()}},include:{demand:{select:{businessEntityId:true}}},take:200});for(const p of rows){await tx.matchPublication.update({where:{id:p.id},data:{status:'EXPIRED',closedAt:new Date(),version:{increment:1}}});await tx.auditLog.create({data:{userId:'SYSTEM',userName:'系统',role:'SYSTEM',ip:'',userAgent:'matching-expiry',businessEntityId:p.demand.businessEntityId,module:'供需匹配',objectId:p.id,action:'发布到期失效',before:JSON.stringify({status:'ACTIVE'}),after:JSON.stringify({status:'EXPIRED'}),requestId:randomUUID()}});await this.stage(tx,p.id);}const open=await tx.matchPublication.findMany({where:{status:'ACTIVE',stage:{in:['BIDDING','NEGOTIATING','PENDING_CONFIRM']},responses:{some:{status:{in:['OPEN','ACCEPTED']}}}},include:{responses:true}});for(const p of open)if(p.responses.some(r=>new Date(parse(r.terms).validUntil)<=new Date()))await this.stage(tx,p.id);});}
 private view(p:any,req:any){const own=p.demand.businessEntityId===req.user.businessEntityId&&p.createdBy===req.user.id,platform=req.user.businessEntity.type==='PLATFORM';const stored=parse(p.snapshot);const {privateInfo,...snapshot}=Object.keys(stored).length?stored:demandSnapshot(p.demand);const privateFields=privateInfo||p.demand;const carriers=p.recipients.length?p.recipients.map((r:any)=>r.carrier):p.targetCarrier?[p.targetCarrier]:[];const targetCarriers=own||platform?carriers:carriers.filter((c:any)=>c.id===req.user.businessEntityId);if(!own&&!platform&&snapshot.suppliers){snapshot.suppliers=snapshot.suppliers.filter((s:any)=>s.carrierId===req.user.businessEntityId);snapshot.supplier=snapshot.suppliers[0]||null;}if(!own&&!platform&&snapshot.supplier?.carrierId!==req.user.businessEntityId)snapshot.supplier=null;return {id:p.id,businessNo:p.businessNo,demandId:p.demandId,planRunId:p.planRunId,supplyId:p.supplyId,objectType:p.objectType,mode:p.mode,status:p.status,stage:p.stage,version:p.version,deadline:p.deadline,createdAt:p.createdAt,closedAt:p.closedAt,quoteType:p.quoteType,allowPartial:false,quantityKg:p.quantityKg,matchedKg:p.matchedKg,remainingKg:p.quantityKg-p.matchedKg,notes:p.notes,riskNotes:parse(p.riskNotes),snapshot,trader:p.demand.businessEntity,targetCarrier:own||platform||p.targetCarrierId===req.user.businessEntityId?p.targetCarrier:null,targetCarriers,own,budget:own||platform?privateFields.budgetCents:null,contact:own||platform||p.contactPublic?privateFields.contact:null,phone:own||platform||p.contactPublic?privateFields.phone:null};}
 async list(q:MatchQuery,req:any){await this.expire();const range=this.range(q);const where:any={...(Object.keys(range).length?{quantityKg:range}:{}),AND:[this.scope(req),...(q.carrierId?[{OR:[{targetCarrierId:q.carrierId},{recipients:{some:{carrierId:q.carrierId}}}]}]:[])],demand:{deletedAt:null,...(req.user.businessEntity.type==='PLATFORM'?{}:{businessEntity:{status:'ACTIVE',deletedAt:null}}),...sample(),...((q.departureFrom||q.departureTo)?{departureAt:{...(q.departureFrom?{gte:new Date(q.departureFrom)}:{}),...(q.departureTo?{lte:new Date(q.departureTo)}:{})}}:{}),...(q.grainId?{AND:[{OR:[{grainId:q.grainId},{orderItem:{grainId:q.grainId}}]}]}:{}),...(q.modeId?{modes:{some:{modeId:q.modeId}}}:{}),...(q.origin?{originRegion:{contains:q.origin}}:{}),...(q.destination?{destinationRegion:{contains:q.destination}}:{})},...(q.publicationMode?{mode:q.publicationMode}:{}),...(q.status?{status:q.status}:{}),...(q.type?{objectType:q.type}:{}),...(q.q?{OR:[{businessNo:{contains:q.q}},{demand:{name:{contains:q.q}}}]}:{})};if(q.scope==='owned')where.AND.push({createdBy:req.user.id,demand:{businessEntityId:req.user.businessEntityId}});if(q.scope==='mine')where.AND.push({OR:[{demand:{businessEntityId:req.user.businessEntityId}},{targetCarrierId:req.user.businessEntityId},{recipients:{some:{carrierId:req.user.businessEntityId}}},{responses:{some:{carrierId:req.user.businessEntityId}}}]});const [total,rows]=await this.db.$transaction([this.db.matchPublication.count({where}),this.db.matchPublication.findMany({where,include,orderBy:{createdAt:q.order},skip:(q.page-1)*q.pageSize,take:q.pageSize})]);return {total,items:rows.map(p=>this.view(p,req)),page:q.page,pageSize:q.pageSize};}
 async detail(id:string,req:any){await this.expire();const p=await this.row(id,req);const all=p.createdBy===req.user.id&&p.demand.businessEntityId===req.user.businessEntityId||req.user.businessEntity.type==='PLATFORM';const responses=await this.db.matchResponse.findMany({where:{publicationId:id,...(all?{}:{carrierId:req.user.businessEntityId,createdBy:req.user.id})},include:{rounds:{orderBy:{round:'asc'}},confirmations:{orderBy:{confirmedAt:'desc'}}},orderBy:{createdAt:'asc'}});const carriers=await this.db.businessEntity.findMany({where:{id:{in:responses.map(r=>r.carrierId)}},select:entity});return {...this.view(p,req),responses:responses.map(r=>({...r,carrier:carriers.find(c=>c.id===r.carrierId),terms:parse(r.terms),expired:new Date(parse(r.terms).validUntil)<=new Date(),rounds:r.rounds.map(v=>({...v,terms:parse(v.terms)})),confirmations:r.confirmations.map(v=>({...v,terms:parse(v.terms)}))}))};}
 async options(req:any){const trader=req.user.businessEntity.type==='TRADER';const [carriers,dicts,demands]=await Promise.all([this.db.businessEntity.findMany({where:{type:'CARRIER',status:'ACTIVE',deletedAt:null,...sample()},select:entity}),this.db.dictionary.findMany({where:{enabled:true,group:{in:['粮食品种','运输方式']}}}),trader?this.db.transportDemand.findMany({where:{businessEntityId:req.user.businessEntityId,createdBy:req.user.id,deletedAt:null,status:{in:['DRAFT','PUBLISHED']},...sample()},include:{publications:{where:{status:'ACTIVE',deadline:{gt:new Date()}},select:{id:true}},planRuns:{where:{status:'SELECTED'},select:{id:true,businessNo:true,version:true,demandVersion:true,selectedPlanId:true}}},orderBy:{createdAt:'desc'}}):[]]);return {carriers,grains:dicts.filter(d=>d.group==='粮食品种'),modes:dicts.filter(d=>d.group==='运输方式'),demands:demands.filter(d=>d.quantityKg>d.matchedKg&&!d.publications.length).map(d=>({id:d.id,name:d.name,businessNo:d.businessNo,version:d.version,quantityKg:d.quantityKg,matchedKg:d.matchedKg,departureAt:d.departureAt,plans:d.planRuns}))};}
 async supplies(q:MatchQuery,req:any){
  const now=new Date(),range=this.range(q),owned=q.scope==='owned';
  const conditions:any[]=[...(owned?[]:supplyAvailability(now).AND as any[]),...(owned?[{businessEntityId:req.user.businessEntityId,createdBy:req.user.id}]:[]),...(q.departureTo?[{OR:[{serviceStart:null},{serviceStart:{lte:new Date(q.departureTo)}}]}]:[]),...(q.departureFrom?[{OR:[{serviceEnd:null},{serviceEnd:{gte:new Date(q.departureFrom)}}]}]:[]),...(q.q?[{OR:[{name:{contains:q.q}},{businessNo:{contains:q.q}},{businessEntity:{name:{contains:q.q}}}]}]:[]),...(q.grainId?[{OR:[{grains:{none:{}}},{grains:{some:{grainId:q.grainId}}}]}]:[])];
  if(Object.keys(range).length){if(range.gte!=null)conditions.push({capacityKg:{gte:range.gte}});if(range.lte!=null)conditions.push({OR:[{minKg:null},{minKg:{lte:range.lte}}]});}
  const where:any={AND:conditions,...(q.carrierId?{businessEntityId:q.carrierId}:{}),status:owned?{in:['PUBLISHED','PAUSED','EXPIRED']}:'PUBLISHED',deletedAt:null,businessEntity:{status:'ACTIVE',deletedAt:null},...sample(),...(q.modeId?{modeId:q.modeId}:{}),...(q.origin?{originRegion:{contains:q.origin}}:{}),...(q.destination?{destinationRegion:{contains:q.destination}}:{})};
  const [total,rows]=await this.db.$transaction([this.db.transportSupply.count({where}),this.db.transportSupply.findMany({where,include:{businessEntity:{select:entity},mode:true,grains:{include:{grain:true}}},orderBy:{createdAt:q.order},skip:(q.page-1)*q.pageSize,take:q.pageSize})]);
  return {total,items:rows.map(s=>({id:s.id,name:s.businessEntity.name,businessNo:s.businessNo,carrier:s.businessEntity,status:s.status,version:s.version,mode:s.mode.label,grains:s.grains.map(g=>g.grain.label),origin:s.originRegion,destination:s.destinationRegion,capacityKg:s.capacityKg,minKg:s.minKg,maxKg:s.maxKg,loadingType:s.loadingType,bulkPriceCents:s.bulkPriceCents,container20PriceCents:s.container20PriceCents,container40PriceCents:s.container40PriceCents,resourceDescription:s.resourceDescription,capabilities:s.capabilities,serviceStart:s.serviceStart,serviceEnd:s.serviceEnd,referencePriceCents:s.referencePriceCents,priceUnit:s.priceUnit,validUntil:s.validUntil})),page:q.page,pageSize:q.pageSize};
 }

 async recommendations(kind:string,id:string,req:any){
  if(kind==='demand'&&req.user.businessEntity.type==='TRADER'){
   const p=await this.db.matchPublication.findFirst({where:{id,createdBy:req.user.id,demand:{businessEntityId:req.user.businessEntityId,deletedAt:null,...sample()}},include:{demand:{include:matchDemandInclude},recipients:true,responses:{select:{carrierId:true}}}});
   if(!p)throw new NotFoundException('不是本人发布的信息，无法查看匹配推荐');
   const items=await demandRecommendations(this.db,p);return {items,total:items.length};
  }
  if(kind==='supply'&&req.user.businessEntity.type==='CARRIER'){
   const s=await this.db.transportSupply.findFirst({where:{id,businessEntityId:req.user.businessEntityId,createdBy:req.user.id,deletedAt:null,...sample()},include:matchSupplyInclude});
   if(!s)throw new NotFoundException('不是本人发布的信息，无法查看匹配推荐');
   const valid=s.status==='PUBLISHED'&&(!s.validFrom||s.validFrom<=new Date())&&(!s.validUntil||s.validUntil>new Date())&&(!s.serviceEnd||s.serviceEnd>new Date());
   const items=valid?await supplyRecommendations(this.db,s,req.user):[];return {items,total:items.length};
  }
  throw new ForbiddenException('仅发布账号可查看自己的匹配推荐');
 }
 async mine(q:MatchQuery,req:any){
  const kind=req.user.businessEntity.type==='TRADER'?'demand':'supply';
  if(req.user.businessEntity.type==='PLATFORM')return {items:[],total:0,page:q.page,pageSize:q.pageSize};
  const query=Object.assign(new MatchQuery(),q,{scope:'owned'}),data=kind==='demand'?await this.list(query,req):await this.supplies(query,req);
  const items=await Promise.all(data.items.map(async row=>{try{const recommendations=await this.recommendations(kind,row.id,req);return {...row,recommendations:recommendations.items,recommendationCount:recommendations.total};}catch{return {...row,recommendations:[],recommendationError:'匹配推荐暂时不可用，请重试'};}}));
  return {...data,items};
 }
 async myPublications(req:any){
  this.role(req,'TRADER');const rows=await this.db.matchPublication.findMany({where:{createdBy:req.user.id,status:'ACTIVE',deadline:{gt:new Date()},demand:{businessEntityId:req.user.businessEntityId,deletedAt:null,departureAt:{gt:new Date()},...sample()}},select:{id:true,version:true,businessNo:true,snapshot:true,quantityKg:true,matchedKg:true},orderBy:{createdAt:'desc'}});
  return {items:rows.filter(p=>p.quantityKg>p.matchedKg).map(p=>({id:p.id,version:p.version,businessNo:p.businessNo,name:parse(p.snapshot).name,quantity:(p.quantityKg-p.matchedKg)/1000}))};
 }
 async invite(id:string,dto:MatchInviteDto,req:any){
  this.role(req,'TRADER');return this.tx(async tx=>{
   const p=await this.row(id,req,tx);this.owner(p,req);this.active(p);
   if(p.quantityKg<=p.matchedKg)throw new ConflictException('运输数量已全部落实');
   if(await tx.businessEntity.count({where:{id:{in:dto.carrierIds},type:'CARRIER',status:'ACTIVE',deletedAt:null,...sample()}})!==dto.carrierIds.length)throw new BadRequestException('所选物流运营商已停用或不存在');
   const selectedSupply=dto.supplyId?await tx.transportSupply.findFirst({where:{id:dto.supplyId,businessEntityId:{in:dto.carrierIds},status:'PUBLISHED',deletedAt:null,...supplyAvailability(),...sample()}}):null;
   if(dto.supplyId&&(!selectedSupply||dto.carrierIds.length!==1))throw new ConflictException('运力已变化，请重新选择');
   const current=new Set(p.recipients.map((r:any)=>r.carrierId));if(p.targetCarrierId)current.add(p.targetCarrierId);
   const added=dto.carrierIds.filter(cid=>!current.has(cid));if(!added.length)return {id,invitedCarrierIds:dto.carrierIds};
   this.version(p,dto.version);if(current.size+added.length>10)throw new BadRequestException('一份发布最多邀请10家物流运营商');await this.bump(tx,p);
   if(p.targetCarrierId&&!p.recipients.some((r:any)=>r.carrierId===p.targetCarrierId))await tx.matchRecipient.create({data:{publicationId:id,carrierId:p.targetCarrierId,supplyId:p.supplyId,invitedBy:p.createdBy,invitedAt:p.createdAt}});
   for(const carrierId of added)await tx.matchRecipient.create({data:{publicationId:id,carrierId,supplyId:selectedSupply?.id,supplyVersion:selectedSupply?.version,invitedBy:req.user.id,invitedAt:new Date()}});
   if(p.mode==='DIRECTED'&&current.size+added.length>1)await tx.matchPublication.update({where:{id},data:{targetCarrierId:null,supplyId:null}});
   await this.audit.write(tx,req,'供需匹配',id,'邀请报价',undefined,{carrierIds:added,supplyId:dto.supplyId});return {id,invitedCarrierIds:dto.carrierIds};
  });
 }

 async publish(dto:MatchPublishDto,req:any){this.role(req,'TRADER');await this.expire();return this.tx(async tx=>{
  const d=await tx.transportDemand.findFirst({where:{id:dto.demandId,businessEntityId:req.user.businessEntityId,createdBy:req.user.id,deletedAt:null,...sample()},include:demandInclude});if(!d)throw new NotFoundException('需求不存在');this.version(d,dto.version);
  if(!['DRAFT','PUBLISHED'].includes(d.status)||d.matchedKg>=d.quantityKg)throw new ConflictException('需求已取消或全部匹配');
  if(await tx.matchPublication.count({where:{demandId:d.id,status:'ACTIVE'}}))throw new ConflictException('该需求已有有效发布，请在详情中关闭后重新匹配');
  if(new Date(dto.deadline)<=new Date()||new Date(dto.deadline)>d.departureAt)throw new BadRequestException('截止时间须晚于现在且不晚于发运时间');
  if(dto.targetCarrierIds&&dto.targetCarrierId)throw new BadRequestException('请使用一种指定企业选择方式');const targets=dto.targetCarrierIds||(dto.targetCarrierId?[dto.targetCarrierId]:[]);let target=targets.length===1?targets[0]:undefined,plan:any=null;const risks:string[]=[];const quantityKg=d.quantityKg-d.matchedKg;
  if(dto.supplyId){const s=await tx.transportSupply.findFirst({where:{id:dto.supplyId,status:'PUBLISHED',deletedAt:null,...supplyAvailability(),businessEntity:{status:'ACTIVE',deletedAt:null},...sample()},include:{grains:true}});if(!s)throw new ConflictException('供给已失效，请重新选择');if(dto.mode!=='DIRECTED'||target!==s.businessEntityId)throw new BadRequestException('从供给匹配必须定向给该供给所属承运商');if(quantityKg>s.capacityKg||s.minKg&&quantityKg<s.minKg||s.maxKg&&quantityKg>s.maxKg)risks.push('需求数量超出供给承接范围');if(s.serviceStart&&d.departureAt<s.serviceStart||s.serviceEnd&&(d.departureAt>s.serviceEnd||d.arrivalAt&&d.arrivalAt>s.serviceEnd))risks.push('运输时间与供给服务窗口不一致');if(s.grains.length&&!s.grains.some(g=>g.grainId===(d.orderItem?.grainId||d.grainId)))risks.push('供给未声明适配该粮食品种');if(!d.modes.some(m=>m.modeId===s.modeId))risks.push('供给运输方式与需求不一致');if(d.originCodes.split('/')[1]!==s.originCodes.split('/')[1]||d.destinationCodes.split('/')[1]!==s.destinationCodes.split('/')[1])risks.push('起讫城市与供给覆盖范围不一致');if(risks.length&&!dto.riskAcknowledged)throw new BadRequestException(risks.join('；')+'。请确认风险后再发布');}
  if(dto.mode==='DIRECTED'){if(!targets.length||await tx.businessEntity.count({where:{id:{in:targets},type:'CARRIER',status:'ACTIVE',deletedAt:null,...sample()}})!==targets.length)throw new BadRequestException('请选择有效物流运营商');}else if(targets.length)throw new BadRequestException('公开发布不能指定物流运营商');
  if(dto.planRunId){const run=await tx.planRun.findFirst({where:{id:dto.planRunId,businessEntityId:req.user.businessEntityId,demandId:d.id,status:'SELECTED'},include:{candidates:{include:{segments:{orderBy:{sequence:'asc'}}}}}});if(!run||run.demandVersion!==d.version||d.matchedKg>0)throw new ConflictException('所选方案与当前需求版本不一致，请重新求解并选择');const latest=await tx.planRun.findFirst({where:{groupId:run.groupId},orderBy:{version:'desc'}});if(latest?.id!==run.id)throw new ConflictException('请选择最新版本的完整方案');const c=run.candidates.find(c=>c.id===run.selectedPlanId);if(!c)throw new ConflictException('请先选择完整方案');plan={runId:run.id,businessNo:run.businessNo,version:run.version,name:c.name,warnings:parse(c.warnings),segments:c.segments.map(s=>({sequence:s.sequence,mode:s.mode,origin:parse(s.origin),destination:parse(s.destination),lineName:s.lineName,geometryId:s.geometryId,routeProfile:s.routeProfile,service:parse(s.priceSnapshot).service||null}))};}
  const p=await tx.matchPublication.create({data:{businessNo:no('FB'),demandId:d.id,objectType:plan?'PLAN':'DEMAND',planRunId:dto.planRunId,supplyId:dto.supplyId,mode:dto.mode,targetCarrierId:target,recipients:targets.length?{create:targets.map(carrierId=>({carrierId,supplyId:targets.length===1?dto.supplyId:undefined,invitedBy:req.user.id,invitedAt:new Date()}))}:undefined,deadline:new Date(dto.deadline),quoteType:dto.quoteType,budgetPublic:false,contactPublic:dto.contactPublic,notes:dto.notes||'',demandVersion:d.version+1,createdBy:req.user.id,snapshot:JSON.stringify({...demandSnapshot(d),plan}),allowPartial:false,quantityKg,riskNotes:JSON.stringify(risks)}});
  const changed=await tx.transportDemand.updateMany({where:{id:d.id,version:d.version},data:{status:'PUBLISHED',matchStage:d.matchedKg?'PARTIAL':'WAITING',version:{increment:1},updatedBy:req.user.id}});if(changed.count!==1)throw new ConflictException('需求已更新');await this.audit.write(tx,req,'供需匹配',p.id,'发布匹配',undefined,{demandId:d.id,mode:p.mode,objectType:p.objectType,quantityKg});return {id:p.id};
 });}
 private terms(dto:QuoteTermsDto,p:any){if(!dto)throw new BadRequestException('请填写完整报价条款');const quantityKg=Math.round(dto.quantity*1000),priceCents=Math.round(dto.price*100),totalCents=dto.unit==='TOTAL'?priceCents:Math.round(priceCents*quantityKg/1000);if(dto.unit!==p.quoteType)throw new BadRequestException('报价单位必须与发布要求一致');if(quantityKg!==p.quantityKg-p.matchedKg)throw new BadRequestException('报价数量须覆盖完整待承接数量');if(totalCents>2000000000||totalCents<1)throw new BadRequestException('报价总额超出支持范围');if(new Date(dto.validUntil)<=new Date()||new Date(dto.validUntil)>p.deadline)throw new BadRequestException('报价有效期须晚于现在且不超过响应截止时间');if(new Date(dto.departureAt)<=new Date()||new Date(dto.arrivalAt)<=new Date(dto.departureAt)||new Date(dto.validUntil)>new Date(dto.departureAt))throw new BadRequestException('请检查报价有效期、发运和到达时间');if(p.objectType==='PLAN'&&!dto.followOriginalPlan&&!dto.note.trim())throw new BadRequestException('调整原方案时须说明调整内容');return {...dto,quantityKg,priceCents,totalCents};}
 private async record(tx:any,r:any,action:string,terms:any,note:string,req:any){return tx.negotiationRound.create({data:{responseId:r.id,round:r.version,action,terms:JSON.stringify(terms),authorEntityId:req.user.businessEntityId,authorId:req.user.id,authorName:req.user.displayName,note}});}
 async quote(id:string,dto:QuoteDto,req:any){this.role(req,'CARRIER');return this.tx(async tx=>{const p=await this.row(id,req,tx);this.active(p);this.version(p,dto.publicationVersion);if(p.mode==='DIRECTED'&&p.targetCarrierId!==req.user.businessEntityId&&!p.recipients.some((r:any)=>r.carrierId===req.user.businessEntityId))throw new ForbiddenException('该发布仅限指定承运商响应');const terms=this.terms(dto.terms,p);if(await tx.matchResponse.findUnique({where:{publicationId_createdBy:{publicationId:id,createdBy:req.user.id}}}))throw new ConflictException('已有报价，请在议价记录中修订报价');await this.bump(tx,p);const r=await tx.matchResponse.create({data:{publicationId:id,carrierId:req.user.businessEntityId,createdBy:req.user.id,lastAuthorId:req.user.businessEntityId,terms:JSON.stringify(terms)}});await this.record(tx,r,'OFFER',terms,terms.note,req);await this.stage(tx,id);await this.audit.write(tx,req,'供需匹配',id,'提交报价',undefined,{responseId:r.id,totalCents:terms.totalCents});return {id:r.id};});}
 private async response(id:string,req:any,tx:any){const r=await tx.matchResponse.findUnique({where:{id}});if(!r)throw new NotFoundException('报价不存在');const p=await this.row(r.publicationId,req,tx);if(!(p.createdBy===req.user.id&&p.demand.businessEntityId===req.user.businessEntityId||r.createdBy===req.user.id&&r.carrierId===req.user.businessEntityId)||req.user.businessEntity.type==='PLATFORM')throw new ForbiddenException('仅议价双方可操作');if(!await tx.businessEntity.findFirst({where:{id:r.carrierId,status:'ACTIVE',deletedAt:null}}))throw new ConflictException('承运主体已停用');return {r,p};}
 async negotiate(id:string,dto:NegotiateDto,req:any){return this.tx(async tx=>{const {r,p}=await this.response(id,req,tx);this.active(p);this.version(p,dto.publicationVersion);this.version(r,dto.version);if(r.status==='CONFIRMED')throw new ConflictException('已确认承运，请先取消承运确认');let terms=parse(r.terms);if(dto.action==='COUNTER'){if(['WITHDRAWN','REJECTED'].includes(r.status)&&req.user.businessEntityId!==r.carrierId)throw new ConflictException('请等待承运商重新报价');terms=this.terms(dto.terms!,p);}else{if(!['OPEN','ACCEPTED'].includes(r.status))throw new ConflictException('该报价已结束，请重新报价');if(dto.action!=='WITHDRAW'&&r.lastAuthorId===req.user.businessEntityId)throw new BadRequestException('请等待对方回应，不能接受或拒绝自己的报价');if(dto.action==='WITHDRAW'&&r.lastAuthorId!==req.user.businessEntityId)throw new BadRequestException('只能撤回自己提出的条款');if(dto.action==='ACCEPT'){if(r.status==='ACCEPTED')throw new ConflictException('该报价已接受');this.terms(terms,p);}}
  await this.bump(tx,p);const status=({COUNTER:'OPEN',ACCEPT:'ACCEPTED',REJECT:'REJECTED',WITHDRAW:'WITHDRAWN'} as any)[dto.action];const next=await tx.matchResponse.update({where:{id,version:r.version},data:{version:{increment:1},status,terms:JSON.stringify(terms),...(dto.action==='COUNTER'?{lastAuthorId:req.user.businessEntityId}:{}),acceptedRound:dto.action==='ACCEPT'?r.version:null}});await this.record(tx,next,dto.action,terms,dto.note,req);await this.stage(tx,p.id);await this.audit.write(tx,req,'供需匹配',p.id,'议价'+dto.action,{responseId:id,version:r.version},{responseId:id,version:next.version});return {id};});}
 async confirm(id:string,dto:ConfirmDto,req:any){this.role(req,'TRADER');return this.tx(async tx=>{const {r,p}=await this.response(id,req,tx);this.owner(p,req);this.active(p);this.version(p,dto.publicationVersion);this.version(r,dto.version);if(r.status!=='ACCEPTED'||!r.acceptedRound)throw new ConflictException('请先由双方接受当前报价条款');const terms=this.terms(parse(r.terms),p);await this.bump(tx,p);const updated=await tx.transportDemand.updateMany({where:{id:p.demandId,version:p.demand.version,matchedKg:{lte:p.demand.quantityKg-terms.quantityKg}},data:{matchedKg:{increment:terms.quantityKg},version:{increment:1},updatedBy:req.user.id}});if(updated.count!==1)throw new ConflictException('剩余可承运数量不足或需求已更新');const c=await tx.carrierConfirmation.create({data:{businessNo:no('CY'),publicationId:p.id,responseId:r.id,demandId:p.demandId,traderId:p.demand.businessEntityId,carrierId:r.carrierId,quantityKg:terms.quantityKg,totalCents:terms.totalCents,terms:JSON.stringify(terms),confirmedBy:req.user.id}});await tx.matchResponse.update({where:{id},data:{status:'CONFIRMED',version:{increment:1}}});await tx.matchPublication.update({where:{id:p.id},data:{matchedKg:{increment:terms.quantityKg},...(p.matchedKg+terms.quantityKg>=p.quantityKg?{status:'MATCHED',closedAt:new Date()}:{})}});await this.stage(tx,p.id);await this.audit.write(tx,req,'供需匹配',p.id,'确认承运',undefined,{confirmationId:c.id,totalCents:c.totalCents,quantityKg:c.quantityKg});return c;});}
 async close(id:string,dto:CloseMatchDto,req:any){this.reason(dto);return this.tx(async tx=>{const p=await this.row(id,req,tx);this.owner(p,req);this.version(p,dto.version);this.active(p);await this.bump(tx,p);await tx.matchPublication.update({where:{id},data:{status:'CLOSED',closedAt:new Date(),notes:p.notes+'\n关闭原因：'+dto.reason}});await this.stage(tx,id);await this.audit.write(tx,req,'供需匹配',id,'关闭发布',undefined,{reason:dto.reason});return {id};});}
 async cancel(id:string,dto:CloseMatchDto,req:any){this.reason(dto);this.role(req,'TRADER');return this.tx(async tx=>{const c=await tx.carrierConfirmation.findUnique({where:{id},include:{publication:{select:{createdBy:true}}}});if(!c||c.traderId!==req.user.businessEntityId||c.publication.createdBy!==req.user.id)throw new NotFoundException('承运确认不存在');if(await tx.contractPackage.count({where:{confirmationId:id}}))throw new ConflictException('已生成合同包，请在合同管理中处理变更或终止');this.version(c,dto.version);if(c.status!=='CONFIRMED')throw new ConflictException('承运确认已取消');await tx.carrierConfirmation.update({where:{id,version:dto.version},data:{status:'CANCELLED',version:{increment:1},cancelledAt:new Date(),cancelReason:dto.reason}});const released=await tx.transportDemand.updateMany({where:{id:c.demandId,matchedKg:{gte:c.quantityKg}},data:{matchedKg:{decrement:c.quantityKg},version:{increment:1},updatedBy:req.user.id}});if(released.count!==1)throw new ConflictException('需求数量不一致，请联系平台');const p=await tx.matchPublication.findUniqueOrThrow({where:{id:c.publicationId}});await tx.matchPublication.update({where:{id:p.id},data:{matchedKg:{decrement:c.quantityKg},version:{increment:1},...(p.status==='MATCHED'?{status:'CLOSED'}:{})}});await tx.matchResponse.update({where:{id:c.responseId},data:{status:'WITHDRAWN',version:{increment:1},acceptedRound:null}});await this.stage(tx,p.id);await this.audit.write(tx,req,'供需匹配',p.id,'取消承运确认',{confirmationId:id},{reason:dto.reason});return {id};});}
}
