import {Injectable,BadRequestException,ForbiddenException,NotFoundException,ConflictException} from '@nestjs/common';
import {randomUUID} from 'node:crypto';
import {Database} from './database';import {Audit} from './audit';import {AmapService,hash,meters} from './amap';
import {SolveDto,NodeDto,LineDto,PriceDto,GeometryDto,PlanSelectDto,PlanPublishDto,PlanQuery} from './planning.dto';
import {estimateSegment,segmentMetrics,pointRegion} from './planning-estimates';
import {demandSnapshot} from './match-snapshot';
import {TransportService} from './transport.service';
import {recommendPlans} from './planning-recommendations';
import {findCorridorChains,modeFamily,familyLabel} from './planning-network';
import {adviseCorridors} from './planning-advisor';
import {supplierRecommendations} from './planning-suppliers';
import {publishPlan} from './planning-publication';
import {checkAgentOperation} from './agent-operation';
import {businessDataScope} from './business-data-scope';
import {storedDemandPoint} from './demand-location';
import {budgetBounds,filterByTotalBudget} from './planning-budget';
const sample=businessDataScope;
const lineInclude={origin:true,destination:true,geometry:{select:{id:true,routeProfile:true,source:true,sourceRef:true,queriedAt:true}},prices:{orderBy:{validFrom:'desc' as const}}};
const runInclude={candidates:{orderBy:{rank:'asc' as const},include:{segments:{orderBy:{sequence:'asc' as const},include:{geometry:true}}}}};
const number=(prefix:string)=>`${prefix}-${Date.now().toString(36).toUpperCase()}-${randomUUID().slice(0,6).toUpperCase()}`;
@Injectable()
export class PlanningService {
 private solving=new Set<string>();
 constructor(private db:Database,private audit:Audit,private amap:AmapService,private transport:TransportService){}
 async examples(){throw new ForbiddenException('请填写运输条件或从已有运输需求带入');}
 async exampleDemand(_req:any){throw new ForbiddenException('请从交易订单创建运输需求，或直接填写求解条件');}
 async publish(id:string,dto:PlanPublishDto,req:any){return publishPlan(this.db,this.audit,id,dto,req);}
 async suppliers(id:string,candidateId:string,req:any){const run=await this.run(id,req);const candidate=run.candidates.find(c=>c.id===candidateId);if(!candidate)throw new BadRequestException('请选择本次求解中的有效方案');const items=await supplierRecommendations(this.db,run.input,candidate);return {items:items.slice(0,10),total:items.length};}
 private platform(req:any){if(req.user.businessEntity.type!=='PLATFORM')throw new ForbiddenException('仅平台可维护公共线路与参考价格');}
 private scope(req:any){return req.user.businessEntity.type==='PLATFORM'?{}:{businessEntityId:req.user.businessEntityId};}
 private version(row:any,v?:number){if(!row||row.version!==v)throw new ConflictException('数据已更新，请刷新后重试');}
 private async grains(ids:string[]){if(await this.db.dictionary.count({where:{id:{in:ids},group:'粮食品种',enabled:true}})!==ids.length)throw new BadRequestException('请选择有效粮食品种');}
 private priceView(p:any){return {...p,rate:p.rateMillis/1000};}
 private lineView(l:any){return {...l,serviceInfo:JSON.parse(l.serviceInfo||'{}'),distanceKm:l.distanceMeters?l.distanceMeters/1000:null,durationHours:l.durationSeconds/3600,capacity:l.capacityKg==null?null:l.capacityKg/1000,grainIds:JSON.parse(l.grainIds),loadingTypes:JSON.parse(l.loadingTypes),prices:l.prices.map((p:any)=>this.priceView(p))};}
 async options(){return {nodes:await this.db.transportNode.findMany({where:{enabled:true,quality:{in:['PROVIDER','VERIFIED']}},orderBy:{name:'asc'}}),grains:await this.db.dictionary.findMany({where:{group:'粮食品种',enabled:true},orderBy:{sort:'asc'}}),lines:await this.db.transportLine.findMany({where:{enabled:true,quality:{in:['VERIFIED','PUBLIC_REFERENCE']},...sample()},select:{id:true,name:true,mode:true,originId:true,destinationId:true}})};}
 async nodes(q:PlanQuery){const where={...(q.q?{OR:[{name:{contains:q.q}},{city:{contains:q.q}}]}:{})};const [total,items]=await this.db.$transaction([this.db.transportNode.count({where}),this.db.transportNode.findMany({where,orderBy:{updatedAt:q.order},skip:(q.page-1)*q.pageSize,take:q.pageSize})]);return {items,total,page:q.page,pageSize:q.pageSize};}
 async saveNode(dto:NodeDto,req:any,id?:string){this.platform(req);const {version,nodeId,...data}=dto;return this.db.$transaction(async tx=>{const old=id?await tx.transportNode.findUnique({where:{id}}):null;if(id)this.version(old,version);const row=id?await tx.transportNode.update({where:{id,version},data:{...data,verifiedAt:new Date(),version:{increment:1}}}):await tx.transportNode.create({data:{...data,verifiedAt:new Date()}});if(old&&(old.lng!==row.lng||old.lat!==row.lat))await tx.transportLine.updateMany({where:{OR:[{originId:id},{destinationId:id}]},data:{quality:'DRAFT',geometryId:null,version:{increment:1}}});await this.audit.write(tx,req,'运输节点',row.id,id?'维护运输节点':'新增运输节点',old,row);return row;});}
 async lines(q:PlanQuery){const where={...sample(),...(q.q?{OR:[{name:{contains:q.q}},{businessNo:{contains:q.q}},{origin:{name:{contains:q.q}}},{destination:{name:{contains:q.q}}}]}:{}),...(q.mode?{mode:q.mode}:{}),...(q.status?{enabled:q.status==='ACTIVE'}:{})};const [total,items]=await this.db.$transaction([this.db.transportLine.count({where}),this.db.transportLine.findMany({where,include:lineInclude,orderBy:{updatedAt:q.order},skip:(q.page-1)*q.pageSize,take:q.pageSize})]);return {items:items.map(l=>this.lineView(l)),total,page:q.page,pageSize:q.pageSize};}
 async line(id:string){const row=await this.db.transportLine.findFirst({where:{id,...sample()},include:lineInclude});if(!row)throw new NotFoundException('线路不存在');return this.lineView(row);}
 async saveLine(dto:LineDto,req:any,id?:string){this.platform(req);await this.grains(dto.grainIds);if(!dto.loadingTypes.length)throw new BadRequestException('至少选择一种装载形式');if(dto.originId===dto.destinationId)throw new BadRequestException('起讫节点不能相同');const nodes=await this.db.transportNode.findMany({where:{id:{in:[dto.originId,dto.destinationId]},enabled:true,quality:{not:'DRAFT'}}});if(nodes.length!==2)throw new BadRequestException('请选择两个已核验或供应商定位的有效节点');const origin=nodes.find(n=>n.id===dto.originId)!,destination=nodes.find(n=>n.id===dto.destinationId)!;
  if(dto.mode==='RAIL'&&[origin,destination].some(n=>n.type!=='RAIL')||dto.mode==='WATER'&&[origin,destination].some(n=>n.type!=='PORT'))throw new BadRequestException('铁路线路须连接铁路站点，水运线路须连接港口');
  const road=dto.mode==='ROAD'?(await this.amap.routes(origin,destination))[0]:null;
  const {version,distanceKm,durationHours,capacity,grainIds,loadingTypes,...fields}=dto;
  return this.db.$transaction(async tx=>{const old=id?await tx.transportLine.findUnique({where:{id}}):null;if(id)this.version(old,version);const changed=old&&(old.originId!==dto.originId||old.destinationId!==dto.destinationId||old.mode!==dto.mode||old.distanceMeters!==Math.round(distanceKm*1000));const data={...fields,distanceMeters:road?.distanceMeters??Math.round(distanceKm*1000),durationSeconds:road?.durationSeconds??Math.round(durationHours*3600),capacityKg:capacity==null?null:Math.round(capacity*1000),grainIds:JSON.stringify(grainIds),loadingTypes:JSON.stringify(loadingTypes),geometryId:road?.id??(changed?null:old?.geometryId),...(road?{source:'AMAP_V5_DRIVING',sourceRef:road.id,sourceUrl:road.sourceRef}:{})};const row=id?await tx.transportLine.update({where:{id,version},data:{...data,version:{increment:1}}}):await tx.transportLine.create({data:{...data,businessNo:number('XL'),isTestData:false}});await this.audit.write(tx,req,'运输线路',row.id,id?'维护运输线路':'新增运输线路',old,row);return row;});
 }
 async prices(q:PlanQuery){const where={lineId:q.lineId||null,...sample()};const [total,items]=await this.db.$transaction([this.db.routePrice.count({where}),this.db.routePrice.findMany({where,orderBy:{validFrom:'desc'},skip:(q.page-1)*q.pageSize,take:q.pageSize})]);return {items:items.map(p=>this.priceView(p)),total,page:q.page,pageSize:q.pageSize};}
 async savePrice(dto:PriceDto,req:any,id?:string){this.platform(req);if(dto.grainId)await this.grains([dto.grainId]);if(dto.lineId)await this.line(dto.lineId);if(!dto.lineId&&dto.unit!=='PER_TON_KM')throw new BadRequestException('通用公路价格使用元/吨公里');const start=new Date(dto.validFrom),end=new Date(dto.validUntil);if(end<=start)throw new BadRequestException('价格结束时间必须晚于开始时间');const {version,rate,...fields}=dto;return this.db.$transaction(async tx=>{const old=id?await tx.routePrice.findUnique({where:{id}}):null;if(id){this.version(old,version);if(old!.lineId!==(dto.lineId||null)||old!.grainId!==(dto.grainId||null))throw new BadRequestException('编辑价格不能改变所属线路或粮种');}if(dto.enabled&&await tx.routePrice.count({where:{id:{not:id||''},lineId:dto.lineId||null,grainId:dto.grainId||null,enabled:true,validFrom:{lt:end},validUntil:{gt:start}}}))throw new ConflictException('同一线路与粮种的价格有效期不能重叠');const data={...fields,lineId:dto.lineId||null,grainId:dto.grainId||null,rateMillis:Math.round(rate*1000),validFrom:start,validUntil:end};const row=id?await tx.routePrice.update({where:{id,version},data:{...data,version:{increment:1}}}):await tx.routePrice.create({data:{...data,isTestData:false}});await this.audit.write(tx,req,'线路价格',row.id,id?'维护参考价格':'新增参考价格',old,row);return this.priceView(row);});}
 async importGeometry(id:string,dto:GeometryDto,req:any){this.platform(req);const line=await this.line(id);this.version(line,dto.version);if(line.mode==='ROAD')throw new BadRequestException('公路几何必须来自正式道路路线服务');if(line.mode==='RAIL'&&dto.routeProfile!=='VERIFIED_RAIL'||line.mode==='WATER'&&dto.routeProfile==='VERIFIED_RAIL')throw new BadRequestException('几何来源类型与运输方式不符');const points=dto.coordinates;if(points.length<3||points.some(p=>!Array.isArray(p)||p.length!==2||!p.every(Number.isFinite)||p[0]<73||p[0]>136||p[1]<3||p[1]>54))throw new BadRequestException('请导入3至50000个有效GCJ-02坐标点');if(meters(line.origin,{lng:points[0][0],lat:points[0][1]})>2000||meters(line.destination,{lng:points.at(-1)![0],lat:points.at(-1)![1]})>2000)throw new BadRequestException('几何起讫点与线路节点相差超过2公里');let length=0;for(let i=1;i<points.length;i++)length+=meters({lng:points[i-1][0],lat:points[i-1][1]},{lng:points[i][0],lat:points[i][1]});if(length<line.distanceMeters*.5||length>line.distanceMeters*1.5)throw new BadRequestException('几何长度与线路里程不一致，请核验原始数据');return this.db.$transaction(async tx=>{const geometry=await tx.routeGeometry.create({data:{cacheKey:hash({lineId:id,points}),pathIndex:0,mode:line.mode,routeProfile:dto.routeProfile,coordinates:JSON.stringify(points),distanceMeters:line.distanceMeters,durationSeconds:line.durationSeconds,source:dto.source,sourceRef:dto.sourceRef,expiresAt:new Date('2099-01-01'),checksum:hash(points)}});await tx.transportLine.update({where:{id,version:dto.version},data:{geometryId:geometry.id,version:{increment:1}}});await this.audit.write(tx,req,'运输线路',id,'导入可追溯线路几何',undefined,{geometryId:geometry.id,source:dto.source,sourceRef:dto.sourceRef,pointCount:points.length});return {geometryId:geometry.id,pointCount:points.length};});}
 async demandInput(id:string,req:any,locate=true){const d=await this.db.transportDemand.findFirst({where:{id,deletedAt:null,...sample(),...this.scope(req)},include:{orderItem:{include:{grain:true,tradeOrder:true}},modes:{include:{mode:true}}}});if(!d)throw new NotFoundException('需求不存在或无权访问');if(d.status==='CANCELLED')throw new ConflictException('已取消需求不能求解');
  const savedOrigin=storedDemandPoint(d.originPoint),savedDestination=storedDemandPoint(d.destinationPoint);
  const nodes=locate&&(!savedOrigin||!savedDestination)?await this.db.transportNode.findMany({where:{enabled:true,quality:{in:['PROVIDER','VERIFIED']}}}):[];
  const match=async(address:string,region:string)=>{if(!locate)return null;const city=region.split(' / ')[1]||'';const text=address.trim().replace(/\s|\//g,'');const local=nodes.filter(n=>(!city||n.city===city)&&(text===n.name||text===n.province+n.city+n.district+n.name||text===n.address||(text.endsWith(n.name)&&text.includes(n.city))));if(local.length===1)return {name:address,nodeId:local[0].id,lng:local[0].lng,lat:local[0].lat,matchKind:'NODE',matchedAddress:local[0].name};try{return await this.amap.locate(address,city);}catch{return null;}};
  const origin=savedOrigin||await match(d.originAddress,d.originRegion),destination=savedDestination||await match(d.destinationAddress,d.destinationRegion);
  const searchAddress=(address:string,region:string)=>{const city=region.split(' / ')[1];return city&&address.includes(city)?address:region.replaceAll(' / ','')+address;};
  return {origin,destination,demandId:d.id,demandVersion:d.version,isTestData:d.isTestData,businessNo:d.businessNo,orderNo:d.orderItem?.tradeOrder.businessNo||null,grainId:d.orderItem?.grainId||d.grainId,cargoName:d.orderItem?.cargoName||d.cargoName,quantity:d.quantityKg/1000,originSearch:searchAddress(d.originAddress,d.originRegion),destinationSearch:searchAddress(d.destinationAddress,d.destinationRegion),departureAt:d.departureAt,arrivalAt:d.arrivalAt,modes:d.modes.filter(m=>m.mode.code!=='4').map(m=>({1:'ROAD',2:'RAIL',3:'WATER'} as any)[m.mode.code]),allowMultimodal:d.allowMultimodal,allowTransfer:d.allowTransfer,maxTransfers:Math.min(d.maxTransfers,4),loadingType:d.loadingType,preference:d.preference,notes:d.notes};}
 private async resolvePoint(point:any){if(!point)throw new BadRequestException('请选择真实起讫点');if(point.nodeId){const node=await this.db.transportNode.findFirst({where:{id:point.nodeId,enabled:true,quality:{not:'DRAFT'}}});if(!node)throw new BadRequestException('节点不存在或未核验');return {nodeId:node.id,name:point.name,lng:node.lng,lat:node.lat,province:node.province,city:node.city,district:node.district};}return point;}
 private cost(price:any,dto:SolveDto,distance:number){if(price.unit==='PER_CONTAINER'&&(dto.loadingType!=='CONTAINER'||!dto.containerCount))throw new BadRequestException('按箱计价线路需填写箱型与箱数');const factor=price.unit==='PER_TON_KM'?dto.quantity*distance/1000:price.unit==='PER_TON'?dto.quantity:price.unit==='PER_CONTAINER'?dto.containerCount!:1;const value=Math.round(factor*price.rateMillis/10);if(!Number.isSafeInteger(value)||value>2000000000)throw new BadRequestException('测算费用超出单方案支持范围，请拆分运输批次');return value;}
 async solve(dto:SolveDto,req:any,signal?:AbortSignal){if(this.solving.has(req.user.id))throw new ConflictException('已有求解进行中，请等待完成');this.solving.add(req.user.id);try{return await this.performSolve(dto,req,signal);}finally{this.solving.delete(req.user.id);}}
 private async performSolve(dto:SolveDto,req:any,signal?:AbortSignal){
  try{budgetBounds(dto);}catch(e){throw new BadRequestException((e as Error).message);}
  checkAgentOperation(signal);dto.allowModel??=true;
  await this.grains([dto.grainId]);if(!dto.modes.length)dto.modes=['ROAD','RAIL','WATER'];if(new Date(dto.departureAt).getTime()<=Date.now())throw new BadRequestException('计划发运时间不能早于当前时间');if(dto.arrivalAt&&new Date(dto.arrivalAt)<=new Date(dto.departureAt))throw new BadRequestException('到达时间须晚于发运时间');if(!dto.allowTransfer&&dto.maxTransfers!==0||dto.allowTransfer&&dto.maxTransfers<1)throw new BadRequestException('中转条件不一致');if(dto.loadingType==='CONTAINER'&&(!dto.containerCount||!dto.containerType))throw new BadRequestException('集装箱运输须填写箱型及箱数');
  let source:any=null;if(dto.demandId){source=await this.demandInput(dto.demandId,req,false);if(source.demandVersion!==dto.demandVersion)throw new ConflictException('需求已更新，请从需求重新带入');if(source.grainId!==dto.grainId||source.quantity!==dto.quantity||source.loadingType!==dto.loadingType||new Date(source.departureAt).getTime()!==new Date(dto.departureAt).getTime()||(!source.allowMultimodal&&dto.allowMultimodal)||(!source.allowTransfer&&dto.allowTransfer)||dto.maxTransfers>source.maxTransfers||source.modes.length&&dto.modes.some(m=>!source.modes.includes(m)))throw new BadRequestException('关联需求的货物、数量、装载及发运条件不可改写，运输约束只可收窄');if(source.arrivalAt&&(!dto.arrivalAt||new Date(dto.arrivalAt)>new Date(source.arrivalAt)))throw new BadRequestException('到达时间不能放宽需求约束');}
  const previous=dto.previousRunId?await this.run(dto.previousRunId,req):null;if(previous&&previous.businessEntityId!==req.user.businessEntityId)throw new ForbiddenException('不能为其他主体创建方案版本');if(previous&&previous.demandId!==(dto.demandId||null))throw new BadRequestException('重算不能改变原方案关联需求');
  const origin=await this.resolvePoint(dto.origin),destination=await this.resolvePoint(dto.destination);if(meters(origin,destination)<100)throw new BadRequestException('起讫点距离过近，请重新选择');
  const depart=new Date(dto.departureAt),allPrices=await this.db.routePrice.findMany({where:{enabled:true,validFrom:{lte:depart},validUntil:{gt:depart},OR:[{grainId:null},{grainId:dto.grainId}],...sample()},orderBy:{validFrom:'desc'}});
  const priceFor=(lineId:string|null)=>allPrices.filter(p=>p.lineId===lineId).sort((a,b)=>Number(!!b.grainId)-Number(!!a.grainId))[0];const roadPrice=priceFor(null),warnings:string[]=[],candidates:any[]=[];
  const roadSegment=(g:any,a:any,b:any,price:any)=>({mode:'ROAD',origin:JSON.stringify(a),destination:JSON.stringify(b),geometryId:g.id,distanceMeters:g.distanceMeters,durationSeconds:g.durationSeconds+Math.floor(g.durationSeconds/(8*3600))*4*3600,waitSeconds:4*3600,costCents:this.cost(price,dto,g.distanceMeters),priceSnapshot:JSON.stringify({...this.priceView(price),containerCount:dto.containerCount}),source:g.source,routeProfile:g.routeProfile});
  if(dto.modes.includes('ROAD')&&!dto.requiredLineId&&(!dto.requiredNodeId||[origin.nodeId,destination.nodeId].includes(dto.requiredNodeId))){if(roadPrice){try{const routes=await this.amap.routes(origin,destination);for(const [i,g] of routes.entries())candidates.push({name:`公路直运 · 路径 ${i+1}`,segments:[roadSegment(g,origin,destination,roadPrice)],warnings:['公路直运用于备选比较，未验证货车限行；测算包含参考司机休息及装卸作业时间。']});}catch{warnings.push('公路直运查询失败，继续计算可用联运线路');}}else warnings.push('计划发运日缺少有效通用公路参考价，未生成公路直运候选');}
  checkAgentOperation(signal);const lines=await this.db.transportLine.findMany({where:{enabled:true,quality:{in:['VERIFIED','PUBLIC_REFERENCE']},mode:{in:dto.modes},origin:{enabled:true,quality:{not:'DRAFT'}},destination:{enabled:true,quality:{not:'DRAFT'}},...sample()},include:{origin:true,destination:true,geometry:true}});
  const conversion=(l:any)=>dto.loadingType==='BULK'&&!JSON.parse(l.loadingTypes).includes('BULK')&&JSON.parse(l.loadingTypes).includes('CONTAINER')&&dto.allowContainerization&&dto.allowMultimodal&&dto.allowTransfer;
  const eligible=lines.filter(l=>(!l.capacityKg||l.capacityKg>=Math.round(dto.quantity*1000))&&(!JSON.parse(l.grainIds).length||JSON.parse(l.grainIds).includes(dto.grainId))&&(JSON.parse(l.loadingTypes).includes(dto.loadingType)||conversion(l))&&(priceFor(l.id)||l.quality==='PUBLIC_REFERENCE')&&(!priceFor(l.id)||priceFor(l.id)!.unit!=='PER_CONTAINER'||dto.loadingType==='CONTAINER'||conversion(l)));
  const advisor=await adviseCorridors({...dto,origin,destination},eligible,signal);checkAgentOperation(signal);const network=findCorridorChains(eligible,origin,destination,dto,advisor.lineIds);const validChains=network.chains;
  const solverInfo={engine:'MULTIMODAL_GRAPH_V2',publicLineCount:eligible.length,explored:network.explored,corridorCount:network.found,accessLimitKm:network.accessLimit/1000,exitLimitKm:network.exitLimit/1000,advisor};
  
  for(const chain of validChains){checkAgentOperation(signal);const segments:any[]=[];const risk:string[]=[];let conversionCharged=false;const first=chain[0],last=chain.at(-1)!;const approach=meters(origin,first.origin)>100,exit=meters(last.destination,destination)>100;if((approach||exit)&&(!dto.modes.includes('ROAD')||!roadPrice))continue;const bridges=chain.slice(1).filter((l,i)=>meters(chain[i].destination,l.origin)>100).length;if(chain.length+Number(approach)+Number(exit)+bridges-1>dto.maxTransfers)continue;
   try{if(approach){const g=(await this.amap.routes(origin,first.origin))[0];segments.push(roadSegment(g,origin,{...first.origin,nodeId:first.origin.id},roadPrice));}
    for(const [lineIndex,l] of chain.entries()){checkAgentOperation(signal);if(lineIndex>0){const previousNode=chain[lineIndex-1].destination;if(meters(previousNode,l.origin)>100){const g=(await this.amap.routes(previousNode,l.origin))[0];segments.push({...roadSegment(g,{...previousNode,nodeId:previousNode.id},{...l.origin,nodeId:l.origin.id},roadPrice),waitSeconds:2*3600});risk.push('铁路站与港口之间按高德道路接驳，实际港内转运资格待确认');}}const p=priceFor(l.id);const service=JSON.parse(l.serviceInfo||'{}');const converted=!!conversion(l);const estimate=!p?estimateSegment(l,dto,converted,converted&&!conversionCharged):null;if(estimate&&converted)conversionCharged=true;const priced=!!p&&!(converted&&p.unit==='PER_CONTAINER')&&(p.unit!=='PER_TON_KM'||l.distanceMeters>0);let geometry=l.geometry;if(l.mode==='ROAD')geometry=(await this.amap.routes(l.origin,l.destination))[0];segments.push({mode:l.mode,origin:JSON.stringify({name:l.origin.name,lng:l.origin.lng,lat:l.origin.lat,nodeId:l.originId}),destination:JSON.stringify({name:l.destination.name,lng:l.destination.lng,lat:l.destination.lat,nodeId:l.destinationId}),lineId:l.id,lineName:l.name,geometryId:geometry?.id??null,distanceMeters:geometry?.distanceMeters??l.distanceMeters,durationSeconds:l.mode==='ROAD'?geometry!.durationSeconds:l.durationSeconds,waitSeconds:estimate?.waitSeconds??(segments.length?l.transferMinutes*60:0),costCents:estimate?estimate.fees.reduce((n:number,f:any)=>n+f.costCents,0):priced?this.cost(p,dto,geometry?.distanceMeters??l.distanceMeters):0,priceSnapshot:JSON.stringify({...((priced&&p)?this.priceView(p):{unit:'PENDING',source:'承运方报价待确认',maintainer:l.maintainer}),pending:!priced&&!estimate,conversionRequired:converted,...(estimate||{}),containerCount:dto.containerCount,service:{...service,sourceUrl:l.sourceUrl,source:l.source},distanceKnown:!!l.distanceMeters,schedulePending:l.quality==='PUBLIC_REFERENCE'}),source:l.source,routeProfile:geometry?.routeProfile??'MISSING'});if(!geometry)risk.push(estimate?`${l.name}缺少实际轨迹，地图虚线为运输走廊示意`:`${l.name}缺少已核验路径，地图仅显示节点；业务衔接见下方区段链`);if(l.quality==='PUBLIC_REFERENCE')risk.push(`${l.name}为公开班线参考；具体发车/开航日期、候班时间、当期运营及粮食承运条件待确认`);if(estimate?.durationEstimated)risk.push(`${l.name}未取得公开运输时效，按走廊节点估算，不代表已订班期`);if(converted)risk.push(`${l.name}需散粮入箱及目的站拆箱，作业能力、箱数、费用和时长待确认`);if(estimate)risk.push(`${l.name}的费用、候班、装卸及可靠性采用参考估算；地图虚线为运输走廊示意`);if(!priced&&!estimate)risk.push(`${l.name}尚无有效报价，不计作零元运输`);if(!l.capacityKg)risk.push(`${l.name}可用运力待承运方确认`);}
    if(exit){const g=(await this.amap.routes(last.destination,destination))[0];segments.push({...roadSegment(g,{...last.destination,nodeId:last.destination.id},destination,roadPrice),waitSeconds:last.transferMinutes*60});}
    if(!dto.allowMultimodal&&new Set(segments.map(s=>s.mode)).size>1)continue;candidates.push({name:chain.map(l=>l.name).join(' → '),segments,warnings:risk});
   }catch(e){checkAgentOperation(signal);if(e instanceof BadRequestException)throw e;warnings.push(`线路 ${first.name} 的接驳道路查询失败，未纳入候选`);}
  }
  if(!eligible.some(l=>l.mode!=='ROAD'))warnings.push('当前无满足粮种、装载、运力条件的铁路/水运线路；散装需求可启用“散粮入箱比选”，或补充可用班线');
  const seen=new Set<string>();let computed=candidates.filter(c=>{const key=hash(c.segments.map((s:any)=>[s.geometryId,s.lineId]));if(seen.has(key))return false;seen.add(key);return true;}).map(c=>{const distanceMeters=c.segments.reduce((n:number,s:any)=>n+s.distanceMeters,0),durationSeconds=c.segments.reduce((n:number,s:any)=>n+s.durationSeconds+s.waitSeconds,0),costCents=c.segments.reduce((n:number,s:any)=>n+s.costCents,0);if(costCents>2000000000)throw new BadRequestException('方案费用过高，请拆分批次');return {...c,reliability:Math.max(0,Math.round(c.segments.reduce((n:number,s:any)=>n+segmentMetrics(s,dto.quantity).reliability,0)/c.segments.length)-(c.segments.length-1)*2),costComplete:c.segments.every((s:any)=>{const p=JSON.parse(s.priceSnapshot);return !p.pending&&(!p.conversionRequired||p.conversionIncluded);}),distanceMeters,durationSeconds,costCents,transferCount:c.segments.length-1,arrivalAt:new Date(depart.getTime()+durationSeconds*1000),geometryComplete:c.segments.every((s:any)=>s.geometryId),modes:[...new Set(c.segments.map((s:any)=>s.mode))]};}).filter(c=>!dto.arrivalAt||c.arrivalAt<=new Date(dto.arrivalAt));
  const budget=filterByTotalBudget(computed,dto);computed=budget.candidates;
  if(budget.excluded)warnings.push('已排除'+budget.excluded+'条总费用不在预算区间内的路线');
  if(budget.unknown)warnings.push('另有'+budget.unknown+'条路线费用不完整，无法核对总预算，未纳入本次结果');
  if(budget.constrained&&!computed.length)warnings.push('没有可核对费用且满足总预算的方案，请调整预算区间或完善线路报价');
  const comparable=computed.filter(c=>c.costComplete&&!c.segments.some((s:any)=>JSON.parse(s.priceSnapshot).schedulePending));const minCost=Math.max(1,Math.min(...comparable.map(c=>c.costCents))),minTime=Math.max(1,Math.min(...comparable.map(c=>c.durationSeconds)));const score=(c:any)=>dto.preference==='COST'?c.costCents:dto.preference==='TIME'?c.durationSeconds:.5*c.costCents/minCost+.5*c.durationSeconds/minTime;computed.sort((a,b)=>Number(comparable.includes(b))-Number(comparable.includes(a))||(comparable.includes(a)?score(a)-score(b):a.durationSeconds-b.durationSeconds));
  const preferIntermodal=dto.allowMultimodal&&dto.modes.length>1;const recommendations=recommendPlans(computed,preferIntermodal);const families=[...new Set<string>(computed.map(c=>modeFamily(c.modes as string[])))].map(f=>computed.find(c=>modeFamily(c.modes as string[])===f)!);const retained=[...new Set([...recommendations.recommendations.map(r=>r.candidate),...families,...computed])].slice(0,24);if(preferIntermodal&&!computed.some(c=>c.modes.length>1))warnings.push('在允许方式、到达期限及已收录通道范围内没有可行联运路线，当前仅有单方式备选；可放宽到达时间或补充通道');
  if(computed.length<2)warnings.push('满足约束的候选不足两条，可调整方式、到达时间或完善线路价格');const groupId=previous?.groupId||randomUUID();
  checkAgentOperation(signal);const result=await this.db.$transaction(async tx=>{if(source){const current=await tx.transportDemand.findUnique({where:{id:source.demandId}});if(!current||current.version!==source.demandVersion||current.deletedAt||current.status==='CANCELLED')throw new ConflictException('求解期间需求已变化，请重新带入');}const latest=await tx.planRun.findFirst({where:{groupId},orderBy:{version:'desc'}});if(previous&&latest?.id!==previous.id)throw new ConflictException('已有更新方案版本，请打开最新版本');const run=await tx.planRun.create({data:{businessNo:number('FA'),groupId,version:(latest?.version||0)+1,businessEntityId:req.user.businessEntityId,demandId:dto.demandId||null,demandVersion:dto.demandVersion||null,input:JSON.stringify({...dto,origin,destination,sourceOrderNo:source?.orderNo,sourceDemand:source,solverInfo}),warnings:JSON.stringify([...new Set(warnings)]),status:computed.length?'READY':'NO_RESULT',createdBy:req.user.id,isTestData:!!source?.isTestData,candidates:{create:retained.map((c,index)=>({name:c.name,rank:index+1,distanceMeters:c.distanceMeters,durationSeconds:c.durationSeconds,costCents:c.costCents,transferCount:c.transferCount,arrivalAt:c.arrivalAt,geometryComplete:c.geometryComplete,modes:JSON.stringify(c.modes),warnings:JSON.stringify([...c.warnings,'费用为参考测算，最终成交价和运输排程由业务双方确认',...(c.segments.some((s:any)=>JSON.parse(s.priceSnapshot).isTestData)?['使用参考价格，实际报价待确认']:[])]),recommendation:recommendations.recommendations.find(r=>r.candidate===c)?.label||'',segments:{create:c.segments.map((s:any,i:number)=>({...s,sequence:i+1}))}}))}}});await this.audit.write(tx,req,'联运方案',run.id,'完成方案求解',undefined,{groupId,version:run.version,candidateCount:retained.length,demandId:dto.demandId||null});return run;});if(dto.allowModel){const summary=advisor.status==='SUCCEEDED'?'已识别收录的联运通道并完成连通性与约束校验':'使用本地联运网络求解；模型辅助未启用或已降级';await this.db.agentRun.create({data:{userId:req.user.id,entityId:req.user.businessEntityId,capability:'PLAN',contextType:'plan',contextId:result.id,question:'辅助识别北粮南运联运通道',status:advisor.status==='SUCCEEDED'?'SUCCEEDED':'DEGRADED',provider:advisor.provider,durationMs:advisor.durationMs||0,result:{create:{summary,structured:JSON.stringify(advisor),quality:'REFERENCE',sources:JSON.stringify([{source:'PUBLIC_CORRIDOR_CATALOG'}]),links:JSON.stringify([{label:'查看联运求解结果',url:'/plans/solve?runId='+result.id}])}}}});}return this.run(result.id,req);
 }
 async runs(q:PlanQuery,req:any){const where={...this.scope(req),...sample(),...(q.q?{businessNo:{contains:q.q}}:{}),...(q.demandId?{demandId:q.demandId}:{})};const [total,items]=await this.db.$transaction([this.db.planRun.count({where}),this.db.planRun.findMany({where,orderBy:{createdAt:'desc'},skip:(q.page-1)*q.pageSize,take:q.pageSize,include:{_count:{select:{candidates:true}}}})]);return {items:items.map(r=>({...r,input:JSON.parse(r.input),warnings:JSON.parse(r.warnings)})),total,page:q.page,pageSize:q.pageSize};}
 async run(id:string,req:any){const row=await this.db.planRun.findFirst({where:{id,...this.scope(req),...sample()},include:runInclude});if(!row)throw new NotFoundException('方案不存在或无权访问');const publications=await this.db.matchPublication.findMany({where:{planRunId:id,status:'ACTIVE'},select:{id:true,deadline:true,supplyId:true,recipients:{select:{supplyId:true}}}});const result={...row,publication:publications.find(p=>p.deadline>new Date())||null,input:JSON.parse(row.input),warnings:JSON.parse(row.warnings),candidates:row.candidates.map(c=>({...c,...this.completeness(c),reliability:Math.max(0,Math.round(c.segments.reduce((n:number,s:any)=>n+segmentMetrics(s,JSON.parse(row.input).quantity).reliability,0)/c.segments.length)-c.transferCount*2),estimated:c.segments.some(s=>{const p=JSON.parse(s.priceSnapshot);return p.estimated||p.isTestData;}),modes:JSON.parse(c.modes),family:modeFamily(JSON.parse(c.modes)),familyLabel:familyLabel(JSON.parse(c.modes)),warnings:JSON.parse(c.warnings),segments:c.segments.map(s=>({...s,...segmentMetrics(s,JSON.parse(row.input).quantity),origin:JSON.parse(s.origin),destination:JSON.parse(s.destination),priceSnapshot:JSON.parse(s.priceSnapshot),costCents:JSON.parse(s.priceSnapshot).pending?null:s.costCents,distanceMeters:JSON.parse(s.priceSnapshot).distanceKnown===false?null:s.distanceMeters,geometry:s.geometry?{...s.geometry,coordinates:JSON.parse(s.geometry.coordinates),steps:JSON.parse(s.geometry.steps)}:null}))}))};const recommended=recommendPlans(result.candidates,result.input.allowMultimodal&&result.input.modes.length>1);return {...result,recommendedPlans:recommended.recommendations.map(({candidate,...recommendation})=>({...recommendation,candidateId:candidate.id})),recommendationUnavailable:recommended.unavailable};}
 private completeness(c:any){const snapshots=c.segments.map((s:any)=>JSON.parse(s.priceSnapshot));const costComplete=snapshots.every((p:any)=>!p.pending&&(!p.conversionRequired||p.conversionIncluded)),distanceComplete=snapshots.every((p:any)=>p.distanceKnown!==false),scheduleComplete=snapshots.every((p:any)=>!p.schedulePending&&!p.conversionRequired);return {costComplete,distanceComplete,scheduleComplete,knownCostCents:c.costCents,costCents:costComplete?c.costCents:null,knownDistanceMeters:c.distanceMeters,distanceMeters:distanceComplete?c.distanceMeters:null,referenceArrivalAt:c.arrivalAt,arrivalAt:scheduleComplete?c.arrivalAt:null};}
 async select(id:string,dto:PlanSelectDto,req:any){if(await this.db.matchPublication.count({where:{planRunId:id,status:'ACTIVE',deadline:{gt:new Date()}}}))throw new ConflictException('方案已发布，请先关闭原发布再更换');if(req.user.businessEntity.type!=='TRADER')throw new ForbiddenException('仅贸易企业可以选定完整运输方案');const row=await this.run(id,req);if(new Date(row.input.departureAt).getTime()<=Date.now())throw new ConflictException('计划发运时间已过，请重算后选择');if(!row.candidates.some(c=>c.id===dto.candidateId))throw new BadRequestException('候选方案不属于本次求解');return this.db.$transaction(async tx=>{const latest=await tx.planRun.findFirst({where:{groupId:row.groupId},orderBy:{version:'desc'}});if(latest?.id!==id)throw new ConflictException('该方案已有新版本，请选择最新版本');if(row.demandId){const d=await tx.transportDemand.findUnique({where:{id:row.demandId}});if(!d||d.deletedAt||d.status==='CANCELLED'||d.version!==row.demandVersion)throw new ConflictException('关联需求已变化，请重算后选择');}const changed=await tx.planRun.updateMany({where:{id,revision:dto.revision},data:{selectedPlanId:dto.candidateId,status:'SELECTED',revision:{increment:1}}});if(!changed.count)throw new ConflictException('方案选择已更新，请刷新');await this.audit.write(tx,req,'联运方案',id,'选择完整方案',{selectedPlanId:row.selectedPlanId},{selectedPlanId:dto.candidateId});return {id,selectedPlanId:dto.candidateId,revision:dto.revision+1};});}
}
