import {Injectable,Controller,Get,Param,Query,Req,NotFoundException,BadRequestException} from '@nestjs/common';
import {Database} from './database';
import {meters} from './amap';
import {ContractsService,parse} from './contracts.service';
import {TrackingService} from './tracking.service';
import {WaybillTrackingQuery} from './tracking-workspace.dto';
import {corridorProgress} from './tracking-quantities';
import {previewTracking,previewPath,trackingNodes,completedTransport} from './tracking-preview';
import {Permit} from './security';
import {referenceRoadMovement,referenceRoadForecast} from './reference-road-motion';
const pointWhere=(test:boolean)=>test?{}:{isTestData:false};
@Injectable()
export class TrackingWorkspaceService {
 constructor(private db:Database,private contracts:ContractsService,private tracking:TrackingService){}
 test(q:WaybillTrackingQuery){return process.env.ENABLE_TEST_WORKSPACE==='true'&&process.env.NODE_ENV!=='production'&&q.includeTest==='true';}
 include(q:WaybillTrackingQuery,detail=false){return {package:true,stages:{orderBy:{sequence:'asc' as const},include:{attachments:{select:{id:true,name:true,category:true,mime:true,createdAt:true}},tasks:{include:{evidence:{select:{id:true,name:true,category:true,mime:true,createdAt:true}},issues:{where:{status:'OPEN'}},events:{orderBy:{createdAt:'asc' as const}},trackPoints:{where:pointWhere(this.test(q)),orderBy:{observedAt:'desc' as const},take:detail?6000:80},observations:{where:pointWhere(this.test(q)),orderBy:{observedAt:'desc' as const},take:detail?200:1}}}}}};}
 async rows(all:any[],q:WaybillTrackingQuery,detail=false){
  const ids=all.flatMap(b=>b.stages.flatMap((s:any)=>s.tasks.map((t:any)=>t.id))),referenceIds=all.filter(b=>parse(b.package.snapshot).sourceSystem==='BUSINESS_INITIALIZATION').flatMap(b=>b.stages.flatMap((s:any)=>s.tasks.map((t:any)=>t.id))),vehicleIds=all.flatMap(b=>b.stages.flatMap((s:any)=>s.tasks.map((t:any)=>t.vehicleId).filter(Boolean))),driverIds=all.flatMap(b=>b.stages.flatMap((s:any)=>s.tasks.map((t:any)=>t.driverId).filter(Boolean)));
  const [vehicles,drivers,vessels,nodes,rules,predicted,forecasts]=await Promise.all([this.db.fleetVehicle.findMany({where:{id:{in:vehicleIds}}}),this.db.user.findMany({where:{id:{in:driverIds}},select:{id:true,businessEntityId:true,displayName:true}}),this.db.vesselArchive.findMany({where:{carrierId:{in:all.map(b=>b.package.carrierId)}}}),this.db.transportNode.findMany({where:{enabled:true,source:{not:'DEVELOPMENT_SCENARIO'}}}),this.tracking.rules(),this.db.riskRecord.findMany({where:{taskId:{in:ids},status:{in:['NEW','ONGOING']},OR:[{lastSeenAt:{gte:new Date(Date.now()-120000)}},{taskId:{in:referenceIds}}]}}),this.db.forecast.findMany({where:{taskId:{in:ids},OR:[{predictedAt:{gte:new Date(Date.now()-120000)}},{taskId:{in:referenceIds}}]},orderBy:{predictedAt:'desc'}})]);
  const result=[];
  for(const b of all){const snap=parse(b.package.snapshot),planned=await this.tracking.planned({business:b}),progress=corridorProgress(b.stages.map((s:any)=>({...s,tasks:s.tasks.map((t:any)=>({...t,vehicleCapacityKg:vehicles.find(v=>v.id===t.vehicleId&&v.carrierId===b.package.carrierId)?.capacityKg}))})),b.package.quantityKg),assets=[];
   if(detail&&this.test(q))for(const seg of planned){for(const key of ['origin','destination'])if(!Number.isFinite(seg[key]?.lng)){const name=seg[key]?.name||'',matching=nodes.filter(n=>n.city&&name.includes(n.city.replace(/市$/,''))).sort((a,b)=>Number(b.type===(seg.mode==='WATER'?'PORT':seg.mode==='RAIL'?'RAIL':'WAREHOUSE'))-Number(a.type===(seg.mode==='WATER'?'PORT':seg.mode==='RAIL'?'RAIL':'WAREHOUSE')));if(matching.length)seg[key]={...matching[0],name,source:'SIMULATED_CITY_REFERENCE'};}if(!seg.geometry){const coordinates=previewPath(seg);if(coordinates.length>=3)seg.geometry={mode:seg.mode,source:'SIMULATED_CORRIDOR',routeProfile:'PREVIEW_ONLY',coordinates};}}
   for(const s of b.stages){const vessel=vessels.find(v=>v.carrierId===b.package.carrierId&&(s.vesselId?v.id===s.vesselId:v.name===s.vessel&&v.voyage===s.voyage)),stageView={id:s.id,sequence:s.sequence,mode:s.mode,status:s.status,origin:s.origin,destination:s.destination,quantityKg:s.quantityKg,plannedStartAt:s.plannedStartAt,plannedEndAt:s.plannedEndAt,actualEndAt:s.actualEndAt,containerized:s.containerized,vessel:s.vessel,voyage:s.voyage,mmsi:s.mmsi||vessel?.mmsi||'',billOfLading:s.billOfLading,railWaybillNo:s.railWaybillNo,boxes:parse(s.boxes),weightTicketNo:s.weightTicketNo,attachments:detail?s.attachments:undefined};
    for(const t of s.tasks){if(t.status==='CANCELLED')continue;const vehicle=vehicles.find(v=>v.id===t.vehicleId&&v.carrierId===b.package.carrierId),driver=drivers.find(v=>v.id===t.driverId&&v.businessEntityId===b.package.carrierId),points=this.tracking.positionsFor({...t,business:b,trackPoints:[...t.trackPoints].reverse()},{includeTest:q.includeTest,page:1,pageSize:20}),observations=[...t.observations].reverse().map((o:any)=>({...o,node:nodes.find(n=>n.id===o.nodeId)}));
     const movement=referenceRoadMovement({...t,business:b}),referenceForecast=movement?referenceRoadForecast({...t,business:b}):null;
     const row=this.tracking.row({...t,business:b,vehicle,trackPoints:[...t.trackPoints].reverse(),observations,planned,predictedRisks:predicted.filter(v=>v.taskId===t.id),forecast:referenceForecast||parse(forecasts.find(f=>f.taskId===t.id)?.result||'{}')},{includeTest:q.includeTest,page:1,pageSize:20},rules);
     const segment=planned.find(v=>v.mode===s.mode&&v.origin.name===s.origin&&v.destination.name===s.destination),preview=previewTracking({...t,stage:s,business:b},points,segment,observations,detail&&this.test(q)),track=preview.points;
     const currentNode=observations.at(-1),position=(preview.preview?track.at(-1):row.currentPosition)||currentNode?.node&&{longitude:currentNode.node.lng,latitude:currentNode.node.lat,observedAt:currentNode.observedAt,sourceSystem:currentNode.sourceSystem,dataQuality:currentNode.isTestData?'SIMULATED':'REPORTED'};
     if(preview.preview){row.currentPosition=position;row.alerts=row.alerts.filter(a=>!['MISSING_POSITION','STALE_POSITION','DEVIATION','STATIONARY'].includes(a.type)).concat(preview.alerts);row.eta=preview.forecast?.eta||null;row.etaQuality='SIMULATED';}
     assets.push({...row,completed:completedTransport({...t,stage:s,business:b}),movement,previewForecast:referenceForecast||preview.forecast,trajectoryPreview:preview.preview,waybillId:b.id,waybillNo:b.waybillNo||b.businessNo,shipper:snap.trader?.name||'',title:s.mode==='ROAD'?vehicle?.plate||t.resource:s.mode==='WATER'?s.vessel||t.resource:s.railWaybillNo||t.resource,driver:driver?.displayName,stage:stageView,mmsi:stageView.mmsi,voyage:s.voyage,position:position||null,currentNode:currentNode||null,plannedDepartureAt:t.plannedStartAt||s.plannedStartAt,plannedArrivalAt:t.plannedEndAt||s.plannedEndAt,trajectory:this.gaps(track,rules.staleMinutes).map((p:any)=>({id:p.id,longitude:p.longitude,latitude:p.latitude,observedAt:p.observedAt,assetId:p.assetId,sourceSystem:p.sourceSystem,sourceType:p.sourceType,dataQuality:p.dataQuality,gapBefore:p.gapBefore})),observations:detail?observations:undefined,feedback:parse(t.feedback),feedbackSubmittedAt:t.feedbackSubmittedAt,vehicleCapacityKg:vehicle?.capacityKg,evidence:detail?t.evidence:undefined,timeline:detail?[...t.events.map((e:any)=>({...e,at:e.createdAt,kind:'EXECUTION',payload:parse(e.payload)})),...observations.map((o:any)=>({...o,at:o.observedAt,kind:'OBSERVATION',type:o.eventType}))].sort((a,b)=>new Date(a.at).getTime()-new Date(b.at).getTime()):undefined});
    }
   }
   const endpoint=(v:any)=>typeof v==='string'?v:v?.address||v?.name||'';
   result.push({id:b.id,waybillNo:b.waybillNo||b.businessNo,contractNo:b.package.businessNo,shipper:snap.trader?.name||'',carrier:snap.carrier?.name||'',cargo:snap.grain||'粮食',quantityKg:b.package.quantityKg,origin:endpoint(snap.origin),destination:endpoint(snap.destination),status:b.status,loadingType:snap.loadingType,isTestData:b.package.isTestData,stageCount:b.stages.length,completedStages:b.stages.filter((s:any)=>s.status==='COMPLETED').length,assets,referenceData:snap.sourceSystem==='BUSINESS_INITIALIZATION',alerts:assets.flatMap(a=>a.alerts),progress,segments:planned,nodes:trackingNodes(progress,planned,nodes),createdAt:b.createdAt});
  }
  return result;
 }
 gaps(points:any[],minutes:number){return points.map((p,i)=>({...p,gapBefore:i>0&&(p.assetId!==points[i-1].assetId||p.sourceType!==points[i-1].sourceType||p.observedAt.getTime()-points[i-1].observedAt.getTime()>minutes*60000||meters({lng:p.longitude,lat:p.latitude},{lng:points[i-1].longitude,lat:points[i-1].latitude})/Math.max(1,(p.observedAt.getTime()-points[i-1].observedAt.getTime())/1000)>70)}));}
 matches(b:any,q:WaybillTrackingQuery){const like=(a:any,v?:string)=>!v||String(a||'').toLowerCase().includes(v.trim().toLowerCase());return like(b.waybillNo+' '+b.contractNo,q.waybill)&&like(b.shipper,q.shipper)&&like(b.cargo,q.cargo)&&like(b.origin,q.origin)&&like(b.destination,q.destination)&&(q.minKg==null||b.quantityKg>=q.minKg)&&(q.maxKg==null||b.quantityKg<=q.maxKg)&&(!q.mode&&!q.asset&&!q.mmsi||b.assets.some((a:any)=>(!q.mode||a.mode===q.mode)&&like(a.title,q.asset)&&like(a.mmsi,q.mmsi)));}
 async list(q:WaybillTrackingQuery,r:any){if(q.minKg!=null&&q.maxKg!=null&&q.minKg>q.maxKg)throw new BadRequestException('数量下限不能超过上限');const all=await this.db.logisticsBusiness.findMany({where:{package:{...this.contracts.scope(r),...(!this.test(q)?{isTestData:false}:{})},...(q.status?{status:q.status}:{})},include:this.include(q),orderBy:{createdAt:'desc'}});const rows=(await this.rows(all,q)).filter(b=>this.matches(b,q));return {items:rows.slice((q.page-1)*q.pageSize,q.page*q.pageSize),total:rows.length,asOf:new Date(),includeTest:this.test(q)};}
 async detail(id:string,q:WaybillTrackingQuery,r:any){const b=await this.db.logisticsBusiness.findFirst({where:{id,package:{...this.contracts.scope(r),...(!this.test(q)?{isTestData:false}:{})}},include:this.include(q,true)});if(!b)throw new NotFoundException('运单不存在或无权查看');return (await this.rows([b],q,true))[0];}
}
@Controller('tracking/waybills') @Permit('tracking:read')
export class TrackingWorkspaceController {
 constructor(private s:TrackingWorkspaceService){}
 @Get() list(@Query() q:WaybillTrackingQuery,@Req() r:any){return this.s.list(q,r);}
 @Get(':id') detail(@Param('id') id:string,@Query() q:WaybillTrackingQuery,@Req() r:any){return this.s.detail(id,q,r);}
}
