import {Injectable,BadRequestException,ForbiddenException,NotFoundException,ConflictException} from '@nestjs/common';
import {Database} from './database';
import {Audit} from './audit';
import {ContractsService,parse,sha} from './contracts.service';
import {AmapService,meters} from './amap';
import {TrackingQuery,PositionBatch,PositionInput,ObservationInput,EpcisInput,RuleInput} from './tracking.dto';
import {simulationPoints} from './tracking-simulation';
import {referenceRoadHistory,referenceRoadMovement,referenceRoadForecast} from './reference-road-motion';
const finished=['COMPLETED','CANCELLED'];
const canonical=(v:any):any=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
const fingerprint=(v:any)=>sha(JSON.stringify(canonical(v)));
const positionBody=(p:any)=>({sourceSystem:p.sourceSystem,sourceRecordId:p.sourceRecordId,sourceType:p.sourceType,assetId:p.assetId,observedAt:new Date(p.observedAt).toISOString(),longitude:p.originalLongitude??p.longitude,latitude:p.originalLatitude??p.latitude,coordinateSystem:p.originalCoordinateSystem??p.coordinateSystem});
const defaults={id:'default',staleMinutes:30,stationaryMinutes:120,stationaryMeters:200,deviationMeters:3000,nodeHours:24,version:1};
@Injectable()
export class TrackingService {
 constructor(private db:Database,private contracts:ContractsService,private audit:Audit,private amap:AmapService){}
 test(q:TrackingQuery){return process.env.ENABLE_TEST_WORKSPACE==='true'&&process.env.NODE_ENV!=='production'&&q.includeTest==='true';}
 scope(r:any,q:TrackingQuery){return {...this.contracts.scope(r),...(!this.test(q)?{isTestData:false}:{})};}
 async rules(){return await this.db.trackingRule.findUnique({where:{id:'default'}})||defaults;}
 async updateRules(d:RuleInput,r:any){if(r.user.businessEntity.type!=='PLATFORM')throw new ForbiddenException('仅平台可配置监测阈值');return this.db.$transaction(async tx=>{const old=await tx.trackingRule.upsert({where:{id:'default'},update:{},create:{id:'default'}});if(old.version!==d.version)throw new ConflictException('阈值已更新，请刷新');const row=await tx.trackingRule.update({where:{id:'default',version:d.version},data:{...d,version:{increment:1}}});await this.audit.write(tx,r,'全程可视化','default','修改监测阈值',old,row);return row;});}
 async task(id:string,r:any,q?:TrackingQuery){if(q)this.range(q);const where:any={...(q&&!this.test(q)?{isTestData:false}:{}),...(q?.from||q?.to?{observedAt:{...(q.from?{gte:new Date(q.from)}:{}),...(q.to?{lte:new Date(q.to)}:{})}}:{})};const t=await this.db.transportTask.findFirst({where:{id,business:{package:this.contracts.scope(r)}},include:{business:{include:{package:true}},events:{orderBy:{createdAt:'asc'}},issues:true,evidence:{select:{id:true,name:true,mime:true,createdAt:true,digest:true}},trackPoints:{where,orderBy:{observedAt:'desc'},take:2000},observations:{where,orderBy:{observedAt:'desc'},take:1000}}});if(!t)throw new NotFoundException('任务不存在或无权查看');const total=await this.db.trackPoint.count({where:{taskId:id,...where}});return {...t,trackPoints:t.trackPoints.reverse(),observations:t.observations.reverse(),trajectoryWindow:{limit:2000,total,truncated:total>2000,from:q?.from||null,to:q?.to||null}};}
 ingestOwner(t:any,r:any){if(r.user.businessEntity.type!=='CARRIER'||r.user.businessEntityId!==t.business.package.carrierId)throw new ForbiddenException('仅关联承运商可接入运输数据');}
 time(value:string){if(!/T.*(?:Z|[+-]\d{2}:\d{2})$/.test(value))throw new BadRequestException('采集时间须包含时区的 ISO 时间');const time=new Date(value);if(!Number.isFinite(time.getTime())||time.getTime()>Date.now()+300000)throw new BadRequestException('采集时间无效或晚于当前时间五分钟以上');return time;}
 async coordinates(lng:number,lat:number,system:string){if(!Number.isFinite(lng)||!Number.isFinite(lat)||lng<73||lng>136||lat<3||lat>54)throw new BadRequestException('当前仅接收中国境内有效坐标');if(system==='GCJ02')return {longitude:lng,latitude:lat};const data=await this.amap.request('/v3/assistant/coordinate/convert',{locations:`${lng},${lat}`,coordsys:'gps'});const [longitude,latitude]=String(data.locations).split(';')[0].split(',').map(Number);if(!Number.isFinite(longitude)||!Number.isFinite(latitude))throw new BadRequestException('坐标转换失败');return {longitude,latitude};}
 async positions(id:string,d:PositionBatch,r:any){const t=await this.task(id,r);this.ingestOwner(t,r);if(!['ROAD','WATER'].includes(t.mode))throw new BadRequestException('铁路任务请接入节点事件');const stage=t.stageId?await this.db.transportStage.findUnique({where:{id:t.stageId}}):null;const prepared:any[]=[];for(const p of d.points){if(['GPS','BEIDOU'].includes(p.sourceType)&&t.mode!=='ROAD'||['AIS','HISTORICAL_AIS'].includes(p.sourceType)&&t.mode!=='WATER')throw new BadRequestException('定位来源与运输方式不一致');if(p.sourceType==='SIMULATED'&&(!t.business.package.isTestData||process.env.NODE_ENV==='production'||process.env.ENABLE_TEST_WORKSPACE!=='true'))throw new BadRequestException('该定位来源未启用');if(['AIS','HISTORICAL_AIS'].includes(p.sourceType)&&t.serviceManaged){if(!stage?.mmsi)throw new BadRequestException('请先在水运阶段关联船舶 MMSI');if(p.assetId!==stage.mmsi)throw new BadRequestException('AIS 船舶标识与本航次 MMSI 不一致');}const observedAt=this.time(p.observedAt);const coordinates=await this.coordinates(p.longitude,p.latitude,p.coordinateSystem);prepared.push({taskId:id,sourceType:p.sourceType,sourceSystem:p.sourceSystem,sourceRecordId:p.sourceRecordId,assetId:p.assetId,observedAt,...coordinates,originalLongitude:p.longitude,originalLatitude:p.latitude,originalCoordinateSystem:p.coordinateSystem,isTestData:t.business.package.isTestData||p.sourceType==='SIMULATED',dataQuality:p.sourceType==='SIMULATED'?'SIMULATED':'REPORTED',fingerprint:fingerprint(positionBody(p))});}
 if(new Set(prepared.map(p=>p.sourceSystem+'|'+p.sourceRecordId)).size!==prepared.length)throw new BadRequestException('同一批次来源记录编号重复');
 return this.db.$transaction(async tx=>{let inserted=0,replayed=0;for(const p of prepared){const old=await tx.trackPoint.findUnique({where:{taskId_sourceSystem_sourceRecordId:{taskId:id,sourceSystem:p.sourceSystem,sourceRecordId:p.sourceRecordId}}});if(old){if(old.fingerprint!==p.fingerprint&&fingerprint(positionBody(old))!==p.fingerprint)throw new ConflictException('相同来源记录不能覆盖不同位置');replayed++;}else{await tx.trackPoint.create({data:p});inserted++;}}await this.audit.write(tx,r,'全程可视化',id,'接入定位批次',undefined,{inserted,replayed});return {inserted,replayed};});}
 async observation(id:string,d:ObservationInput,r:any,payload:any=d){const t=await this.task(id,r);this.ingestOwner(t,r);if(d.sourceType==='RAIL'&&t.mode!=='RAIL')throw new BadRequestException('铁路事件仅关联铁路任务');if(d.simulated&&(!t.business.package.isTestData||process.env.NODE_ENV==='production'||process.env.ENABLE_TEST_WORKSPACE!=='true'))throw new BadRequestException('该事件来源未启用');if(d.nodeId){const node=await this.db.transportNode.findFirst({where:{id:d.nodeId,enabled:true,...(d.sourceType==='RAIL'?{type:'RAIL'}:{})}});if(!node||node.name!==d.nodeName)throw new BadRequestException('节点编号、名称或类型不匹配');}const observedAt=this.time(d.observedAt);return this.db.$transaction(async tx=>{const key={taskId:id,sourceSystem:d.sourceSystem,sourceRecordId:d.sourceRecordId},digest=fingerprint(payload);const old=await tx.transportObservation.findUnique({where:{taskId_sourceSystem_sourceRecordId:key}});if(old){if(old.fingerprint!==digest&&fingerprint(parse(old.payload))!==digest)throw new ConflictException('相同来源事件不能覆盖不同内容');return {id:old.id,replayed:true};}const row=await tx.transportObservation.create({data:{...key,sourceType:d.sourceType,eventType:d.eventType,nodeId:d.nodeId,nodeName:d.nodeName,observedAt,payload:JSON.stringify(payload),isTestData:t.business.package.isTestData||d.simulated,fingerprint:digest}});await this.audit.write(tx,r,'全程可视化',id,'接入 '+d.sourceType+' 节点',undefined,{id:row.id,eventType:d.eventType});return {id:row.id,replayed:false};});}
 async epcis(id:string,d:EpcisInput,r:any){const t=await this.task(id,r);if(!d.epcList.includes(`urn:grain:task:${id}`)&&!(t.boxNo&&d.epcList.includes(`urn:grain:container:${t.boxNo}`)))throw new BadRequestException('EPC 标识须包含本任务或关联箱号');const steps:Record<string,string>={shipping:'DEPARTURE',receiving:'ARRIVAL',loading:'LOADING',unloading:'UNLOADING',transporting:'TRANSFER'};return this.observation(id,{sourceSystem:d.sourceSystem,sourceRecordId:d.eventID,sourceType:'EPCIS',eventType:steps[d.bizStep],nodeName:d.readPoint,nodeId:d.nodeId,observedAt:d.eventTime,simulated:d.simulated},r,d);}
 range(q:TrackingQuery){if(q.from&&q.to&&new Date(q.from)>new Date(q.to))throw new BadRequestException('开始时间须早于结束时间');}
 positionsFor(t:any,q:TrackingQuery){this.range(q);const points=referenceRoadHistory(t)??(this.test(q)&&!q.from&&!q.to?simulationPoints(t,t.trackPoints):t.trackPoints);return points.filter((p:any)=>(this.test(q)||!p.isTestData)&&(!q.from||p.observedAt>=new Date(q.from))&&(!q.to||p.observedAt<=new Date(q.to)));}
 current(t:any,q:TrackingQuery){return this.positionsFor(t,q).filter((p:any)=>p.sourceType!=='HISTORICAL_AIS').at(-1)||null;}
 risks(t:any,q:TrackingQuery,rules:any){const items:any[]=[],add=(type:string,level:string,message:string,at:Date|string,position:any=null)=>items.push({id:t.id+':'+type,type,level,message,at,taskId:t.id,taskNo:t.businessNo,mode:t.mode,position});if(finished.includes(t.status)||t.business.package.status==='TERMINATED')return items;const snapshot=parse(t.business.package.snapshot),current=this.current(t,q);if(t.status==='IN_TRANSIT'&&t.mode!=='RAIL'){if(!current)add('MISSING_POSITION','MEDIUM',t.mode==='WATER'?'尚无本航次 AIS 定位':'尚无车辆定位',t.createdAt);else if(Date.now()-current.observedAt.getTime()>rules.staleMinutes*60000)add('STALE_POSITION','MEDIUM',`位置超过 ${rules.staleMinutes} 分钟未更新`,current.observedAt,current);}
 if(snapshot.deal?.arrivalAt&&new Date(snapshot.deal.arrivalAt)<new Date()&&!['ARRIVED','UNLOADED','RECEIVED'].includes(t.status))add('PLAN_OVERDUE','HIGH','已超过约定到达时间，待核实实际到达',snapshot.deal.arrivalAt,current);
 for(const issue of t.issues.filter((i:any)=>i.status==='OPEN'))add('ISSUE_'+issue.id,'HIGH',issue.description,issue.createdAt,current);
 const last=t.events.at(-1);if(['AT_LOADING','ARRIVED'].includes(t.status)&&last&&Date.now()-last.createdAt.getTime()>rules.nodeHours*3600000)add('NODE_TIMEOUT','MEDIUM',`当前作业节点停留超过 ${rules.nodeHours} 小时`,last.createdAt,current);
 const ps=this.positionsFor(t,q).filter((p:any)=>current&&p.sourceType===current.sourceType&&p.assetId===current.assetId&&Date.now()-p.observedAt.getTime()<=(rules.stationaryMinutes+60)*60000);if(t.status==='IN_TRANSIT'&&ps.length>=3&&current&&Date.now()-current.observedAt.getTime()<rules.staleMinutes*60000&&current.observedAt.getTime()-ps[0].observedAt.getTime()>=rules.stationaryMinutes*60000&&ps.every((p:any)=>meters({lng:p.longitude,lat:p.latitude},{lng:current.longitude,lat:current.latitude})<=rules.stationaryMeters))add('STATIONARY','MEDIUM',`连续 ${rules.stationaryMinutes} 分钟处于 ${rules.stationaryMeters} 米范围`,current.observedAt,current);
 const latest=current;if(latest&&t.status==='IN_TRANSIT'&&Date.now()-latest.observedAt.getTime()<rules.staleMinutes*60000){const movement=referenceRoadMovement(t),geom=movement?movement.points.map((p:number[])=>p.slice(0,2)):t.planned?.[t.segment-1]?.geometry?.coordinates;if(geom?.length&&this.distanceToPath(latest,geom)>rules.deviationMeters)items.push({id:t.id+':DEVIATION',type:'DEVIATION',level:'HIGH',message:`距计划参考路径超过 ${rules.deviationMeters} 米，请核实运输位置`,at:latest.observedAt,taskId:t.id,taskNo:t.businessNo,mode:t.mode,position:latest});}
 return items;}
 row(t:any,q:TrackingQuery,rules:any){const latestNode=(t.observations||[]).filter((o:any)=>this.test(q)||!o.isTestData).at(-1)||null;const s=parse(t.business.package.snapshot),segments=parse(t.business.segments),movement=referenceRoadMovement(t),forecast=movement?referenceRoadForecast(t):t.forecast,current=this.current(t,q),alerts=this.risks(t,q,rules);return {id:t.id,businessNo:t.businessNo,businessId:t.businessId,logisticsNo:t.business.businessNo,waybillNo:t.business.waybillNo,contractId:t.business.packageId,contractNo:t.business.package.businessNo,contractStatus:t.business.package.status,demandId:s.demandId,demandNo:s.demandNo,origin:segments[t.segment-1]?.origin,destination:segments[t.segment-1]?.destination,segment:t.segment,mode:t.mode,status:t.status,quantityKg:t.quantityKg,loadedKg:t.loadedKg,unloadedKg:t.unloadedKg,resource:t.resource,asset:t.vehicle?.plate||t.resource,boxNo:t.boxNo,grain:s.grain,trader:s.trader?.name,carrier:s.carrier?.name,plannedDepartureAt:s.deal?.departureAt,plannedArrivalAt:s.deal?.arrivalAt,isTestData:t.business.package.isTestData,currentPosition:current,currentNode:latestNode,positionStatus:!current?'MISSING':current.sourceType==='SIMULATED'?'SIMULATED':Date.now()-current.observedAt.getTime()>rules.staleMinutes*60000?'STALE':'FRESH',eta:forecast?.eta||null,etaQuality:forecast?.quality||'INSUFFICIENT',alerts:alerts.concat((t.predictedRisks||[]).filter((x:any)=>!alerts.some(a=>a.type===x.type)&&(!movement||!['MISSING_POSITION','STALE_POSITION','STATIONARY','DEVIATION','ETA_DELAY'].includes(x.type))).map((x:any)=>({...x,at:x.lastSeenAt,taskId:t.id,taskNo:t.businessNo,mode:t.mode,position:current})))};}
 async all(q:TrackingQuery,r:any){this.range(q);const rows=await this.db.transportTask.findMany({where:{business:{package:this.scope(r,q)},...(q.mode?{mode:q.mode}:{}),...(q.status?{status:q.status}:{}),...(q.q?{OR:[{businessNo:{contains:q.q}},{resource:{contains:q.q}},{boxNo:{contains:q.q}},{business:{businessNo:{contains:q.q}}},{business:{waybillNo:{contains:q.q}}},{business:{package:{businessNo:{contains:q.q}}}},{business:{package:{snapshot:{contains:q.q}}}}]}:{})},include:{business:{include:{package:true}},issues:{where:{status:'OPEN'}},observations:{where:!this.test(q)?{isTestData:false}:{},orderBy:{observedAt:'desc'},take:1},events:{orderBy:{createdAt:'desc'},take:1},trackPoints:{where:{...(!this.test(q)?{isTestData:false}:{}),...(q.from||q.to?{observedAt:{...(q.from?{gte:new Date(q.from)}:{}),...(q.to?{lte:new Date(q.to)}:{})}}:{})},orderBy:{observedAt:'desc'},take:500}},orderBy:{createdAt:'desc'}});const rules=await this.rules();const nodeIds=rows.flatMap(t=>t.observations.map(o=>o.nodeId)).filter((v):v is string=>!!v);const nodes=await this.db.transportNode.findMany({where:{id:{in:nodeIds}}});const vehicles=await this.db.fleetVehicle.findMany({where:{id:{in:rows.map(t=>t.vehicleId).filter((v):v is string=>!!v)}}});const risks=await this.db.riskRecord.findMany({where:{taskId:{in:rows.map(t=>t.id)},type:{in:['PORT_CONGESTION','ENVIRONMENT','ETA_DELAY']},status:{in:['NEW','ONGOING']},lastSeenAt:{gte:new Date(Date.now()-120000)}}});const forecasts=await this.db.forecast.findMany({where:{taskId:{in:rows.map(t=>t.id)},predictedAt:{gte:new Date(Date.now()-120000)}},orderBy:{predictedAt:'desc'},take:rows.length*2});const paths=new Map<string,any[]>();for(const t of rows)if(!paths.has(t.businessId))paths.set(t.businessId,await this.planned(t));return rows.map(t=>this.row({...t,predictedRisks:risks.filter(x=>x.taskId===t.id),forecast:parse(forecasts.find(f=>f.taskId===t.id)?.result||'{}'),planned:paths.get(t.businessId),observations:t.observations.map(o=>({...o,node:nodes.find(n=>n.id===o.nodeId)})),vehicle:vehicles.find(v=>v.id===t.vehicleId),events:[...t.events].reverse(),trackPoints:[...t.trackPoints].reverse()},q,rules));}
 async list(q:TrackingQuery,r:any){let rows=await this.all(q,r);if(q.risk==='true')rows=rows.filter(t=>t.alerts.length);return {items:rows.slice((q.page-1)*q.pageSize,q.page*q.pageSize),total:rows.length,page:q.page,pageSize:q.pageSize,asOf:new Date(),includeTest:this.test(q)};}
 async overview(q:TrackingQuery,r:any){const rows=await this.all(q,r);const modes=['ROAD','RAIL','WATER'].map(mode=>{const all=rows.filter(t=>t.mode===mode);return {mode,tasks:all.length,quantityKg:all.reduce((s,t)=>s+t.quantityKg,0),active:all.filter(t=>t.status==='IN_TRANSIT').length};});return {total:rows.length,inTransit:rows.filter(t=>t.status==='IN_TRANSIT').length,completed:rows.filter(t=>t.status==='COMPLETED').length,waiting:rows.filter(t=>['DISPATCHED','ACCEPTED','AT_LOADING','LOADED'].includes(t.status)).length,arrived:rows.filter(t=>['ARRIVED','UNLOADED','RECEIVED'].includes(t.status)).length,riskTasks:rows.filter(t=>t.alerts.length).length,positioned:rows.filter(t=>t.currentPosition).length,modes,asOf:new Date(),scope:r.user.businessEntity.type==='PLATFORM'?'平台全局':'关联业务',notice:'区段任务重量可重复经过多个运输方式，不能相加为唯一货量'};}
 async alerts(q:TrackingQuery,r:any){let all=(await this.all(q,r)).flatMap(t=>t.alerts);return {items:all.slice((q.page-1)*q.pageSize,q.page*q.pageSize),total:all.length,asOf:new Date()};}
 async planned(t:any){const snapshot=parse(t.business.package.snapshot),segments=parse(t.business.segments);let planSegments:any[]=[];if(snapshot.plan?.runId){const run=await this.db.planRun.findFirst({where:{id:snapshot.plan.runId,demandId:snapshot.demandId,version:snapshot.plan.version}});if(run?.selectedPlanId)planSegments=await this.db.planSegment.findMany({where:{candidateId:run.selectedPlanId},include:{geometry:true},orderBy:{sequence:'asc'}});}const planned:any[]=[];for(const [i,segment] of segments.entries()){const sameEndpoint=(name:string,p:any)=>p&&[p.name,p.address,p.city,p.region].includes(name);const p=snapshot.plan?.segments?.find((v:any)=>v.mode===segment.mode&&sameEndpoint(segment.origin,v.origin)&&sameEndpoint(segment.destination,v.destination))||snapshot.plan?.segments?.[i];const endpoint=(name:string,point:any)=>point&&[point.name,point.address,point.city,point.region].includes(name)&&Number.isFinite(point.lng)&&Number.isFinite(point.lat)?point:null;let origin=endpoint(segment.origin,p?.origin),destination=endpoint(segment.destination,p?.destination);if(!origin)origin=await this.db.transportNode.findFirst({where:{name:segment.origin,enabled:true}});if(!destination)destination=await this.db.transportNode.findFirst({where:{name:segment.destination,enabled:true}});let geometry=null;if(p?.mode===segment.mode&&origin&&destination){const persisted=planSegments.find((v:any)=>v.sequence===(p.sequence||i+1)&&v.mode===segment.mode);const saved=p.geometryId?await this.db.routeGeometry.findUnique({where:{id:p.geometryId}}):persisted?.mode===segment.mode?persisted.geometry:null;const candidate=saved||p.geometry;if(candidate&&candidate.mode===segment.mode&&candidate.source&&candidate.coordinates){const coordinates=typeof candidate.coordinates==='string'?parse(candidate.coordinates):candidate.coordinates;if(Array.isArray(coordinates)&&coordinates.length>=3)geometry={...candidate,coordinates};}}if(!geometry&&origin?.id&&destination?.id){const line=await this.db.transportLine.findFirst({where:{originId:origin.id,destinationId:destination.id,mode:segment.mode,enabled:true,quality:'VERIFIED'},include:{geometry:true}});if(line?.geometry&&line.geometry.mode===segment.mode)geometry={...line.geometry,coordinates:parse(line.geometry.coordinates)};}planned.push({...segment,sequence:i+1,origin:origin||{name:segment.origin},destination:destination||{name:segment.destination},geometry,geometryStatus:geometry?'AVAILABLE':'NODES_ONLY',source:geometry?.source||'INTERNAL_SEGMENT',routeProfile:geometry?.routeProfile});}return planned;}
 async detail(id:string,q:TrackingQuery,r:any){const t:any=await this.task(id,r,q);if(t.business.package.isTestData&&!this.test(q))throw new NotFoundException('测试业务未包含在当前范围');const snapshot=parse(t.business.package.snapshot),segments=parse(t.business.segments),rules=await this.rules();const planned=await this.planned(t);
 const points=this.positionsFor(t,q),observations=t.observations.filter((o:any)=>(this.test(q)||!o.isTestData)&&(!q.from||o.observedAt>=new Date(q.from))&&(!q.to||o.observedAt<=new Date(q.to)));const observationNodes=await this.db.transportNode.findMany({where:{id:{in:observations.map((o:any)=>o.nodeId).filter(Boolean)}}});const vehicle=t.vehicleId?await this.db.fleetVehicle.findUnique({where:{id:t.vehicleId}}):null;const row=this.row({...t,vehicle,planned,observations:observations.map((o:any)=>({...o,node:observationNodes.find(n=>n.id===o.nodeId)}))},q,rules);const timeline=[...t.events.map((e:any)=>({...e,at:e.createdAt,kind:'EXECUTION',payload:parse(e.payload)})),...observations.map((o:any)=>({...o,at:o.observedAt,kind:'OBSERVATION',type:o.eventType,payload:parse(o.payload),node:observationNodes.find(n=>n.id===o.nodeId)}))].sort((a,b)=>new Date(a.at).getTime()-new Date(b.at).getTime());
 // Geometry is a planned reference. Sparse observations are never advertised as a real path.
 const trajectory=points.map((p:any)=>({...p,gapBefore:false}));for(let i=1;i<trajectory.length;i++){const a=trajectory[i-1],b=trajectory[i];b.gapBefore=b.sourceType!==a.sourceType||b.assetId!==a.assetId||b.observedAt.getTime()-a.observedAt.getTime()>rules.staleMinutes*60000||meters({lng:a.longitude,lat:a.latitude},{lng:b.longitude,lat:b.latitude})/Math.max(1,(b.observedAt-a.observedAt)/1000)>70;}

 return {...row,asOf:new Date(),segments:planned,trajectory,trajectoryWindow:t.trajectoryWindow,timeline,evidence:t.evidence,issues:t.issues,observations,chain:await this.db.transportTask.findMany({where:{businessId:t.businessId},select:{id:true,businessNo:true,segment:true,mode:true,status:true,quantityKg:true},orderBy:{segment:'asc'}}),sourceLinks:{demand:snapshot.demandId?`/supply-demand/demands?id=${snapshot.demandId}`:null,plan:snapshot.plan?.runId?`/plans/solve?runId=${snapshot.plan.runId}`:null,contract:`/contracts/archives?id=${t.business.packageId}`,execution:`/services?businessId=${t.businessId}`},rules,actualArrivalAt:t.events.find((e:any)=>e.type==='ARRIVE')?.createdAt||null};}
 distanceToPath(point:any,path:number[][]){let best=Infinity;const k=Math.cos(point.latitude*Math.PI/180),x=point.longitude*k,y=point.latitude;for(let i=1;i<path.length;i++){const [a,b]=[path[i-1],path[i]],ax=a[0]*k,ay=a[1],dx=b[0]*k-ax,dy=b[1]-ay,ratio=Math.max(0,Math.min(1,((x-ax)*dx+(y-ay)*dy)/(dx*dx+dy*dy||1)));best=Math.min(best,Math.hypot(x-ax-ratio*dx,y-ay-ratio*dy)*111320);}return best;}
 async trajectory(id:string,q:TrackingQuery,r:any){const d=await this.detail(id,q,r);return {taskId:id,coordinateSystem:'GCJ02',points:d.trajectory,asOf:d.asOf};}
}
