<script setup lang="ts">
import { ref,reactive,computed,watch,onMounted,onBeforeUnmount } from 'vue';
import { useRoute,useRouter,onBeforeRouteLeave,onBeforeRouteUpdate } from 'vue-router';
import { ElMessage,ElMessageBox } from 'element-plus';
import { get,api,message } from '../api';
import { useAuth } from '../stores/auth';
import Icon from '../components/Icon.vue';
const route=useRoute(),router=useRouter(),auth=useAuth();
const section=computed(()=>String(route.meta.section));
const names:Record<string,string>={users:'用户',roles:'角色',entities:'主体',dictionaries:'字典项',logs:'日志'};
const rows=ref<any[]>([]),total=ref(0),loading=ref(false),error=ref(''),saving=ref(false),formError=ref('');
const query=reactive({q:'',status:'',type:'',page:1,pageSize:10,order:'desc'});
const drawer=ref(false),detail=ref<any>(null),editingId=ref(''),resetId=ref(''),resetOpen=ref(false),newPassword=ref('');
const form=reactive<any>({}),roles=ref<any[]>([]),entities=ref<any[]>([]),permissions=ref<any[]>([]),selected=ref<any[]>([]);
const registrationOptions=ref<any[]>([]);let snapshot='';let requestVersion=0;
const canWrite=computed(()=>auth.can(`${section.value}:write`));
const availableRoles=computed(()=>roles.value.filter(r=>r.entityType===entities.value.find(e=>e.id===form.businessEntityId)?.type));
const editablePermissions=computed(()=>permissions.value.filter(p=>(form.entityType==='PLATFORM'||(!['users','roles','entities','dictionaries','logs','data','contract-template'].includes(p.code.split(':')[0])&&!['trade-orders:import','plan:maintain'].includes(p.code)))&&(!['demand:write','demand:publish','plan:select'].includes(p.code)||form.entityType==='TRADER')&&(!['supply:write','supply:publish'].includes(p.code)||form.entityType==='CARRIER')));
const date=(v:string)=>v?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'—';
const typeName=(v:string)=>({PLATFORM:'平台运营方',TRADER:'粮食贸易企业',CARRIER:'物流运营商'} as Record<string,string>)[v]||v;
async function load(){const version=++requestVersion;loading.value=true;error.value='';selected.value=[];try{const data=await get(`/${section.value}`,query);if(version!==requestVersion)return;if(section.value==='roles'){const all=data.filter((r:any)=>(!query.q||`${r.name}${r.code}`.includes(query.q))&&(!query.type||r.entityType===query.type));total.value=all.length;rows.value=all.slice((query.page-1)*query.pageSize,query.page*query.pageSize);}else{rows.value=data.items;total.value=data.total;}}catch(e){if(version===requestVersion)error.value=message(e);}finally{if(version===requestVersion)loading.value=false;}}
function search(){query.page=1;router.replace({query:Object.fromEntries(Object.entries(query).filter(([,v])=>v!==''))});load();}
function clear(){Object.assign(query,{q:'',status:'',type:section.value==='logs'?'audit':'',page:1,pageSize:10,order:'desc'});search();}
watch(section,()=>{drawer.value=false;detail.value=null;Object.assign(query,{q:String(route.query.q||''),status:String(route.query.status||''),type:String(route.query.type||(section.value==='logs'?'audit':'')),page:Math.max(1,Number(route.query.page)||1),pageSize:10,order:'desc'});load();},{immediate:true});
async function openEdit(row?:any){
  editingId.value=row?.id||'';formError.value='';
  try{
    if(section.value==='users') {const result=await get('/users/options');roles.value=result.roles;entities.value=result.entities;}
    if(section.value==='roles')permissions.value=await get('/permissions');
    if(section.value==='entities'){const data=await get('/transport-options');registrationOptions.value=data.regions.map((p:any)=>({...p,children:p.children.map(({children,...c}:any)=>({...c,label:['市辖区','县'].includes(c.label)?p.label:c.label}))}));}
  }catch(e){ElMessage.error(message(e));return;}
  Object.keys(form).forEach(k=>delete form[k]);
  if(section.value==='users')Object.assign(form,{username:row?.username||'',displayName:row?.displayName||'',businessEntityId:row?.businessEntityId||'',roleIds:row?.roles.map((r:any)=>r.id)||[],status:row?.status||'ACTIVE',phone:row?.phone||'',email:row?.email||'',department:row?.department||'',...(!row?{password:''}:{})});
  if(section.value==='entities')Object.assign(form,{name:row?.name||'',type:row?.type||'TRADER',status:row?.status||'ACTIVE',contact:row?.contact||'',phone:row?.phone||'',registeredCodes:row?.registeredCodes?.split('/').filter(Boolean)||[]});
  if(section.value==='dictionaries')Object.assign(form,{group:row?.group||'',code:row?.code||'',label:row?.label||'',sort:row?.sort||0,enabled:row?.enabled??true});
  if(section.value==='roles')Object.assign(form,{name:row.name,description:row.description,entityType:row.entityType,permissionIds:row.permissions.map((p:any)=>p.permissionId)});
  snapshot=JSON.stringify(form);drawer.value=true;
}
async function discard(){if(saving.value)return false;if(drawer.value&&snapshot!==JSON.stringify(form)){try{await ElMessageBox.confirm('尚有未保存的修改，关闭后将丢失。','放弃修改？',{confirmButtonText:'放弃修改',cancelButtonText:'继续编辑',type:'warning'});}catch{return false;}}drawer.value=false;return true;}
onBeforeRouteLeave(async()=>await discard());
onBeforeRouteUpdate(async to=>to.meta.section!==route.meta.section?await discard():true);
function warnUnload(e:BeforeUnloadEvent){if(drawer.value&&snapshot!==JSON.stringify(form)){e.preventDefault();e.returnValue='';}}
onMounted(()=>window.addEventListener('beforeunload',warnUnload));onBeforeUnmount(()=>window.removeEventListener('beforeunload',warnUnload));
async function save(){
  formError.value='';
  if(section.value==='users'&&(!form.username||!form.displayName||!form.businessEntityId||!form.roleIds.length)){formError.value='请填写账号、姓名、所属主体并选择角色';return;}
  if(section.value==='users'&&!editingId.value&&(form.password.length<12||!/[A-Za-z]/.test(form.password)||!/[0-9]/.test(form.password))){formError.value='初始密码至少12位，且包含字母和数字';return;}
  if(section.value==='entities'&&form.name.trim().length<2){formError.value='请输入至少2个字的主体名称';return;}
  if(section.value==='dictionaries'&&(!form.group||!form.code||!form.label)){formError.value='请完整填写字典分组、编码与名称';return;}
  saving.value=true;
  try{const payload={...form};delete payload.entityType;if(section.value==='entities')payload.registeredCodes=(form.registeredCodes||[]).join('/');if(editingId.value)await api.put(`/${section.value}/${editingId.value}`,payload);else await api.post(`/${section.value}`,payload);drawer.value=false;ElMessage.success('已保存');await load();if(section.value==='roles')await auth.loadMenus();}catch(e){formError.value=message(e);}finally{saving.value=false;}
}
async function remove(row:any){try{await ElMessageBox.confirm(`确认删除“${row.displayName||row.name}”？该记录将停用并保留审计记录。`,'删除确认',{type:'warning',confirmButtonText:'确认删除',cancelButtonText:'取消'});await api.delete(`/${section.value}/${row.id}`);ElMessage.success('已删除');load();}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(message(e));}}
async function resetPassword(){saving.value=true;formError.value='';try{await api.post(`/users/${resetId.value}/reset-password`,{newPassword:newPassword.value});resetOpen.value=false;ElMessage.success('密码已重置，该用户需重新登录并修改密码');load();}catch(e){formError.value=message(e);}finally{saving.value=false;}}
function rowAction(command:string,row:any){if(command==='edit')openEdit(row);else if(command==='delete')remove(row);else if(command==='reset'){resetId.value=row.id;newPassword.value='';formError.value='';resetOpen.value=true;}else detail.value=row;}
function exportSelected(){const fields=section.value==='users'?['username','displayName','status','phone','email']:section.value==='entities'?['name','type','status','contact','phone']:['group','code','label','enabled'];const safe=(v:any)=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const csv='\uFEFF'+[fields,...selected.value.map(r=>fields.map(f=>r[f]))].map(r=>r.map(safe).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const link=document.createElement('a');link.href=url;link.download=`${section.value}-selected.csv`;link.click();URL.revokeObjectURL(url);}
</script>
<template>
<div v-if="section==='logs'" class="log-tabs"><el-radio-group v-model="query.type" @change="search"><el-radio-button value="audit">操作日志</el-radio-button><el-radio-button value="login">登录日志</el-radio-button></el-radio-group></div>
<el-form class="filter-panel" inline @submit.prevent="search"><el-form-item label="关键词"><el-input v-model="query.q" :placeholder="section==='users'?'搜索账号 / 姓名':section==='logs'?'搜索操作 / 人员':'输入名称或编码'" aria-label="搜索关键词" clearable><template #prefix><Icon name="search" :size="16"/></template></el-input></el-form-item><el-form-item v-if="section!=='roles'" label="状态"><el-select v-model="query.status" placeholder="全部状态" clearable aria-label="状态筛选"><template v-if="section==='logs'"><el-option label="成功" value="SUCCESS"/><el-option label="失败" value="FAILED"/></template><template v-else><el-option label="正常 / 启用" value="ACTIVE"/><el-option label="停用" value="DISABLED"/></template></el-select></el-form-item><el-form-item v-if="['entities','roles'].includes(section)" label="主体类型"><el-select v-model="query.type" placeholder="全部类型" clearable aria-label="主体类型筛选"><el-option label="平台运营方" value="PLATFORM"/><el-option label="粮食贸易企业" value="TRADER"/><el-option label="物流运营商" value="CARRIER"/></el-select></el-form-item><el-form-item class="filter-actions"><el-button type="primary" plain native-type="submit">搜索</el-button><el-button @click="clear">重置</el-button></el-form-item></el-form>
<section class="table-panel"><div class="list-toolbar"><div><strong>{{names[section]}}列表</strong><span v-if="!error">共 <b>{{total}}</b> 条</span></div><div><el-button v-if="canWrite&&!['roles','logs'].includes(section)" type="primary" @click="openEdit()"><Icon name="plus" :size="16"/>新增{{names[section]}}</el-button></div></div>
<div v-if="selected.length" class="bulk-bar"><span>已选择 {{selected.length}} 项</span><el-button size="small" @click="exportSelected"><Icon name="download" :size="14"/>导出所选</el-button></div>
<el-alert v-if="error" :title="error" type="error" show-icon :closable="false"><el-button @click="load">重新加载</el-button></el-alert>
<el-table v-else :data="rows" v-loading="loading" row-key="id" @selection-change="selected=$event" :empty-text="query.q||query.status||query.type&&section!=='logs'?'没有符合条件的记录，请调整筛选条件':'暂无记录'">
<el-table-column v-if="!['roles','logs'].includes(section)" type="selection" width="46"/>
<template v-if="section==='users'"><el-table-column label="用户" min-width="180"><template #default="{row}"><div class="table-person"><span class="table-avatar">{{row.displayName.slice(0,1)}}</span><div><strong>{{row.displayName}}</strong><small>{{row.username}}</small></div></div></template></el-table-column><el-table-column label="所属主体" min-width="230"><template #default="{row}">{{row.businessEntity.name}}<small class="cell-note">{{typeName(row.businessEntity.type)}}</small></template></el-table-column><el-table-column label="业务角色" min-width="150"><template #default="{row}"><el-tag v-for="r in row.roles" :key="r.id" type="info" effect="plain" size="small">{{r.name}}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><span :class="row.status==='ACTIVE'?'success-text':'muted'"><span class="status-dot"></span>{{row.status==='ACTIVE'?'正常':'已停用'}}</span></template></el-table-column><el-table-column label="最近登录" min-width="170"><template #default="{row}">{{date(row.lastLoginAt)}}</template></el-table-column></template>
<template v-if="section==='entities'"><el-table-column label="主体名称" min-width="250"><template #default="{row}"><strong>{{row.name}}</strong></template></el-table-column><el-table-column label="主体类型" min-width="140"><template #default="{row}">{{typeName(row.type)}}</template></el-table-column><el-table-column prop="registeredRegion" label="企业注册地" min-width="190"/><el-table-column prop="contact" label="联系人" min-width="100"/><el-table-column prop="phone" label="联系电话" min-width="140"/><el-table-column label="用户数" width="85"><template #default="{row}">{{row._count?.users||0}}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><span :class="row.status==='ACTIVE'?'success-text':'muted'"><span class="status-dot"></span>{{row.status==='ACTIVE'?'正常':'已停用'}}</span></template></el-table-column></template>
<template v-if="section==='roles'"><el-table-column prop="name" label="角色名称" min-width="180"/><el-table-column prop="code" label="角色编码" min-width="150"/><el-table-column label="主体类型" min-width="140"><template #default="{row}">{{typeName(row.entityType)}}</template></el-table-column><el-table-column label="权限项" width="100"><template #default="{row}">{{row.permissions.length}} 项</template></el-table-column><el-table-column label="关联用户" width="110"><template #default="{row}">{{row._count.users}} 人</template></el-table-column><el-table-column prop="description" label="说明" min-width="240"/></template>
<template v-if="section==='dictionaries'"><el-table-column prop="group" label="字典分组" min-width="150"/><el-table-column prop="code" label="编码" min-width="100"/><el-table-column prop="label" label="名称" min-width="160"/><el-table-column prop="sort" label="排序值" width="100"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'" size="small">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="更新时间" min-width="180"><template #default="{row}">{{date(row.updatedAt)}}</template></el-table-column></template>
<template v-if="section==='logs'"><el-table-column label="时间" min-width="185"><template #default="{row}">{{date(row.createdAt)}}</template></el-table-column><el-table-column :prop="query.type==='login'?'username':'userName'" label="操作人员" min-width="120"/><el-table-column v-if="query.type!=='login'" prop="module" label="模块" min-width="100"/><el-table-column :prop="query.type==='login'?'reason':'action'" label="操作" min-width="150"/><el-table-column prop="ip" label="IP 地址" min-width="120"/><el-table-column label="结果" width="100"><template #default="{row}"><el-tag :type="row.success===false?'danger':'success'" size="small">{{row.success===false?'失败':'成功'}}</el-tag></template></el-table-column></template>
<el-table-column label="操作" width="100" fixed="right"><template #default="{row}"><el-dropdown trigger="click" @command="(cmd:string)=>rowAction(cmd,row)"><el-button text :aria-label="'操作 '+(row.username||row.name||row.label||row.id)"><Icon name="more"/></el-button><template #dropdown><el-dropdown-menu><el-dropdown-item command="view">查看详情</el-dropdown-item><el-dropdown-item v-if="canWrite" command="edit">{{section==='roles'?'配置权限':'编辑'}}</el-dropdown-item><el-dropdown-item v-if="canWrite&&section==='users'&&row.id!==auth.user?.id" command="reset">重置密码</el-dropdown-item><el-dropdown-item v-if="canWrite&&['users','entities'].includes(section)" command="delete" divided>删除</el-dropdown-item></el-dropdown-menu></template></el-dropdown></template></el-table-column>
</el-table><div class="pagination"><span>数据来自当前工作空间</span><el-pagination v-model:current-page="query.page" v-model:page-size="query.pageSize" :total="total" :page-sizes="[10,20,50]" layout="prev,pager,next,sizes" @change="load"/></div></section>
<el-drawer v-model="drawer" :title="(editingId?'编辑':'新增')+names[section]" size="520px" :before-close="async(done:()=>void)=>{if(await discard())done();}" :close-on-click-modal="false"><el-form label-position="top" @submit.prevent="save" :disabled="saving">
<template v-if="section==='users'"><el-form-item label="账号" required><el-input v-model="form.username" aria-label="账号" :disabled="!!editingId" placeholder="字母、数字、点、下划线"/></el-form-item><el-form-item label="姓名" required><el-input v-model="form.displayName" aria-label="姓名"/></el-form-item><el-form-item label="所属主体" required><el-select v-model="form.businessEntityId" aria-label="所属主体" filterable @change="form.roleIds=[]"><el-option v-for="e in entities" :key="e.id" :value="e.id" :label="e.name"/></el-select></el-form-item><el-form-item label="业务角色" required><el-select v-model="form.roleIds" aria-label="业务角色" multiple><el-option v-for="r in availableRoles" :key="r.id" :value="r.id" :label="r.name"/></el-select></el-form-item><div class="form-grid"><el-form-item label="手机号"><el-input v-model="form.phone" aria-label="手机号"/></el-form-item><el-form-item label="部门"><el-input v-model="form.department" aria-label="部门"/></el-form-item></div><el-form-item label="邮箱"><el-input v-model="form.email" aria-label="邮箱"/></el-form-item><el-form-item v-if="!editingId" label="初始密码" required><el-input v-model="form.password" type="password" show-password aria-label="初始密码" placeholder="至少12位，含字母和数字" autocomplete="new-password"/></el-form-item></template>
<template v-if="section==='entities'"><el-form-item label="企业注册地"><el-cascader v-model="form.registeredCodes" :options="registrationOptions" clearable filterable aria-label="企业注册地" placeholder="选择省 / 市"/></el-form-item><el-form-item label="主体名称" required><el-input v-model="form.name" aria-label="主体名称"/></el-form-item><el-form-item label="主体类型" required><el-select v-model="form.type" :disabled="!!editingId" aria-label="主体类型"><el-option v-for="t in ['TRADER','CARRIER','PLATFORM']" :key="t" :value="t" :label="typeName(t)"/></el-select></el-form-item><el-form-item label="联系人"><el-input v-model="form.contact" aria-label="联系人"/></el-form-item><el-form-item label="联系电话"><el-input v-model="form.phone" aria-label="联系电话"/></el-form-item></template>
<el-form-item v-if="['users','entities'].includes(section)" label="状态"><el-radio-group v-model="form.status"><el-radio value="ACTIVE">正常</el-radio><el-radio value="DISABLED">停用</el-radio></el-radio-group></el-form-item>
<template v-if="section==='dictionaries'"><el-form-item label="字典分组" required><el-input v-model="form.group" aria-label="字典分组" placeholder="如：粮食品种"/></el-form-item><el-form-item label="编码" required><el-input v-model="form.code" aria-label="编码"/></el-form-item><el-form-item label="名称" required><el-input v-model="form.label" aria-label="名称"/></el-form-item><el-form-item label="排序值"><el-input-number v-model="form.sort" :min="0" :max="9999" aria-label="排序值"/></el-form-item><el-form-item label="启用"><el-switch v-model="form.enabled" aria-label="启用"/></el-form-item></template>
<template v-if="section==='roles'"><el-form-item label="角色名称" required><el-input v-model="form.name" aria-label="角色名称"/></el-form-item><el-form-item label="说明"><el-input v-model="form.description" type="textarea" aria-label="说明"/></el-form-item><el-form-item label="功能权限"><el-checkbox-group v-model="form.permissionIds" class="permission-grid"><el-checkbox v-for="p in editablePermissions" :key="p.id" :value="p.id" :disabled="form.name==='司机'">{{p.name}}</el-checkbox></el-checkbox-group></el-form-item><el-alert title="主体数据隔离始终生效。权限变更将在下一次请求生效。" type="info" :closable="false"/></template>
<el-alert v-if="formError" :title="formError" type="error" :closable="false" show-icon class="form-error"/>
</el-form><template #footer><el-button :disabled="saving" @click="discard">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-drawer>
<el-drawer :model-value="!!detail" @close="detail=null" :title="names[section]+'详情'" size="540px"><template v-if="detail"><el-descriptions v-if="section==='users'" :column="1" border><el-descriptions-item label="姓名">{{detail.displayName}}</el-descriptions-item><el-descriptions-item label="账号">{{detail.username}}</el-descriptions-item><el-descriptions-item label="主体">{{detail.businessEntity.name}}</el-descriptions-item><el-descriptions-item label="角色">{{detail.roles.map((r:any)=>r.name).join('、')}}</el-descriptions-item><el-descriptions-item label="手机">{{detail.phone||'未填写'}}</el-descriptions-item><el-descriptions-item label="邮箱">{{detail.email||'未填写'}}</el-descriptions-item><el-descriptions-item label="状态">{{detail.status==='ACTIVE'?'正常':'停用'}}</el-descriptions-item></el-descriptions><template v-else-if="section==='roles'"><h3>{{detail.name}}</h3><p>{{detail.description}}</p><div class="detail-tags"><el-tag v-for="p in detail.permissions" :key="p.permissionId" type="info">{{p.permission.name}}</el-tag></div></template><el-descriptions v-else-if="section==='entities'" :column="1" border><el-descriptions-item label="名称">{{detail.name}}</el-descriptions-item><el-descriptions-item label="类型">{{typeName(detail.type)}}</el-descriptions-item><el-descriptions-item label="联系人">{{detail.contact||'未填写'}}</el-descriptions-item><el-descriptions-item label="电话">{{detail.phone||'未填写'}}</el-descriptions-item><el-descriptions-item label="状态">{{detail.status==='ACTIVE'?'正常':'停用'}}</el-descriptions-item></el-descriptions><el-descriptions v-else-if="section==='dictionaries'" :column="1" border><el-descriptions-item label="分组">{{detail.group}}</el-descriptions-item><el-descriptions-item label="编码">{{detail.code}}</el-descriptions-item><el-descriptions-item label="名称">{{detail.label}}</el-descriptions-item><el-descriptions-item label="更新时间">{{date(detail.updatedAt)}}</el-descriptions-item></el-descriptions><template v-else><el-descriptions :column="1" border><el-descriptions-item label="操作人">{{detail.userName||detail.username}}</el-descriptions-item><el-descriptions-item label="动作">{{detail.action||detail.reason}}</el-descriptions-item><el-descriptions-item label="时间">{{date(detail.createdAt)}}</el-descriptions-item><el-descriptions-item label="IP">{{detail.ip}}</el-descriptions-item><el-descriptions-item label="请求编号">{{detail.requestId}}</el-descriptions-item><el-descriptions-item label="终端">{{detail.userAgent}}</el-descriptions-item></el-descriptions><details v-if="detail.before||detail.after" class="audit-details"><summary>查看变更详情</summary><h4>修改前</h4><pre>{{detail.before?JSON.stringify(JSON.parse(detail.before),null,2):'无'}}</pre><h4>修改后</h4><pre>{{detail.after?JSON.stringify(JSON.parse(detail.after),null,2):'无'}}</pre></details></template></template></el-drawer>
<el-dialog v-model="resetOpen" title="重置密码" width="440px" :close-on-click-modal="false"><p>该用户的现有会话将立即失效，下次登录需修改密码。</p><el-form label-position="top" @submit.prevent="resetPassword"><el-form-item label="新临时密码"><el-input v-model="newPassword" type="password" show-password aria-label="新临时密码" placeholder="至少12位，含字母和数字"/></el-form-item></el-form><el-alert v-if="formError" type="error" :title="formError" :closable="false"/><template #footer><el-button @click="resetOpen=false" :disabled="saving">取消</el-button><el-button type="primary" @click="resetPassword" :loading="saving">确认重置</el-button></template></el-dialog>
</template>
