<script setup lang="ts">
import {requestKey} from '../request-key';
import {ref,computed,onMounted,onBeforeUnmount} from 'vue';
import {Bell,ClipboardList,ClipboardCheck,FileText,UserRound,ArrowLeft,ArrowRight,Package,RefreshCw,LogOut,Phone,Truck,ChevronRight,Wifi,BatteryFull,Signal,Search} from 'lucide-vue-next';
import axios from 'axios';
import {ElMessage} from 'element-plus';
import {message} from '../api';
import {label,ton,date,download} from '../fulfillment';
import TaskExecution from '../components/TaskExecution.vue';
import DriverServiceFeedback from '../components/DriverServiceFeedback.vue';
const client=axios.create({baseURL:'/api',withCredentials:true,timeout:15000});let token='',refreshing:Promise<any>|null=null;
client.interceptors.request.use(c=>{if(token)c.headers.Authorization=`Bearer ${token}`;return c;});
client.interceptors.response.use(r=>r,async e=>{if(e.response?.status===401&&!e.config._retry&&!['/driver/login','/driver/refresh'].includes(e.config.url)){e.config._retry=true;try{await refresh();return client(e.config);}catch{user.value=null;token='';}}throw e;});
async function refresh(){if(!refreshing)refreshing=client.post('/driver/refresh').then(r=>{token=r.data.data.accessToken;user.value=r.data.data.user;}).finally(()=>refreshing=null);return refreshing;}
const user=ref<any>(),username=ref(''),password=ref(''),error=ref(''),busy=ref(false),loading=ref(true),tasks=ref<any[]>([]),selected=ref(''),section=ref('tasks'),taskTab=ref('pending'),search=ref(''),newPassword=ref(''),time=ref('');
let tabPicked=false,timer:ReturnType<typeof setInterval>;
const current=computed(()=>tasks.value.find(t=>t.id===selected.value));
const groups=computed(()=>({pending:tasks.value.filter(t=>t.status==='DISPATCHED'),active:tasks.value.filter(t=>!['DISPATCHED','COMPLETED','CANCELLED','RETURNED'].includes(t.status)),completed:tasks.value.filter(t=>t.status==='COMPLETED'),history:tasks.value.filter(t=>['RETURNED','CANCELLED'].includes(t.status))}));
const filtered=computed(()=>((groups.value as any)[taskTab.value]||[]).filter((t:any)=>`${t.businessNo}${t.segment.origin}${t.segment.destination}${t.cargo}`.includes(search.value)));
const documents=computed(()=>tasks.value.flatMap(t=>t.evidence.map((f:any)=>({...f,task:t}))));
const notices=computed(()=>tasks.value.flatMap(t=>[...(t.status==='DISPATCHED'?[{id:t.id,title:'您有一项新运输任务',description:`${t.segment.origin} → ${t.segment.destination}`,task:t}]:[]),...t.issues.map((i:any)=>({id:i.id,title:i.status==='OPEN'?'异常已上报，等待调度处理':'运输异常已处理',description:i.resolution||i.description,task:t}))]));
const title=computed(()=>current.value?'任务详情':section.value==='documents'?'运输单据':section.value==='mine'?'我的':section.value==='messages'?'消息':'任务');
function pickTab(tab:string){taskTab.value=tab;tabPicked=true;}
function navigate(next:string){selected.value='';section.value=next;error.value='';}
function inspect(t:any){selected.value=t.id;section.value='tasks';}
function schedule(s:string){return s?new Date(s).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).replaceAll('/','-'):'暂未约定';}
async function load(){loading.value=true;try{tasks.value=(await client.get('/driver/tasks')).data.data;error.value='';if(!tabPicked)taskTab.value=groups.value.pending.length?'pending':groups.value.active.length?'active':'completed';}catch(e){error.value=message(e);}finally{loading.value=false;}}
async function login(){busy.value=true;error.value='';try{const r=await client.post('/driver/login',{username:username.value,password:password.value});token=r.data.data.accessToken;user.value=r.data.data.user;if(!user.value.mustChangePassword){password.value='';await load();}}catch(e){error.value=message(e);}finally{busy.value=false;}}
async function logout(){busy.value=true;try{await client.post('/driver/logout');token='';user.value=null;tasks.value=[];selected.value='';section.value='tasks';tabPicked=false;}catch(e){error.value=message(e);}finally{busy.value=false;}}
async function changePassword(){busy.value=true;try{await client.post('/driver/password',{currentPassword:password.value,newPassword:newPassword.value});token='';user.value=null;tasks.value=[];password.value='';newPassword.value='';error.value='密码已更新，请使用新密码登录';}catch(e){error.value=message(e);}finally{busy.value=false;}}
async function accept(t:any){busy.value=true;error.value='';try{await client.post(`/driver/tasks/${t.id}/events`,{type:'ACCEPT',requestKey:requestKey()});await load();pickTab('active');inspect(t);ElMessage.success('已接收任务，请前往装货点');}catch(e){error.value=message(e);}finally{busy.value=false;}}
async function downloadFile(f:any){try{const r=await client.get(`/driver/evidence/${f.id}`,{responseType:'blob'});download(r.data,f.name,f.mime);}catch(e){error.value=message(e);}}
const focus=()=>{if(user.value&&!user.value.mustChangePassword&&!busy.value)load();};const tick=()=>time.value=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Shanghai'});
onMounted(async()=>{document.title='司机服务 · 辽粮';document.body.classList.add('driver-app');tick();timer=setInterval(tick,30000);try{await refresh();if(!user.value.mustChangePassword)await load();}catch{}finally{loading.value=false;}window.addEventListener('focus',focus);});
onBeforeUnmount(()=>{clearInterval(timer);document.body.classList.remove('driver-app');window.removeEventListener('focus',focus);});
</script>
<template>
<div class="driver-shell"><main class="mini-app" aria-label="司机小程序"><div class="status-bar" aria-hidden="true"><b>{{time}}</b><span><Signal :size="14"/><Wifi :size="14"/><BatteryFull :size="20"/></span></div>
<header class="mini-header"><button v-if="current||section==='messages'" class="icon-button back-button" aria-label="返回任务列表" @click="navigate('tasks')"><ArrowLeft :size="22"/></button><h1>{{user?title:'司机登录'}}</h1><button v-if="user&&!user.mustChangePassword" class="icon-button message-button" aria-label="消息" @click="navigate('messages')"><Bell :size="22"/><i v-if="notices.length" class="notification-dot"/></button></header>
<div v-if="user&&!user.mustChangePassword&&section==='tasks'&&!current" class="task-tabs" role="tablist" aria-label="任务状态"><button v-for="t in [{key:'pending',name:'待接收'},{key:'active',name:'执行中'},{key:'completed',name:'已完成'}]" :key="t.key" role="tab" :aria-selected="taskTab===t.key" :class="{active:taskTab===t.key}" @click="pickTab(t.key)">{{t.name}}<span v-if="t.key!=='completed'"> ({{(groups as any)[t.key].length}})</span></button></div>
<div class="mini-body" :class="{'login-body':!user,'detail-body':!!current}"><el-alert v-if="error" :title="error" type="error" :closable="false" show-icon class="driver-error"/>
<div v-if="loading&&!user" class="loading-state"><RefreshCw :size="24" class="spinning"/><p>正在载入司机工作台</p></div>
<div v-else-if="!user" class="driver-login"><div class="login-symbol"><Truck :size="38"/></div><h2>北粮南运</h2><p>登录司机账号，开始今天的运输任务</p><el-form label-position="top" @submit.prevent="login"><el-form-item label="司机账号"><el-input v-model="username" autocomplete="username" placeholder="请输入司机账号"/></el-form-item><el-form-item label="登录密码"><el-input v-model="password" type="password" show-password autocomplete="current-password" placeholder="请输入密码"/></el-form-item><el-button native-type="submit" type="primary" :loading="busy" class="login-submit">登录司机端</el-button></el-form><small>账号由所属物流企业分配</small></div>
<div v-else-if="user.mustChangePassword" class="driver-login"><h2>设置新密码</h2><el-form label-position="top"><el-form-item label="当前密码"><el-input v-model="password" type="password"/></el-form-item><el-form-item label="新密码"><el-input v-model="newPassword" type="password" show-password/></el-form-item><el-button type="primary" :loading="busy" @click="changePassword">修改密码并重新登录</el-button></el-form></div>
<template v-else-if="current"><div class="detail-schedule"><span>计划发车 <b>{{schedule(current.plannedDepartureAt)}}</b></span><span>预计结束 <b>{{schedule(current.requiredArrivalAt)}}</b></span></div><DriverServiceFeedback v-if="current.stageId" :key="current.id" :task="current" :client="client" @changed="load"/><TaskExecution v-else :key="current.id" :task="current" driver :client="client" @changed="load"/></template>
<template v-else-if="section==='tasks'"><div class="mini-toolbar"><label class="mini-search"><Search :size="15"/><input v-model="search" placeholder="搜索任务或地点" aria-label="搜索任务"/></label><button class="icon-button" aria-label="刷新任务" :disabled="loading" @click="load"><RefreshCw :size="17" :class="{spinning:loading}"/></button></div><div v-if="loading&&!tasks.length" class="loading-state"><RefreshCw :size="24" class="spinning"/><p>正在获取运输任务</p></div><template v-else>
<article v-for="(t,i) in filtered" :key="t.id" class="mini-task-card"><div class="task-card-top"><span class="cargo-icon" :class="{orange:i%2}"><Package :size="21"/></span><div class="task-ident"><p>{{t.businessNo}}</p><h2>{{t.segment.origin}} <ArrowRight :size="16"/> {{t.segment.destination}}</h2></div><span class="task-status" :class="{done:t.status==='COMPLETED'}">{{t.status==='DISPATCHED'?'新任务':label(t.status)}}</span></div><div class="cargo-line"><ClipboardList :size="15"/><b>粮食（{{t.cargo}}）</b><span>{{t.stageId?(t.feedbackSubmittedAt||t.unloadedKg>0?ton(t.unloadedKg||t.feedback?.quantityKg||0):'待过磅'):ton(t.quantityKg)}}</span></div><dl class="schedule-lines"><dt>计划发车</dt><dd>{{schedule(t.plannedDepartureAt)}}</dd><dt>要求到达</dt><dd>{{schedule(t.requiredArrivalAt)}}</dd></dl><button class="task-primary" :disabled="busy" @click="t.status==='DISPATCHED'?accept(t):inspect(t)">{{t.status==='DISPATCHED'?'接收任务':t.status==='COMPLETED'?'查看回单与记录':'继续执行'}}</button></article>
<div v-if="!filtered.length&&!error" class="mini-empty"><ClipboardCheck :size="40"/><h2>{{search?'未找到相关任务':taskTab==='pending'?'暂无待接收任务':taskTab==='active'?'暂无执行中的任务':taskTab==='history'?'暂无退回或取消的任务':'暂无已完成任务'}}</h2><p>{{search?'试试其他任务编号或地点':'调度下发的任务将在这里显示'}}</p><button @click="search?search='':load()">{{search?'清除搜索':'刷新任务'}}</button></div></template></template>
<template v-else-if="section==='documents'"><div class="section-note">装货凭证与签收回单 <b>{{documents.length}} 份</b></div><button v-for="f in documents" :key="f.id" class="document-card" @click="downloadFile(f)"><FileText :size="23"/><div><strong>{{f.name}}</strong><small>{{f.task.businessNo}} · {{date(f.createdAt)}}</small></div><ChevronRight :size="17"/></button><div v-if="!documents.length" class="mini-empty"><FileText :size="40"/><h2>暂无运输单据</h2><p>在任务中上传装货凭证和签收回单后<br/>可在此查看与下载</p><button @click="navigate('tasks')">前往任务</button></div></template>
<template v-else-if="section==='messages'"><div class="section-note">任务与异常处理动态</div><button v-for="n in notices" :key="n.id" class="notice-card" @click="inspect(n.task)"><Bell :size="19"/><div><strong>{{n.title}}</strong><p>{{n.description}}</p><small>{{n.task.businessNo}}</small></div><ChevronRight :size="16"/></button><div v-if="!notices.length" class="mini-empty"><Bell :size="40"/><h2>暂无消息</h2><p>新任务与异常处理结果将在这里显示</p></div></template>
<template v-else-if="section==='mine'"><div class="profile-card"><div class="profile-avatar"><UserRound :size="31"/></div><h2>{{user.displayName}}</h2><p>{{user.businessEntity.name}}</p><small>司机账号 · {{user.username}}</small></div><div class="profile-stats"><div><b>{{groups.active.length}}</b><span>执行中</span></div><div><b>{{groups.completed.length}}</b><span>已完成</span></div><div><b>{{documents.length}}</b><span>单据</span></div></div><div class="profile-options"><div><Phone :size="18"/><span>联系电话</span><strong>{{user.phone||'暂未登记'}}</strong></div><button @click="navigate('tasks');pickTab('history')"><ClipboardList :size="18"/><span>退回与取消记录</span><ChevronRight :size="17"/></button><button @click="navigate('documents')"><FileText :size="18"/><span>我的运输单据</span><ChevronRight :size="17"/></button><button :disabled="busy" @click="logout"><LogOut :size="18"/><span>退出登录</span><ChevronRight :size="17"/></button></div><p class="driver-service-note">辽粮 · 司机服务</p></template>
</div><nav v-if="user&&!user.mustChangePassword" class="bottom-nav" aria-label="司机功能"><button :class="{active:section==='tasks'||section==='messages'}" @click="navigate('tasks')"><ClipboardCheck :size="23"/><span>任务</span></button><button :class="{active:section==='documents'}" @click="navigate('documents')"><FileText :size="23"/><span>单据</span></button><button :class="{active:section==='mine'}" @click="navigate('mine')"><UserRound :size="23"/><span>我的</span></button></nav><div v-else class="login-footer">辽粮 · 司机服务</div></main></div>
</template>
<style>
body.driver-app{--el-color-primary:#087bff;--el-color-primary-light-3:#52a4ff;--el-color-primary-light-5:#86bfff;--el-color-primary-light-7:#b6d8ff;--el-color-primary-light-9:#edf6ff;--el-color-primary-dark-2:#0064db;--el-font-family:"PingFang SC","Microsoft YaHei",system-ui,sans-serif;--el-text-color-primary:#18274c;--el-border-radius-base:7px;background:#eaf4ff}
body.driver-app .el-dialog{width:min(376px,calc(100vw - 28px))!important;max-height:80dvh;overflow:auto;margin:10dvh auto 0!important;border-radius:14px}
body.driver-app .el-message{max-width:min(370px,calc(100vw - 24px));white-space:normal}
body.driver-app .execution-head{align-items:flex-start}body.driver-app .execution-head h3{overflow-wrap:anywhere;min-width:0}body.driver-app .execution-head .el-tag{flex-shrink:0}body.driver-app .execution .evidence-list .el-button{overflow-wrap:anywhere}
</style>
<style scoped>
.driver-shell{min-height:100dvh;background:radial-gradient(ellipse at 50% 0%,#f7fbff 0%,#eaf4ff 70%);display:flex;justify-content:center;align-items:center;padding:20px;color:#18274c;font-family:var(--el-font-family)}
.mini-app{width:390px;height:min(850px,calc(100dvh - 40px));min-height:560px;display:flex;flex-direction:column;background:#f5faff;border-radius:20px;overflow:hidden;border:1px solid #dcecfb;box-shadow:0 16px 60px #377ec416}
.status-bar{flex-shrink:0;display:flex;align-items:center;justify-content:space-between;height:30px;padding:0 22px;background:#f8fbff;font-size:11px}.status-bar span{display:flex;align-items:center;gap:5px}.status-bar b{font-weight:600}
.mini-header{position:relative;flex-shrink:0;height:49px;display:flex;align-items:center;justify-content:center;background:#f8fbff}.mini-header h1{font-size:18px;font-weight:650;line-height:1.5;margin:0}.icon-button{display:grid;place-items:center;padding:7px;color:#1e3964;border:0;background:none;cursor:pointer}.icon-button:disabled{opacity:.55;cursor:wait}.back-button{position:absolute;left:10px}.message-button{position:absolute;right:12px}.notification-dot{position:absolute;width:7px;height:7px;border-radius:50%;background:#ff4d4f;right:8px;top:5px;border:1px solid white}
.task-tabs{display:flex;flex-shrink:0;height:43px;background:#f8fbff;border-bottom:1px solid #e1eaf4;padding:0 10px}.task-tabs button{position:relative;flex:1;background:none;border:0;color:#8296b2;font-size:14px;font-weight:550}.task-tabs button.active{color:#087bff}.task-tabs button.active:after{content:"";position:absolute;left:24px;right:24px;bottom:0;height:3px;background:#087bff;border-radius:3px 3px 0 0}
.mini-body{flex:1;min-height:0;overflow-y:auto;overscroll-behavior:contain;scrollbar-width:thin;padding:10px 12px 16px}.mini-toolbar{display:flex;align-items:center;gap:7px;margin:0 0 10px}.mini-search{height:31px;flex:1;display:flex;align-items:center;gap:7px;padding:0 10px;background:#eaf3fd;border-radius:7px;color:#8296b2}.mini-search input{width:100%;min-width:0;border:0;background:none;outline:none;color:#1f3558;font-size:12px}.mini-search input::placeholder{color:#92a6bf}
.mini-task-card{background:white;border:1px solid #dcefff;border-radius:12px;padding:13px;margin-bottom:12px;box-shadow:0 2px 9px #2992ff04}.task-card-top{display:flex;align-items:flex-start;gap:9px;position:relative}.cargo-icon{height:35px;width:35px;flex-shrink:0;border-radius:9px;background:#e8f6ff;color:#0499fa;display:grid;place-items:center}.cargo-icon.orange{background:#fff3e6;color:#ff8a26}.task-ident{flex:1;min-width:0}.task-ident>p{font-size:11px;color:#47658f;margin:0 54px 8px 0;overflow-wrap:anywhere;line-height:1.5}.task-ident h2{display:flex;gap:7px;align-items:center;flex-wrap:wrap;font-size:15px;font-weight:650;line-height:1.5;margin:0}.task-ident h2 svg{flex-shrink:0}.task-status{position:absolute;right:0;top:0;background:#e5f3ff;color:#0883ff;border:1px solid #c3e2ff;border-radius:4px;font-size:10px;padding:1px 5px;white-space:nowrap;line-height:1.6}.task-status.done{color:#22856c;background:#edfaf5;border-color:#cfede2}.cargo-line{display:flex;align-items:center;gap:7px;color:#657fa3;font-size:13px;margin:12px 0 10px 44px}.cargo-line b{font-weight:550;color:#466187}.cargo-line span{margin-left:6px}.schedule-lines{display:grid;grid-template-columns:1fr 1.3fr;row-gap:8px;font-size:12px;margin:0 0 13px}.schedule-lines dt{color:#92a7bf}.schedule-lines dd{color:#274876;font-weight:550;margin:0;font-variant-numeric:tabular-nums}.task-primary{width:100%;height:38px;border:0;border-radius:6px;background:linear-gradient(100deg,#0095ff,#006aff);color:white;font-size:14px;font-weight:550;cursor:pointer}.task-primary:disabled{opacity:.6;cursor:wait}
.bottom-nav{flex-shrink:0;display:flex;height:66px;padding:6px 10px 8px;background:#fff;border-top:1px solid #e5eef7;z-index:2}.bottom-nav button{flex:1;display:flex;flex-direction:column;justify-content:center;align-items:center;gap:5px;border:0;background:none;color:#8395b6;font-size:12px}.bottom-nav button.active{color:#087bff;font-weight:600}.bottom-nav button.active svg{fill:#e3f1ff}.login-footer{flex-shrink:0;padding:18px;text-align:center;font-size:10px;color:#9aafc6}
.driver-login{padding:45px 16px 20px;text-align:center}.login-symbol{width:76px;height:76px;margin:0 auto 22px;display:grid;place-items:center;background:#e6f3ff;border-radius:22px;color:#087bff}.driver-login h2{font-size:25px;line-height:1.5;margin:0 0 12px}.driver-login>p{font-size:12px;color:#8499b3;line-height:1.8;margin:0 0 35px}.driver-login .el-form{text-align:left}.driver-login .el-input{--el-input-height:43px}.driver-login .el-button{width:100%;height:42px;margin-top:14px}.driver-login>small{display:block;color:#a0b0c3;font-size:11px;margin-top:24px}
.driver-error{margin-bottom:12px}.mini-empty,.loading-state{text-align:center;padding:70px 10px;color:#9cb6d2}.mini-empty>svg{color:#9cc9f4;margin-bottom:15px}.mini-empty h2{font-size:15px;color:#496b94;font-weight:550;margin:0 0 10px}.mini-empty p,.loading-state p{font-size:12px;line-height:1.9;margin:0}.mini-empty button{margin-top:18px;border:0;border-radius:6px;padding:8px 18px;background:#e5f2ff;color:#087bff;font-size:12px}.spinning{animation:spin 1.2s linear infinite}.loading-state svg{margin-bottom:12px}@keyframes spin{to{transform:rotate(360deg)}}
.detail-body{padding:16px}.detail-schedule{padding:13px;background:#eaf4ff;border-radius:8px;display:grid;gap:8px;font-size:11px;color:#849bb8;margin-bottom:20px}.detail-schedule b{float:right;color:#34567f;font-weight:550}.detail-body :deep(.execution p){overflow-wrap:anywhere}.detail-body :deep(.execution-head h3){font-size:14px}.detail-body :deep(.execution-actions){gap:6px}.detail-body :deep(.execution-actions .el-button){padding:8px 11px}.section-note{font-size:12px;color:#829ab7;margin:8px 4px 17px}.section-note b{float:right;font-weight:500}.document-card,.notice-card{display:flex;width:100%;gap:12px;align-items:center;border:1px solid #e2edfa;background:white;border-radius:10px;padding:16px 12px;margin-bottom:12px;color:#6586ae;text-align:left}.document-card>svg,.notice-card>svg{flex-shrink:0;color:#1688ff}.document-card>div,.notice-card>div{flex:1;min-width:0}.document-card strong,.notice-card strong{display:block;overflow-wrap:anywhere;font-size:13px;font-weight:550;color:#345578;line-height:1.8}.document-card small,.notice-card small{display:block;font-size:10px;color:#99abc0;margin-top:7px;overflow-wrap:anywhere}.notice-card p{font-size:12px;line-height:1.8;color:#6f8aaa;margin:7px 0 0}
.profile-card{text-align:center;padding:24px 10px 20px;background:white;border:1px solid #e2edfa;border-radius:12px}.profile-avatar{margin:0 auto 13px;width:62px;height:62px;border-radius:50%;display:grid;place-items:center;background:#e9f4ff;color:#248dff}.profile-card h2{font-size:19px;margin:0 0 10px}.profile-card p{font-size:12px;color:#6c88a9;line-height:1.8;margin:0 0 10px}.profile-card small{font-size:11px;color:#a0b2c8}.profile-stats{display:flex;justify-content:space-around;padding:24px 0;margin-bottom:12px}.profile-stats>div{display:flex;flex-direction:column;gap:7px;text-align:center}.profile-stats b{font-size:23px;color:#345d90}.profile-stats span{font-size:12px;color:#93a8c2}.profile-options{background:white;border:1px solid #e2edfa;border-radius:10px;overflow:hidden}.profile-options>button,.profile-options>div{display:flex;align-items:center;gap:11px;width:100%;padding:18px 14px;color:#647e9f;background:none;border:0;text-align:left;font-size:13px}.profile-options>button:not(:last-child),.profile-options>div{border-bottom:1px solid #eef4fa}.profile-options span{flex:1;color:#365879}.profile-options strong{font-size:12px;font-weight:500}.driver-service-note{font-size:11px;color:#a0b4cb;text-align:center;margin-top:24px}
button:focus-visible,a:focus-visible,input:focus-visible{outline:2px solid #087bff;outline-offset:3px}
@media(max-width:480px){.driver-shell{padding:0;align-items:stretch}.mini-app{width:100%;height:100dvh;min-height:0;border:0;border-radius:0;box-shadow:none}.bottom-nav{height:calc(66px + env(safe-area-inset-bottom));padding-bottom:calc(8px + env(safe-area-inset-bottom))}.status-bar{padding-top:env(safe-area-inset-top);height:calc(30px + env(safe-area-inset-top))}}
@media(prefers-reduced-motion:reduce){.spinning{animation:none}}
</style>
