<script setup lang="ts">
import Icon from '../components/Icon.vue';
import BusinessArt from '../components/BusinessArt.vue';
import PlatformShowcase from '../components/PlatformShowcase.vue';
const values=[{title:'方案更快',lead:'把复杂路线，变成清晰选择',description:'围绕货物与运输条件，比较公铁、公水、铁水和公铁水方案，减少反复沟通。',art:'plan'},{title:'资源更广',lead:'让合适的运力，更容易找到',description:'连接粮食企业与物流资源，按线路和运输能力寻找承运伙伴。',art:'matching'},{title:'执行更顺',lead:'一次委托，多程有序衔接',description:'从合同到运单，串联车辆、铁路和船舶，让节点协作有据可依。',art:'demand'},{title:'过程更透明',lead:'货物走到哪里，心里有数',description:'汇集运输位置、业务回传和节点进度，及时关注异常与到达变化。',art:'tracking'}] as const;
const steps=[{title:'运输需求',icon:'file',description:'说明货物、地点与时间'},{title:'方案规划',icon:'route',description:'比较路线、费用与时效'},{title:'运力匹配',icon:'handshake',description:'寻找伙伴，协同报价'},{title:'运输执行',icon:'truck',description:'一个运单，衔接多程'},{title:'全程跟踪',icon:'map',description:'掌握节点、位置与风险'}];
const capabilities=[{title:'智能方案求解',icon:'route',description:'从起运地到目的地，组合适合的联运通道。'},{title:'供需协同',icon:'handshake',description:'需求与运力相互匹配，让合作更高效。'},{title:'运输执行',icon:'truck',description:'统一运单，协同公路、铁路与水运阶段。'},{title:'运行监测',icon:'map',description:'汇集运输轨迹和回传信息，掌握业务进度。'},{title:'风险预警',icon:'shield',description:'关注延误与节点异常，辅助运输决策。'},{title:'数据服务',icon:'database',description:'经授权使用业务数据，支持分析与运营。'}];
const aiServices=[{title:'智能问踪',icon:'map',description:'一句话了解运输进度'},{title:'ETA 预测',icon:'clock',description:'关注预计到达与延误'},{title:'港口拥堵',icon:'anchor',description:'了解港口作业影响'},{title:'风险研判',icon:'shield',description:'梳理风险与应对建议'},{title:'单据识别',icon:'scan',description:'提取单据，辅助复核'},{title:'智能报告',icon:'chart',description:'整理业务，形成摘要'}];
const partners=[{name:'粮食贸易企业',icon:'grain'},{name:'物流运营企业',icon:'truck'},{name:'公路承运商',icon:'route'},{name:'铁路运营单位',icon:'train'},{name:'港口企业',icon:'anchor'},{name:'船公司',icon:'ship'}];
function scrollTo(id:string){document.getElementById(id)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
</script>
<template>
<div class="portal-page">
 <a class="skip-link" href="#portal-main">跳到主要内容</a>
 <header class="portal-header"><a href="#" class="portal-brand" aria-label="辽粮智运首页"><img src="/assets/liaoliang-logo.png" alt="辽粮" width="45" height="48"/><span><strong>辽粮智运</strong><small>智能多式联运平台</small></span></a><nav aria-label="首页导航"><a href="#value">客户价值</a><a href="#workflow">业务流程</a><a href="#capabilities">核心能力</a><a href="#ai-service">AI 服务</a><a href="#product">产品展示</a></nav><router-link class="portal-header-action" to="/workbench">进入平台<Icon name="arrow" :size="16"/></router-link></header>
 <main id="portal-main">
  <section class="portal-hero"><img class="hero-image" src="/assets/portal/intermodal-port.webp" alt="粮食港口、公路货运、铁路与船舶衔接的联运场景" fetchpriority="high" width="2172" height="724"/><div class="hero-shade"/><div class="hero-inner"><p class="hero-kicker"><span/>连接北方粮仓与南方市场</p><h1>数智联运<span class="hero-dot"> · </span><br/>畅通南北</h1><p class="hero-subtitle">让粮食运输更智能、更透明、更高效。<br/>从一份需求到全程交付，辽粮智运连接每一程。</p><div class="hero-actions"><button class="portal-btn primary" @click="scrollTo('value')">了解平台<Icon name="arrow" :size="18"/></button><router-link class="portal-btn light" to="/workbench"><Icon name="play" :size="16"/>立即体验</router-link></div><div class="hero-modes"><span><Icon name="truck" :size="17"/>公路</span><i/><span><Icon name="train" :size="17"/>铁路</span><i/><span><Icon name="anchor" :size="17"/>港口</span><i/><span><Icon name="ship" :size="17"/>水运</span></div></div><div class="hero-caption"><span>一程相连 · 全程协同</span><small>GRAIN MULTIMODAL LOGISTICS</small></div><button class="hero-scroll" aria-label="查看客户价值" @click="scrollTo('value')"><Icon name="down" :size="21"/></button></section>
  <section id="value" class="portal-section value-section"><div class="portal-section-heading"><p class="portal-eyebrow">为粮食运输创造价值</p><h2>每一程，都更从容</h2><p>复杂的运输协同，清晰的业务体验。</p></div><div class="value-grid"><article v-for="v in values" :key="v.title"><BusinessArt :kind="v.art" :size="86"/><h3>{{v.title}}</h3><strong>{{v.lead}}</strong><p>{{v.description}}</p></article></div></section>
  <section id="workflow" class="workflow-section"><div class="portal-section"><div class="portal-section-heading"><p class="portal-eyebrow">一站式业务协同</p><h2>从运输需求，到全程交付</h2><p>贯通关键环节，让每一步都衔接有序。</p></div><div class="workflow-steps"><article v-for="(s,i) in steps" :key="s.title"><div class="workflow-icon"><Icon :name="s.icon" :size="29"/><span>{{String(i+1).padStart(2,'0')}}</span></div><h3>{{s.title}}</h3><p>{{s.description}}</p><Icon v-if="i<steps.length-1" class="workflow-arrow" name="arrow" :size="22"/></article></div><p class="workflow-foot"><Icon name="network" :size="17"/>公路、铁路、水运灵活组合 · 贸易方与承运方协同推进</p></div></section>
  <section id="capabilities" class="portal-section capability-section"><div class="portal-section-heading left"><div><p class="portal-eyebrow">平台核心能力</p><h2>让联运业务，形成完整闭环</h2></div><p>规划有依据，执行有衔接，<br/>过程有记录，数据有价值。</p></div><div class="capability-grid"><article v-for="c in capabilities" :key="c.title"><span><Icon :name="c.icon" :size="28"/></span><div><h3>{{c.title}}</h3><p>{{c.description}}</p></div></article></div></section>
  <section id="ai-service" class="ai-section"><div class="portal-section ai-layout"><div class="ai-story"><p class="portal-eyebrow">辽粮 AI 智能服务</p><h2>懂粮食，也懂运输。</h2><p>把繁杂信息整理为清晰答案，<br/>让每一次判断都有业务依据。</p><img src="/assets/portal/liaoliang-ai.webp" alt="辽粮 AI 智能体" width="340" height="340" loading="lazy"/></div><div class="ai-service-grid"><article v-for="a in aiServices" :key="a.title"><Icon :name="a.icon" :size="25"/><h3>{{a.title}}</h3><p>{{a.description}}</p></article></div></div></section>
  <section id="product" class="product-section"><div class="portal-section"><div class="portal-section-heading"><p class="portal-eyebrow">产品展示</p><h2>业务工作台，一屏掌握运输</h2><p>快捷发起业务，集中处理待办，掌握运输进度与风险。</p></div><PlatformShowcase/><div class="product-tags"><span><Icon name="check" :size="15"/>多程衔接</span><span><Icon name="check" :size="15"/>业务协同</span><span><Icon name="check" :size="15"/>全程可视</span><span><Icon name="check" :size="15"/>授权数据</span></div></div></section>
  <section class="portal-section ecosystem-section"><div class="portal-section-heading"><p class="portal-eyebrow">联运生态</p><h2>连接伙伴，共赴每一程</h2><p>面向粮食产业与多式联运上下游，构建开放的业务协作网络。</p></div><div class="ecosystem-grid"><article v-for="p in partners" :key="p.name"><Icon :name="p.icon" :size="29"/><strong>{{p.name}}</strong></article></div></section>
  <section class="portal-conversion"><div><img src="/assets/liaoliang-logo.png" alt="" width="45" height="48"/><p>数智相连，运达未来。</p><h2>让下一程粮食运输，从这里开始</h2><router-link class="portal-btn primary" to="/workbench">进入智能多式联运平台<Icon name="arrow" :size="18"/></router-link></div></section>
 </main>
 <footer class="portal-footer"><div><strong>辽粮智运</strong><span>智能多式联运平台</span></div><p>数智联运 · 畅通南北</p><a href="#portal-main" aria-label="返回顶部">返回顶部<Icon name="up" :size="15"/></a></footer>
</div>
</template>
<style src="./portal.css"/>

