<script setup lang="ts">
import {ref,reactive,computed,onMounted} from 'vue';
import {ElMessage} from 'element-plus';
import {api,get,message} from '../api';
import {useAuth} from '../stores/auth';
import {date} from '../fulfillment';
const auth=useAuth(),rows=ref<any[]>([]),carriers=ref<any[]>([]),total=ref(0),busy=ref(false),saving=ref(false),error=ref(''),formError=ref(''),open=ref(false);
const query=reactive({q:'',page:1,pageSize:20}),f=reactive<any>({});
const writable=computed(()=>auth.can(auth.user?.businessEntity.type==='PLATFORM'?'entities:write':'service:write'));
async function load(){busy.value=true;error.value='';try{const result=await get('/vessels',query);rows.value=result.items;total.value=result.total;carriers.value=result.carriers;}catch(e){error.value=message(e);}finally{busy.value=false;}}
function edit(row?:any){Object.keys(f).forEach(k=>delete f[k]);Object.assign(f,row||{name:'',voyage:'',mmsi:'',enabled:true,carrierId:auth.user?.businessEntity.type==='CARRIER'?auth.user.businessEntityId:''});formError.value='';open.value=true;}
async function save(){if(!f.name.trim()||!f.voyage.trim()||!f.carrierId||!/^[2-7]\d{8}$/.test(f.mmsi)){formError.value='请填写物流企业、船名、航次和有效的 9 位 MMSI';return;}saving.value=true;try{const data={name:f.name,voyage:f.voyage,mmsi:f.mmsi,carrierId:f.carrierId,enabled:f.enabled,version:f.version};await (f.id?api.put('/vessels/'+f.id,data):api.post('/vessels',data));open.value=false;await load();ElMessage.success('船舶档案已保存');}catch(e){formError.value=message(e);}finally{saving.value=false;}}
onMounted(load);
</script>
<template><div><el-alert v-if="error" :title="error" type="error" :closable="false"/><form class="vessel-search" @submit.prevent="query.page=1;load()"><el-input v-model="query.q" placeholder="船名 / 航次 / MMSI" aria-label="搜索船舶档案" clearable/><div><el-button native-type="submit" :loading="busy">搜索</el-button><el-button @click="query.q='';query.page=1;load()">重置</el-button></div></form><section class="table-panel"><header class="list-toolbar"><strong>船舶档案 · {{total}}</strong><el-button v-if="writable" type="primary" @click="edit()">登记船舶</el-button></header><el-table :data="rows" v-loading="busy"><el-table-column prop="name" label="船名" min-width="180"/><el-table-column prop="voyage" label="航次" min-width="130"/><el-table-column prop="mmsi" label="MMSI" width="150"/><el-table-column prop="carrier" label="物流运营企业" min-width="210"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'使用中':'已停用'}}</el-tag></template></el-table-column><el-table-column label="登记时间" min-width="180"><template #default="{row}">{{date(row.createdAt)}}</template></el-table-column><el-table-column v-if="writable" label="操作" width="90"><template #default="{row}"><el-button link type="primary" @click="edit(row)">编辑</el-button></template></el-table-column><template #empty><el-empty description="暂无船舶档案"/></template></el-table><div class="pagination"><el-pagination v-model:current-page="query.page" :total="total" :page-size="query.pageSize" layout="total, prev, pager, next" @current-change="load"/></div></section><el-dialog v-model="open" :title="f.id?'编辑船舶档案':'登记船舶'" width="min(560px,94vw)" :close-on-click-modal="!saving"><el-alert v-if="formError" :title="formError" type="error" :closable="false"/><el-form label-position="top"><el-form-item label="物流运营企业" required><el-select v-model="f.carrierId" :disabled="!!f.id||auth.user?.businessEntity.type==='CARRIER'" aria-label="船舶所属物流企业"><el-option v-for="c in carriers" :key="c.id" :value="c.id" :label="c.name"/></el-select></el-form-item><div class="form-grid"><el-form-item label="船名" required><el-input v-model="f.name" aria-label="档案船名" maxlength="100"/></el-form-item><el-form-item label="航次" required><el-input v-model="f.voyage" aria-label="档案航次" maxlength="100"/></el-form-item></div><el-form-item label="MMSI（海上移动业务识别码）" required><el-input v-model="f.mmsi" aria-label="档案MMSI" maxlength="9" inputmode="numeric"/></el-form-item><el-form-item label="使用状态"><el-switch v-model="f.enabled" active-text="使用中" inactive-text="停用"/></el-form-item></el-form><template #footer><el-button :disabled="saving" @click="open=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></div></template>
<style scoped>.vessel-search{display:flex;gap:20px;padding:20px;background:#fff;border:1px solid var(--border);border-radius:8px;margin-bottom:20px;align-items:center}.vessel-search>.el-input{max-width:360px}.vessel-search>div{margin-left:auto;display:flex;gap:8px}.vessel-search .el-button{margin:0}.el-select{width:100%}</style>
